// Nur astrologische Zuordnungen; Namen und Beinamen stammen aus Religionen.
// Die Celestialen sind vollkommen gut und unveränderlich. gift benennt die
// Tugendneigung des Menschen; trial die Sünde, die dieses Potenzial verdirbt.
// shadowId bezeichnet einen Widersacher, keine ergänzende Seite der Gottheit.
export const MONTH_SIGNS = Object.freeze([
  { id: 'orin', shadowId: 'amon', kind: 'celestial', motif: 'Die Eule', gift: 'Wahrhaftige Erkenntnis', trial: 'Täuschung und Wissensgier', reading: 'Wer im Zeichen des Mentors geboren wird, neigt dazu, Wahrheit zu suchen und Erkenntnis zum Wohl anderer einzusetzen. Amon sucht diese Anlage durch Wissensgier und Täuschung zu verderben: Geheimnisse werden gehortet, Menschen durch Halbwahrheiten gelenkt. Wo Aufrichtigkeit und Großzügigkeit fehlen, wird das Erkenntnisvermögen missbraucht. Orins Weisheit selbst bleibt vollkommen gut.' },
  { id: 'mariel', shadowId: 'lunara', kind: 'celestial', motif: 'Die Taube', gift: 'Barmherzigkeit', trial: 'Herzlosigkeit und Besitzgier', reading: 'Wer im Zeichen der Mutter geboren wird, neigt zu Barmherzigkeit, Fürsorge und selbstloser Liebe. Lunara sucht dieses Potenzial durch Herzlosigkeit und Besitzgier zu verdrängen: Ein Mensch verweigert dann Trost oder bindet andere an sich, um allein über sie zu verfügen. Darin fehlt die Liebe, die Mariel unveränderlich verkörpert. Die Witwe verdirbt menschliche Fürsorge; sie vervollständigt sie nicht.' },
  { id: 'maldras', shadowId: 'bhaal', kind: 'celestial', motif: 'Der Schild', gift: 'Gerechter Schutz', trial: 'Unterwerfung und Entweihung', reading: 'Wer im Zeichen des Templers geboren wird, neigt dazu, Schwache zu schützen und gerecht zu handeln. Bhaal verführt dazu, Schutzgewalt zur Unterwerfung zu missbrauchen und das Anvertraute zu entweihen. Auch wer sich selbst für gerecht hält, kann diesem Versuch erliegen, wenn Gnade und Achtung in seinem Handeln fehlen. Maldras bleibt der unveränderliche Maßstab des gerechten Schutzes.' },
  { id: 'sylvana', shadowId: 'zatrach', kind: 'celestial', motif: 'Die Hindin', gift: 'Achtsame Verbundenheit', trial: 'Rücksichtslose Besitzgier', reading: 'Wer im Zeichen der Hirtin geboren wird, neigt zur Fürsorge für Lebewesen und zur Achtung vor dem Anvertrauten. Zatrach sucht diese Anlage durch rücksichtslose Besitzgier zu verderben. Wo die Achtung fehlt, behandelt der Mensch das Lebendige nur noch als Beute und Mittel zum eigenen Vorteil. Sylvanas Güte kennt diesen Mangel nicht.' },
  { id: 'jovena', shadowId: 'azrath-morvath', kind: 'lesser', motif: 'Das Kleeblatt', gift: 'Mitfreude', trial: 'Selbstsucht und Schadenfreude', reading: 'Wer im Zeichen der Glücksbringerin geboren wird, neigt dazu, Freude zu teilen und anderen Glück zu gönnen. Azrath und Morvath suchen diese Anlage durch Selbstsucht und Schadenfreude zu verdrängen: Der eigene Genuss wird wichtiger als das Wohl anderer, fremdes Unglück zur Unterhaltung. Damit fehlt gerade die Mitfreude, zu der dieses Zeichen befähigt.' },
  { id: 'lyris', shadowId: 'sanguine', kind: 'celestial', motif: 'Die Nachtigall', gift: 'Treue, Fürsorge und Kreativität', trial: 'Wollust, Untreue und Vernachlässigung', reading: 'Wer im Zeichen der Maid geboren wird, neigt zu ihren Tugenden: Enthaltsamkeit, Treue, Fürsorge und Kreativität. Sanguine sucht dieses Potenzial durch Wollust, Untreue, Faulheit und Vernachlässigung zu verderben. Wo Treue und Fürsorge fehlen, wird ein anderer Mensch zum Mittel des eigenen Genusses; wo schöpferische Hingabe fehlt, verkümmert das Talent. Diese Sünden ziehen die menschliche Anlage zum Guten herab. Lyris selbst bleibt vollkommen rein und unveränderlich.' },
  { id: 'selarion', shadowId: 'nemsara', kind: 'lesser', motif: 'Die Fackel', gift: 'Fairer Wettstreit', trial: 'Rachsucht und Hinterlist', reading: 'Wer im Zeichen des Herausforderers geboren wird, neigt zu fairem Wettstreit, Mut und Achtung vor dem Gegenüber. Nemsara sucht diesen Menschen zu Rachsucht und Hinterlist zu verführen. Fehlt die Achtung, soll der Gegner gedemütigt oder durch Betrug besiegt werden. Die Sünde zerstört damit den edlen Wettstreit, zu dem die Anlage befähigt.' },
  { id: 'baldran', shadowId: 'grimnar', kind: 'celestial', motif: 'Das Schwert', gift: 'Ehrenmut und Pflichttreue', trial: 'Grausamkeit und Plünderung', reading: 'Wer im Zeichen des Streiters geboren wird, neigt zu Ehrenmut, Pflichttreue und dem Schutz anderer. Grimnar will diese Stärke für Grausamkeit und Plünderung gewinnen. Wo Ehre und Mitgefühl fehlen, richtet ein Mensch seine Kraft gegen Schutzlose und nennt Gewalttätigkeit womöglich noch Tapferkeit. Der Mangel liegt im Menschen; Baldrans Tugend bleibt unversehrt.' },
  { id: 'auron', shadowId: 'nergaloth', kind: 'lesser', motif: 'Der Zirkel', gift: 'Verantwortung', trial: 'Gewissenlose Schädigung', reading: 'Wer im Zeichen des Erbauers geboren wird, neigt zu verantwortungsvollem Schaffen und zu Werken, die anderen dienen. Nergaloth sucht diese Fähigkeit durch Gewissenlosigkeit zu verderben. Wo Fürsorge und Verantwortung fehlen, wird Schaden aus Eigennutz bewusst hingenommen oder ein Werk zur Schädigung anderer eingesetzt. Das zerstört den guten Zweck des Schaffens.' },
  { id: 'tharim', shadowId: 'nyxara', kind: 'celestial', motif: 'Der Hammer', gift: 'Aufrichtigkeit und Fleiß', trial: 'Betrug und Hinterlist', reading: 'Wer im Zeichen des Knechts geboren wird, neigt zu ehrlicher Arbeit, Geduld und Verlässlichkeit. Nyxara lockt mit Gewinn durch Betrug und Hinterlist. Wo Aufrichtigkeit fehlt, kann ein Mensch die Früchte fremder Arbeit stehlen und sein Können zur Täuschung verwenden. Tharims Vollkommenheit bleibt bestehen; korrumpierbar ist der Mensch, der seinen Tugenden nachstrebt.' },
  { id: 'tethyra', shadowId: 'nhaera', kind: 'lesser', motif: 'Der Kompass', gift: 'Entdeckergeist und Heimkehr', trial: 'Heimkehrverzicht und Bindungsflucht', reading: 'Wer im Zeichen der Seemaid geboren wird, neigt zu Abenteuerlust, Freiheit und verantwortlichem Entdeckergeist. Nhaera versucht, diese Anlage durch Heimkehrverzicht und Bindungsflucht zu verderben: Ein Mensch gibt bewusst die Menschen und Verantwortung preis, die seinem Aufbruch ein Zuhause gegenüberstellen. Abenteuer zu suchen ist gut; eine Heimkehr bleibt essenziell. Ohne wirkliche Zugehörigkeit droht das Schicksal der Heimatlosen. Unfreiwillige Heimatlosigkeit und erlittene Einsamkeit sind keine Sünden.' },
  { id: 'orith', shadowId: 'migdal', kind: 'lesser', motif: 'Der Knoten', gift: 'Demütige Versenkung', trial: 'Machtgier', reading: 'Wer im Zeichen des Mystikers geboren wird, neigt zu geduldiger Versenkung und einem demütigen Umgang mit den Geheimnissen der Magie. Migdal sucht diesen Menschen durch das Versprechen müheloser Macht zu gewinnen. Wo Demut und Gewissen fehlen, werden Erkenntnis und Begabung dem eigenen Herrschaftsverlangen unterworfen. Die Versuchung verdirbt das gute Potenzial, das sie ausnutzt.' },
  { id: 'kharon', shadowId: 'hela', kind: 'celestial', motif: 'Der Rabe', gift: 'Fürsorge und Versöhnung', trial: 'Lebensverachtung', reading: 'Wer im Zeichen des Hüters geboren wird, neigt dazu, Trauernde zu trösten, Frieden zu stiften und die Würde der Lebenden wie der Toten zu achten. Hela sucht diese Anlage durch Verachtung des Lebens zu verdrängen. Wo Fürsorge fehlt, wird einem anderen Schutz und Beistand bewusst verweigert. Kharons Güte bleibt unveränderlich; weder Trauer noch Vergänglichkeit sind selbst diese Sünde.' }
].map((sign, index) => Object.freeze({ ...sign, month: index + 1 })));

export const DRAGON = Object.freeze({ id: 'ordan', shadowId: 'adar', kind: 'dragon', motif: 'Der Drache', everyYears: 1000, gift: 'Demut und Weitsicht', trial: 'Hochmut und Selbstvergötterung', reading: 'Wer in der Drachennacht geboren wird, trägt neben seinem Monatszeichen eine besondere Neigung zu Demut, Weitsicht und verantwortlicher Führung. Adar will dieses Potenzial durch Hochmut verderben: Ein Mensch setzt den eigenen Willen an die Stelle des Guten und hält sich selbst für dessen höchsten Maßstab. Darin fehlen die Demut und die Anerkennung des Guten, die Ordan vollkommen verkörpert. Der Vater bleibt unveränderlich; Adar strebt danach, Menschen von ihm abzuwenden.' });

// Kontinuierliche, zum 468-Tage-Jahr teilerfremde Umläufe: kein Zufallszustand.
export const SOVEREIGNS = Object.freeze([
  { id: 'nimue', shadowId: 'thraal', period: 47, offset: 8, duration: 3, gift: 'Reinheit und Güte', trial: 'Raffgier und Erbarmungslosigkeit', motif: 'Die Quelle', reading: 'Steht die Dame des Sees bei einer Geburt am Himmel, wird dies als zusätzliche Neigung zu Reinheit, Güte und aufrichtiger Fürsorge gelesen. Thraal sucht diese Anlage durch Raffgier und Erbarmungslosigkeit zu verderben. Wo Güte fehlt, nimmt ein Mensch anderen das Lebensnotwendige und lässt Hilfesuchende ihrem Schicksal. Nimues reine Güte bleibt unverändert; der Verschlinger trachtet danach, ihr Wirken im Menschen zu verdrängen.' },
  { id: 'rhea', shadowId: 'syressa', period: 73, offset: 29, duration: 4, gift: 'Beständigkeit', trial: 'Hochmut und verweigerter Beistand', motif: 'Der Berg', reading: 'Steht Rhea bei einer Geburt am Himmel, gilt dies als zusätzliche Neigung zu Beständigkeit, Verlässlichkeit und schützendem Beistand. Syressa, ihre durch Stolz gefallene Schwester, sucht dieses Potenzial durch Hochmut und verweigerten Beistand zu verderben. Wo Fürsorge fehlt, wird die Tür dem Schutzsuchenden verschlossen und ein eigenes Unrecht aus Stolz nicht eingestanden. Rheas Güte bleibt der vollkommene Maßstab; ihre Tugenden brauchen Syressas Verderbnis nicht.' },
  { id: 'zephyr', shadowId: 'maelach', period: 97, offset: 51, duration: 3, gift: 'Verantwortete Freiheit', trial: 'Heuchelei, Wahrheitsverdrehung und Hetze', motif: 'Die Feder', reading: 'Steht Zephyr bei einer Geburt am Himmel, gilt dies als zusätzliche Neigung zu verantworteter Freiheit, aufrichtiger Sprache und der Achtung vor anderen Stimmen. Maelach verführt dazu, Wahrheit aus Eigeninteresse zu verdrehen, Gerüchte zu schüren und Menschen gegeneinander aufzubringen. Wo Aufrichtigkeit und Verantwortung fehlen, wird die Gabe der Sprache zur Täuschung missbraucht. Der Heuchler korrumpiert den Menschen; Zephyrs gutes Wesen bleibt unverändert.' },
  { id: 'aelthar', shadowId: 'nymhra', period: 127, offset: 79, duration: 2, gift: 'Zusammenhalt', trial: 'Selbsttäuschung, Misstrauen und Verrat', motif: 'Der Blitz', reading: 'Steht Aelthar bei einer Geburt am Himmel, gilt dies als zusätzliche Neigung zu Einsicht, Zusammenhalt und Entschlossenheit. Nymhra sucht diese Anlage durch bewusste Selbsttäuschung, geschürtes Misstrauen und den Verrat an Gefährten zu verderben. Wo Wahrhaftigkeit und Beistand fehlen, wird einer erwünschten Eingebung mehr geglaubt als überprüfbarer Wahrheit. Schlaf, Träume und das Erleiden eines Albtraums sind keine Sünden. Aelthars Güte bleibt unverändert.' },
  { id: 'thyrael', shadowId: 'dagon', period: 163, offset: 113, duration: 3, gift: 'Erneuerung zum Guten', trial: 'Herrschsucht und Zerstörungswille', motif: 'Die Flamme', reading: 'Steht der Herr der Flammen bei einer Geburt am Himmel, wird dies als zusätzliche Neigung gelesen, Erneuerung zum Wohl anderer zu bewirken. Dagon sucht diese Tatkraft durch Herrschsucht und Zerstörungswillen zu verderben. Wo Demut und Fürsorge fehlen, zwingt ein Mensch anderen seinen Willen auf und vernichtet, was er zu erneuern vorgibt. Die Sünde zerstört den guten Zweck seines Handelns.' }
].map(sign => Object.freeze({ ...sign, kind: 'sovereign' })));

export const ALL_SIGNS = Object.freeze([...MONTH_SIGNS, DRAGON, ...SOVEREIGNS]);

export const SKY_BODIES = Object.freeze({
  sun: Object.freeze({ id: 'aine', name: 'Áine', title: 'Das goldene Auge', reading: 'Alerias Sonne trägt den Namen Áine. Ihr Licht durchmisst den Jahreskreis und verbindet den Wechsel der dreizehn Zeichen mit dem Rhythmus des Tages.' }),
  moons: Object.freeze([
    Object.freeze({ id: 'brigh', name: 'Brìgh', title: 'Die silberne Wächterin', period: 36, reading: 'Der große, silberhelle Mond begleitet Fürsorge, Heimkehr und Bewahrung. In der Sternendeutung wird er Mariels Obhut zugeordnet.' }),
    Object.freeze({ id: 'aonghus', name: 'Aonghus', title: 'Der blaue Wanderer', period: 52, reading: 'Der kleinere, bläulich schimmernde Mond steht für Sehnsucht, Traum und schöpferischen Wandel. Die Sterndeuter lesen in ihm eine Nähe zu Lyris und Orin.' })
  ])
});
