import { WEDDING_STATUS, ATTENDANCE, GIFT_STATUS } from './wedding-schema.mjs';
import { weddingText as e, weddingGroups, weddingDate, weddingCalendarHref, selectWeddingGuests } from './wedding-model.mjs';
import { renderGuestPortraits } from './wedding-portraits.mjs';

const paragraphs = value => value.split(/\n\s*\n/).filter(Boolean).map(line => `<p>${e(line).replace(/\n/g, '<br>')}</p>`).join('');
const editButton = (list, id, editing, label = 'Bearbeiten') => editing ? `<button type="button" class="wedding-text-button" data-wedding-action="edit-entry" data-list="${list}" data-id="${e(id)}">${label}</button>` : '';
function heading(number, kicker, title, list, editing) {
  return `<header class="wedding-section-heading"><span aria-hidden="true">${number}</span><div><p class="wedding-eyebrow">${kicker}</p><h2>${title}</h2></div>${editing && list ? `<button type="button" class="wedding-small-button" data-wedding-action="add-entry" data-list="${list}">+ Eintrag</button>` : ''}</header>`;
}
export function renderWedding(wedding, { eventsBase, calendar, editing, dirty, revision, conflict }) {
  const media = path => new URL(path, eventsBase).href;
  const gifts = wedding.guests.filter(guest => guest.gift);
  return `<div class="wedding-workbar"><p><span class="wedding-save-dot${dirty ? ' is-draft' : ''}"></span>${dirty ? 'Lokaler Entwurf' : 'Veröffentlichte Fassung'} <span class="wedding-revision">· Fassung ${revision}</span>${conflict ? ' · Online liegt eine neuere Fassung vor' : ''}</p><div><button type="button" data-wedding-action="toggle-edit" aria-pressed="${editing}">${editing ? 'Leseansicht' : 'Seite bearbeiten'}</button><button type="button" data-wedding-action="export">Exportieren</button>${dirty ? '<button type="button" data-wedding-action="publish" class="wedding-primary">Veröffentlichen</button>' : ''}</div></div>
  <section class="wedding-cover" id="brautpaar" aria-labelledby="wedding-title"><div class="wedding-cover-copy"><p class="wedding-eyebrow">Das Hochzeitsfest <span>✦</span> ${e(wedding.location || 'Ein gemeinsamer Anfang')}</p><p class="wedding-hero-status">${e(WEDDING_STATUS[wedding.status])}</p><h1 id="wedding-title">${e(wedding.couple[0].name)}<em><span>&amp;</span> ${e(wedding.couple[1].name)}</em></h1><p class="wedding-cover-intro">${e(wedding.intro || 'Die Vorbereitungen für diese Hochzeit beginnen hier.')}</p>
    <div class="wedding-house-pair">${wedding.couple.map(person => `<div class="wedding-house">${person.crest ? `<img src="${e(media(person.crest))}" alt="Wappen ${e(person.house)}" width="72" height="86">` : '<span class="wedding-crest-placeholder" aria-hidden="true">❧</span>'}<div><small>${e(person.title)}</small><strong>${e(person.name)} ${e(person.house)}</strong><span>Haus ${e(person.house || 'noch offen')}</span></div></div>`).join('')}</div>
    <div class="wedding-cover-actions"><a class="wedding-primary wedding-button" href="#gaestebuch">Das Gästebuch öffnen ↗</a>${editing ? '<button type="button" class="wedding-text-button" data-wedding-action="edit-details">Brautpaar &amp; Eckdaten bearbeiten</button>' : '<a href="#ablauf" class="wedding-text-link">Zur Vorbereitung ↓</a>'}</div>
  </div><figure class="wedding-cover-portrait">${wedding.image ? `<img src="${e(media(wedding.image))}" alt="${e(wedding.couple[0].name)} und ${e(wedding.couple[1].name)}" width="1024" height="1536" fetchpriority="high">` : '<div class="wedding-portrait-empty"><span aria-hidden="true">❧</span><p>Ein gemeinsamer Anfang</p></div>'}<figcaption>${wedding.subtitle ? `<span>${e(wedding.subtitle)}</span>` : ''}${e(wedding.title)}</figcaption></figure></section>
  <div class="wedding-facts"><div><small>Der Ort</small><strong>${e(wedding.location || 'Noch in Abstimmung')}</strong><span>${e(wedding.region)}</span></div><div><small>Der Termin</small><strong>${e(weddingDate(wedding, calendar))}</strong><a href="${e(weddingCalendarHref(wedding, eventsBase))}">${wedding.date.year ? 'Im Kalender ansehen' : 'Kalender von Aleria'} ↗</a></div><div><small>Das Gästebuch</small><strong>${wedding.guests.length} Einträge</strong><span>${gifts.length} Geschenkbeiträge vermerkt</span></div></div>
  <div class="wedding-book-layout"><aside class="wedding-section-register"><p class="wedding-eyebrow">In diesem Festbuch</p><nav aria-label="Hochzeitskapitel"><a href="#buendnis"><span>I</span>Das Bündnis</a><a href="#ablauf"><span>II</span>Der Ablauf</a><a href="#gaestebuch"><span>III</span>Das Gästebuch</a><a href="#gaben"><span>IV</span>Die Gaben</a><a href="#vorbereitung"><span>V</span>Vorbereitung</a></nav><p class="wedding-register-note">Zwei Häuser.<br>Ein gemeinsamer Anfang.</p>${editing ? '<button class="wedding-text-button" type="button" data-wedding-action="load-latest">Online-Fassung laden</button><button class="wedding-text-button" type="button" data-wedding-action="discard">Lokalen Entwurf verwerfen</button>' : ''}</aside>
  <div class="wedding-book-content"><section id="buendnis">${heading('I','Zwei Häuser verbinden sich','Das Bündnis',null,editing)}<div class="wedding-prose">${paragraphs(wedding.background) || '<p>Die Geschichte dieses Ehebündnisses wird noch ergänzt.</p>'}</div></section>
  <section id="ablauf">${heading('II','Von der Trauung zum Ausklang','Der Ablauf','schedule',editing)}${renderWeddingSchedule(wedding, editing)}</section>
  <section id="gaestebuch">${heading('III','Familie, Freunde & Weggefährten','Das Gästebuch','guests',editing)}<p class="wedding-section-intro">Die Menschen hinter dem Fest – mit ihren Rollen, Aufgaben und mitgebrachten Gaben.</p>
    <form class="wedding-guest-tools" role="search"><label class="wedding-search"><span aria-hidden="true">⌕</span><span class="wedding-sr-only">Gäste durchsuchen</span><input type="search" data-wedding-search placeholder="Name, Haus, Aufgabe oder Geschenk …" maxlength="200"></label><div><label>Gesellschaft<select data-wedding-group><option value="all">Alle Gruppen</option>${Object.entries(weddingGroups(wedding)).map(([id,label]) => `<option value="${id}">${e(label)}</option>`).join('')}</select></label><label>Teilnahme<select data-wedding-attendance><option value="all">Alle</option>${Object.entries(ATTENDANCE).map(([id,label]) => `<option value="${id}">${e(label)}</option>`).join('')}</select></label></div></form>
    <div data-wedding-guests>${renderWeddingGuests(wedding, {}, editing, eventsBase)}</div>
  </section><section id="gaben">${heading('IV','Mit guten Wünschen überreicht','Die Gaben',null,editing)}<p class="wedding-section-intro">Vorgemerkte Geschenkbeiträge. Ob eine Gabe bereits überreicht wurde, wird gesondert festgehalten.</p><div class="wedding-gift-grid">${gifts.map(guest => `<article class="wedding-gift"><small>${e(GIFT_STATUS[guest.giftStatus])}</small><h3>${e(guest.gift)}</h3><p>Von ${e(guest.name)}${guest.house ? ` · ${e(guest.house)}` : ''}</p>${editButton('guests',guest.id,editing,'Geschenk bearbeiten')}</article>`).join('') || '<p class="wedding-empty-note">Noch keine Geschenkbeiträge vermerkt.</p>'}</div></section>
  <section id="vorbereitung">${heading('V','Damit der Tag seinen Platz findet','Die Vorbereitung','tasks',editing)}<p class="wedding-section-intro">${wedding.tasks.filter(task => task.done).length} von ${wedding.tasks.length} Aufgaben erledigt.</p><ul class="wedding-task-list">${wedding.tasks.map(task => `<li><div class="wedding-task-state">${editing ? `<input type="checkbox" data-wedding-task="${e(task.id)}" aria-label="${e(task.title)} erledigt"${task.done ? ' checked' : ''}>` : `<span aria-label="${task.done ? 'Erledigt' : 'Offen'}">${task.done ? '✓' : '○'}</span>`}</div><div><h3>${e(task.title)}</h3>${task.owner ? `<small>Verantwortlich: ${e(task.owner)}</small>` : ''}${task.notes ? `<p>${e(task.notes)}</p>` : ''}</div>${editButton('tasks',task.id,editing)}</li>`).join('') || '<li class="wedding-empty-note">Die Vorbereitungsliste ist noch offen.</li>'}</ul>
    ${wedding.notes ? `<aside class="wedding-planning-note"><p class="wedding-eyebrow">Notizen zum Fest</p>${paragraphs(wedding.notes)}</aside>` : ''}
    ${editing ? '<button type="button" class="wedding-text-button" data-wedding-action="edit-details">Hintergrund &amp; Notizen bearbeiten</button>' : ''}
  </section></div></div>`;
}

export function renderWeddingGuests(wedding, filters, editing, eventsBase) {
  const guests = selectWeddingGuests(wedding.guests, filters);
  const groups = weddingGroups(wedding);
  return `<p class="wedding-result-count" role="status" aria-live="polite">${guests.length} von ${wedding.guests.length} Einträgen</p>${Object.entries(groups).map(([id,label]) => {
    const rows = guests.filter(guest => guest.group === id);
    if (!rows.length) return id === 'delegations' && (!filters.group || filters.group === 'all' || filters.group === id) && !filters.query && (!filters.attendance || filters.attendance === 'all') ? `<div class="wedding-guest-group"><h3>${e(label)}</h3><p class="wedding-empty-note">Noch keine Häuser oder Delegationen als Gruppe eingetragen.</p></div>` : '';
    return `<section class="wedding-guest-group" data-guest-group="${id}" aria-label="${e(label)}"><h3><span>${e(label)}</span><small>${String(rows.length).padStart(2,'0')} ${rows.length === 1 ? 'Eintrag' : 'Einträge'}</small></h3><div class="wedding-guest-cards">${rows.map(guest => renderGuestCard(guest,editing,eventsBase)).join('')}</div></section>`;
  }).join('')}${!guests.length && wedding.guests.length ? '<p class="wedding-empty-note">Keine passenden Gäste. Versucht einen anderen Namen oder eine andere Gruppe.</p>' : ''}`;
}
function renderGuestCard(guest, editing, eventsBase) {
  const role = [guest.role,guest.count ? `${guest.count} Personen` : ''].filter(Boolean).join(' · ');
  return `<article class="wedding-guest-card" data-guest-id="${e(guest.id)}">
    <header>${renderGuestPortraits(guest,eventsBase)}<span class="wedding-attendance" data-status="${guest.attendance}">${e(ATTENDANCE[guest.attendance])}</span></header>
    <p class="wedding-guest-role">${e(role)}</p><h4>${e(guest.name)}</h4><p class="wedding-guest-house">${e([guest.rank,guest.house ? `Haus ${guest.house}` : ''].filter(Boolean).join(' · '))}</p>
    <dl>${guest.leader ? `<div><dt>Oberhaupt</dt><dd>${e(guest.leader)}</dd></div>` : ''}<div><dt>Aufgabe beim Fest</dt><dd>${e(guest.task) || '<span class="wedding-muted">Noch offen</span>'}</dd></div><div><dt>Die Gabe</dt><dd>${e(guest.gift) || '<span class="wedding-muted">Keine Angabe</span>'}${guest.gift ? `<small class="wedding-gift-status">${e(GIFT_STATUS[guest.giftStatus])}</small>` : ''}</dd></div></dl>
    ${editing ? `<footer>${editButton('guests',guest.id,true,'Gast & Beitrag bearbeiten')}</footer>` : ''}</article>`;
}
function renderWeddingSchedule(wedding, editing) {
  if (!wedding.schedule.length) return '<div class="wedding-schedule-empty"><span aria-hidden="true">❧</span><h3>Der Tag nimmt noch Gestalt an.</h3><p>Die Reihenfolge und Uhrzeiten für Trauung, Empfang und Feier werden noch abgestimmt.</p></div>';
  return `<ol class="wedding-schedule">${wedding.schedule.map((item,index) => `<li><div class="wedding-schedule-time"><small>${String(index + 1).padStart(2,'0')}</small><strong>${e(item.time) || 'Zeit offen'}</strong></div><div><h3>${e(item.title)}</h3>${item.location ? `<small>${e(item.location)}</small>` : ''}<p>${e(item.description)}</p>${editButton('schedule',item.id,editing)}${editing ? `<button type="button" class="wedding-text-button" data-wedding-action="move-schedule" data-id="${e(item.id)}" data-step="-1" aria-label="${e(item.title)} nach oben"${index === 0 ? ' disabled' : ''}>↑</button><button type="button" class="wedding-text-button" data-wedding-action="move-schedule" data-id="${e(item.id)}" data-step="1" aria-label="${e(item.title)} nach unten"${index === wedding.schedule.length - 1 ? ' disabled' : ''}>↓</button>` : ''}</div></li>`).join('')}</ol>`;
}
export function renderWeddingRegistry(entries, eventsBase) {
  return `<section class="wedding-registry-page"><p class="wedding-eyebrow">Feste &amp; Ehebündnisse</p><h1>Das Hochzeitsregister</h1><p>Die gemeinsamen Anfänge der Häuser Alerias.</p><div class="wedding-registry-grid">${entries.map(entry => `<a href="${e(new URL(entry.id === 'tudwal-revelyn' ? 'Hochzeiten/Haus-Draig-und-Penderyn.html' : `hochzeit.html?id=${encodeURIComponent(entry.id)}`,eventsBase))}"><small>${e(WEDDING_STATUS[entry.status] || 'In Vorbereitung')}</small><h2>${e(entry.title)}</h2><span>Das Festbuch öffnen ↗</span></a>`).join('')}</div><a class="wedding-button wedding-primary" href="${e(new URL('Hochzeitsevent.html',eventsBase))}">Neue Hochzeit vorbereiten ↗</a></section>`;
}
