// Generated by scripts/build-house-content.mjs. Edit haus.content.mjs instead.
window.HAEUSER_DATA = {
  "meta": {
    "id": "haus-madryn",
    "title": "Haus Madryn – Aleria",
    "type": "Ritterhaus",
    "status": "Active",
    "template": "kleinehaeuser",
    "storage": {
      "document": "haus-madryn"
    }
  },
  "name": "Haus Madryn",
  "hierarchy": [
    {
      "type": "Sammlung",
      "name": "Familien Häuser und Clans",
      "slug": "familien-hauser-und-clans"
    },
    {
      "type": "Kontinent",
      "name": "Estryll",
      "slug": "estryll"
    },
    {
      "type": "Königreich",
      "name": "Cenyr",
      "slug": "cenyr"
    },
    {
      "type": "Grafschaft",
      "name": "Celtigerns Wacht",
      "slug": "celtigerns-wacht"
    },
    {
      "type": "Region",
      "name": "Rhonwens Tränen",
      "slug": "rhonwens-tranen"
    },
    {
      "type": "Haus",
      "name": "Haus Madryn",
      "slug": "haus-madryn"
    }
  ],
  "layout": "responsive",
  "classification": {
    "category": "Familien Häuser und Clans",
    "houseType": "Ritterhaus",
    "scale": "Ritterhaus",
    "parentHouseId": "",
    "rootHouseId": "haus-madryn",
    "territoryId": "herrschaft-rhonwens-traenen"
  },
  "profile": {
    "highestTitle": "Ritterherr",
    "rank": "Ritterherr",
    "houseType": "Ritterhaus",
    "motto": "",
    "quoteAuthor": "",
    "seat": "",
    "affiliation": "Celtigerns Wacht",
    "liege": "",
    "patron": "",
    "knightingPatron": "",
    "troopStrength": "",
    "tiarna": "",
    "kerns": "",
    "fleet": "",
    "founding": "",
    "milestoneOne": "",
    "milestoneTwo": "",
    "people": "",
    "wealth": "",
    "religion": "",
    "patronDeities": "",
    "origin": "",
    "cadetBranches": "",
    "allies": "",
    "enemies": ""
  },
  "profileLabels": {
    "tiarna": "Ritter",
    "kerns": "Knechte"
  },
  "showMotto": false,
  "sections": {
    "overview": "Haus Madryn ist in Rhonwens Tränen in Celtigerns Wacht verzeichnet. Weitere Inhalte folgen.",
    "history": "Folgt …",
    "traditions": "Folgt …",
    "knighthood": "Folgt …",
    "succession": "Folgt …",
    "holdings": "Folgt …",
    "cultureReligion": "Folgt …",
    "conflictsAlliances": "Folgt …",
    "values": "Folgt …",
    "court": "Folgt …",
    "familyTree": "Die Hausbio öffnet sich über das Wappen im Stammbaum. Personen und Verbindungen sind in der Familienakte verzeichnet.",
    "historicalFigures": "Folgt …"
  },
  "sectionTitles": {
    "knighthood": "4. Rittertum"
  },
  "images": {
    "haus-wappen": {
      "src": "../Stammbäume/assets/images/houses/Rhonwens Tränen/Ritterliche/Madryn.png",
      "alt": "Wappen von Haus Madryn",
      "format": "square"
    },
    "haus-hauptbild": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Rhonwens_Traenen/Haus_Madryn/assets/krieger.png",
      "alt": "Krieger von Haus Madryn",
      "format": "portrait",
      "maxHeight": 580
    },
    "haus-banner": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Rhonwens_Traenen/Haus_Arwydd/assets/herrschaftsbanner.png",
      "href": "../Kontinente/Estryll/Königreich Cenyr/Grafschaft Celtigerns Wacht/Herrschaft Rhonwens Tränen/Herrschaft Rhonwens Tränen.html",
      "alt": "Herrschaftsbanner von Herrschaft Rhonwens Tränen",
      "format": "square"
    }
  },
  "court": {
    "groups": [],
    "cadets": []
  },
  "figures": {
    "heading": "11. Historische Figuren",
    "tableTitle": "Persönlichkeiten des Hauses",
    "entries": []
  },
  "familyTreeEmbed": {
    "src": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-madryn&mode=view",
    "title": "Stammbaum von Haus Madryn"
  },
  "trivia": [
    "Folgt …"
  ]
};
