// Generated by scripts/build-house-content.mjs. Edit haus.content.mjs instead.
window.HAEUSER_DATA = {
  "meta": {
    "id": "haus-draig",
    "title": "Haus Draig O'Gwynthor – Aleria",
    "type": "Grafenhaus",
    "status": "Active",
    "template": "haus",
    "storage": {
      "document": "haus-draig"
    }
  },
  "name": "Haus Draig O'Gwynthor",
  "hierarchy": [
    {
      "type": "Sammlung",
      "name": "Familien Häuser und Clans",
      "slug": "familien-haeuser-und-clans"
    },
    {
      "type": "Kontinent",
      "name": "Estryll",
      "slug": "estryll"
    },
    {
      "type": "Königreich",
      "name": "Cenyr",
      "slug": "cenyr"
    },
    {
      "type": "Grafschaft",
      "name": "Celtigerns Wacht",
      "slug": "celtigerns-wacht"
    },
    {
      "type": "Sitz",
      "name": "Gwynthor",
      "slug": "gwynthor"
    },
    {
      "type": "Haus",
      "name": "Haus Draig",
      "slug": "haus-draig"
    }
  ],
  "layout": "responsive",
  "classification": {
    "category": "Familien Häuser und Clans",
    "houseType": "Grafenhaus",
    "scale": "Grafschaft",
    "parentHouseId": "",
    "rootHouseId": "haus-draig",
    "territoryId": "celtigerns-wacht"
  },
  "profile": {
    "highestTitle": "Graf",
    "houseType": "Grafschaft",
    "motto": "Nicht überliefert",
    "quoteAuthor": "",
    "seat": "Gwynthor",
    "affiliation": "Königreich Cenyr · König Tristan Pendrag",
    "troopStrength": "Sehr stark",
    "tiarna": "Vor allem Uchelwyr und Teulu; außerdem Cantref",
    "kerns": "Zahlreiche Infanteristen und Seekrieger",
    "fleet": "30–50 Kriegsschiffe",
    "founding": "Nach dem Untergang Avallorns; Jahr unbekannt",
    "milestoneOne": "Celtigern gründet Haus Draig und lässt sich an der Südküste Cenyrs nieder.",
    "milestoneTwo": "Galahad übernimmt 1720 die Führung des Hauses.",
    "people": "Cenyri",
    "wealth": "Sehr hoch",
    "religion": "Alerische Kirche",
    "patronDeities": "Die Dame der See",
    "origin": "Avallorn · Dynastie Dreigiau",
    "cadetBranches": "Saethwyr, Wyrm und Gwyvern",
    "allies": "Haus Pendrag",
    "enemies": "Keine gegenwärtige Hausfehde benannt"
  },
  "profileLabels": {
    "tiarna": "Ritter",
    "kerns": "Knechte"
  },
  "showMotto": false,
  "sections": {
    "overview": "Haus Draig zählt zu den einflussreichsten Adelsfamilien Cenyrs. Als Bruderhaus der königlichen Pendrag entstammt es derselben avallornischen Dynastie. Die Draigs gelten als Verfechter der Ritterlichkeit und als Schild und Schwert Cenyrs.\n\nVon Gwynthor aus regiert das Grafenhaus die Grafschaft Celtigerns Wacht. Seine Macht beruht auf reichen Bergwerken, regem Seehandel und einem starken Ritteraufgebot. Die Verbundenheit mit dem Königshaus prägt seinen politischen Rang ebenso wie das Erbe der Alben.",
    "history": "Die Wurzeln der Draigs liegen in Avallorn. Nach dessen Untergang erreichte Celtigern, ein Prinz des letzten Königs und Angehöriger der Dynastie Dreigiau, gemeinsam mit seinen Geschwistern, ihrer Garde und Tausenden Überlebenden Estryll. Dort unterstützten die Ankömmlinge die Alben im Kampf gegen die Nordmänner.\n\nDie Dreigiau gründeten Mathragon. Aus ihrer Familie gingen zwei Häuser hervor: Vortigern begründete Haus Pendrag und wurde König von Cenyr; sein Bruder Celtigern gründete Haus Draig und ließ sich an der südlichen Küste nieder. Gwynthor entwickelte sich zum Stammsitz seines Hauses.\n\nCeltigerns Ehe mit einer Albin verband die avallornischen Flüchtlinge mit den Alben Cenyrs. Diese Verbindung prägt bis heute die Geschichte und Kultur der Draigs. Durch ihre Abstammung gehören sie zur königlichen Blutlinie, auch wenn die Krone Cenyrs dem Bruderhaus Pendrag zufiel.\n\nDie Grafschaft der Draigs gehört nicht zu den größten des Reiches. Mit Gwynthor besitzt sie jedoch eine bedeutende Handelsstadt, deren Bergbau, Häfen und kultureller Austausch großen Wohlstand schaffen. Cantref, Teulu und berittene Uchelwyr bilden den Kern der ritterlichen Streitmacht; Seekrieger und Flotte sichern den Einfluss des Hauses auf dem Meer.",
    "traditions": "Die ritterlichen Tugenden werden von Generation zu Generation weitergegeben. Die Draigs wollen anderen Häusern und Rittern ein Vorbild sein. Dass nicht jedes Familienmitglied diesem Anspruch gerecht wird, ändert wenig an der Bedeutung des Ideals.\n\nSeit dem Zauberer Myrddin hat auch die Magie ihren festen Platz im Haus. Einzelne Angehörige werden in den magischen Künsten unterwiesen. Der Hofzauberer nimmt allerdings nur alle 100 bis 200 Jahre einen neuen Lehrling auf; die Ausbildung soll mit den ritterlichen Tugenden im Einklang stehen.\n\nVon den Angehörigen des Hauses wird erwartet, den Weg des Ritters zu wählen, zu heiraten und der Familie zu dienen. Sie sollen Cenyr und seine Lande schützen. Wer seine Pflichten zurücklässt, um auf eigene Faust Abenteuer zu suchen oder „sich selbst zu finden“, begegnet im Haus meist Skepsis.",
    "knighthood": "Die Schwertleite findet traditionell an einem See, am Trident oder an der Küste statt. Manche Knappen reisen dafür nach Llanforwyn. Der Ritterschlag verbindet den Dienst am Haus mit dem Glauben und der Verpflichtung, die Schutzbedürftigen zu verteidigen.\n\nCantref führen vor allem die Lanze, Teulu das Schwert; die Uchelwyr stehen für den berittenen Kampf. Gemeinsam verleihen sie dem Haus seine besondere militärische Schlagkraft.\n\nDie charakteristische Drachenschuppen-Rüstung ahmt den Schuppenpanzer eines Drachen nach. Dazu gehört ein roter Helm in Form eines Drachenkopfes: Sein Oberkiefer bildet das hochklappbare Visier. Ein Kamm aus gefärbtem Rosshaar oder Federn sowie die Hausfarben machen die Ritter der Draigs weithin erkennbar.\n\nAuch die Milwr, die Miliz und Waffenknechte des Hauses, tragen seine Zeichen auf ihren Wappenröcken. Die Stadtwache führt dagegen das Wappen Gwynthors. So bleiben das Gefolge der Draigs und die städtischen Wächter voneinander zu unterscheiden.",
    "succession": "Galahad Draig führt das Haus seit 1720. Die überlieferte Erbfolge nennt Anaraut, Idwal, Tudwal, Neithon und Gawain in dieser Reihenfolge. Weitergehende Regeln für Sonderfälle der Nachfolge sind nicht überliefert.\n\nDie Oberhauptfolge am Hof führt die namentlich bekannten Grafen auf. Ihre Jahresangaben bezeichnen die überlieferten Amtszeiten; Lücken in der älteren Überlieferung bleiben offen.",
    "holdings": "Gwynthor und die zugehörige Baronie bilden das Herz des Besitzes der Draigs. Von ihrem Stammsitz aus üben sie ihre gräfliche Herrschaft über Celtigerns Wacht aus.\n\nMehrere sorgfältig verwaltete Bergwerke und Minen sichern einen wesentlichen Teil des Reichtums. Befestigte Häfen schützen die Küstenlinie, dienen der Flotte als Stützpunkte und ermöglichen den Seehandel.\n\nDie Abgaben von Vasallen und Bürgern finanzieren das Heer und die Infrastruktur. Im Gegenzug schuldet das Haus Schutz und die Sicherung seiner Lande.\n\nNeben dem traditionellen Handel mit dem Markt der Fortuna bestehen Beziehungen zur Klingenden Münze. Über diese Verbindungen beziehen die Draigs exotische Waren und exportieren eigene Erzeugnisse. Hinzu kommen Handelskontakte mit anderen Städten, darunter Nas.\n\nBergbau, Abgaben und Handel ermöglichen ein großes, gut ausgerüstetes Heer und eine Flotte von 30 bis 50 Kriegsschiffen. Wirtschaftlicher Wohlstand und militärische Stärke stützen einander.",
    "cultureReligion": "Die Draigs bekennen sich zur Alerischen Kirche, zu den Neun Göttlichen und zur Dame der See. Ihre Rittereide gelten als ernsthafte religiöse Verpflichtung. Eine eigene Ausbildung von Klerikern oder Paladinen unterhält das Haus nicht.\n\nKulturelle Feste, die Pflege der eigenen Sprache und die Bewahrung albischer Überlieferungen gehören zum Hausleben. Die Draigs sind stolz auf ihre Herkunft und verteidigen ihre kulturelle Identität. Zugleich zeigen sie sich anderen Kulturen und Religionen gegenüber offen.",
    "conflictsAlliances": "Die engste Verbindung besteht zum Bruderhaus Pendrag. Darüber hinaus pflegen die Draigs Bündnisse mit bedeutenden Adelshäusern Cenyrs. Ehen mit Alben bleiben geschätzt, kommen jedoch seltener vor als Verbindungen innerhalb des eigenen Volkes.\n\nVon See drohen Überfälle der Schwarzblut-Marodeure, die gelegentlich in den Süden Cenyrs vordringen. Die Sicherung der Küsten ist deshalb ein dauerhafter Auftrag des Hauses.\n\nFrühere Konflikte entstanden durch aufständische Vasallen, darunter das vermeintliche Königshaus von Caisil und die Illysywen. Gegenwärtig stehen diese Auseinandersetzungen nicht im Vordergrund; eine aktive Hausfehde ist nicht benannt.",
    "values": "Tugend, Ehre und Loyalität bilden den Kern des Selbstverständnisses der Draigs. Das Haus beansprucht, besonders fromme und pflichtbewusste Ritter hervorzubringen. Dieser Anspruch ist ein Maßstab für seine Angehörigen, keine Garantie für ihr Handeln.\n\nFamilie, kulturelle Zugehörigkeit und Verantwortung für Cenyr stehen im Mittelpunkt. Ritterdienst und Heirat sollen den Zusammenhalt und die Stellung des Hauses festigen. Persönliche Abenteuerlust wird daran gemessen, ob sie sich mit diesen Verpflichtungen vereinbaren lässt.",
    "court": "Der Hof vereint die gräfliche Hausführung, die Erbfolge und die Ämter zur Verwaltung von Haushalt, Besitz und Gefolge. Galahad ist das gegenwärtige Oberhaupt.",
    "familyTree": "Der Stammbaum zeigt die Familie von Celtigern bis zu den jüngeren Generationen sowie ihre Heiratsverbindungen. Die Portraits am Hof führen zu den jeweiligen Personen. Über das Hauswappen im Stammbaum öffnet sich die Hausbiografie.",
    "historicalFigures": "Celtigern und sein Bruder Vortigern stehen am Anfang der eng verbundenen Häuser Draig und Pendrag. Ihr gemeinsames Erbe erklärt die besondere Nähe der Draigs zur Krone Cenyrs."
  },
  "sectionTitles": {
    "knighthood": "4. Rittertum"
  },
  "images": {
    "haus-wappen": {
      "src": "../Stammbäume/assets/images/houses/Llamreis Ankunft/haus-draig.png",
      "alt": "Wappen von Haus Draig O'Gwynthor",
      "format": "square"
    },
    "haus-hauptbild": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Haus_Draig/assets/draig-ritter.png",
      "alt": "Ritter von Haus Draig O'Gwynthor",
      "format": "portrait",
      "maxHeight": 580
    },
    "haus-banner": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Haus_Draig/assets/gwynthor.png",
      "href": "../Kontinente/Estryll/Königreich Cenyr/Grafschaft Celtigerns Wacht/Grafschaft Celtigerns Wacht.html",
      "alt": "Herrschaftsbanner von Celtigerns Wacht",
      "format": "square"
    },
    "hof-founder-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/celtigern-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=celtigern-draig",
      "alt": "Celtigern Draig",
      "format": "portrait"
    },
    "hof-heads-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/celtigern-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=celtigern-draig",
      "alt": "Celtigern Draig",
      "format": "portrait"
    },
    "hof-heads-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/artus-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=artus-draig",
      "alt": "Artus Draig",
      "format": "portrait"
    },
    "hof-heads-3": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/godwyn-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=godwyn-draig",
      "alt": "Godwyn Draig",
      "format": "portrait"
    },
    "hof-heads-4": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/morholt-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=morholt-draig",
      "alt": "Morholt Draig",
      "format": "portrait"
    },
    "hof-heads-5": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/marared-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=marared-draig",
      "alt": "Marared Draig",
      "format": "portrait"
    },
    "hof-heads-6": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/gruffyd-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=gruffyd-draig",
      "alt": "Gruffyd Draig",
      "format": "portrait"
    },
    "hof-heads-7": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/neithon-1136-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=neithon-1136-draig",
      "alt": "Neithon Draig",
      "format": "portrait"
    },
    "hof-heads-8": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/iorwerth-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=iorwerth-draig",
      "alt": "Iorwerth Draig",
      "format": "portrait"
    },
    "hof-heads-9": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/kenehyr-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=kenehyr-draig",
      "alt": "Kenehyr Draig",
      "format": "portrait"
    },
    "hof-heads-10": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/cynan-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=cynan-draig",
      "alt": "Cynan Draig",
      "format": "portrait"
    },
    "hof-heads-11": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/cunedda-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=cunedda-draig",
      "alt": "Cunedda Draig",
      "format": "portrait"
    },
    "hof-heads-12": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/cadwalladar-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=cadwalladar-draig",
      "alt": "Cadwalladar Draig",
      "format": "portrait"
    },
    "hof-heads-13": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/howell-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=howell-draig",
      "alt": "Howell Draig",
      "format": "portrait"
    },
    "hof-heads-14": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/merfyn-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=merfyn-draig",
      "alt": "Merfyn Draig",
      "format": "portrait"
    },
    "hof-heads-15": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/cahir-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=cahir-draig",
      "alt": "Cahir Draig",
      "format": "portrait"
    },
    "hof-heads-16": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/rhodri-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=rhodri-draig",
      "alt": "Rhodri Draig",
      "format": "portrait"
    },
    "hof-heads-17": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/galahad-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=galahad-draig",
      "alt": "Galahad Draig",
      "format": "portrait"
    },
    "hof-heirs-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/anaraut-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=anaraut-draig",
      "alt": "Anaraut Draig",
      "format": "portrait"
    },
    "hof-heirs-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/idwal-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=idwal-draig",
      "alt": "Idwal Draig",
      "format": "portrait"
    },
    "hof-heirs-3": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/tudwal-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=tudwal-draig",
      "alt": "Tudwal Draig",
      "format": "portrait"
    },
    "hof-heirs-4": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/neithon-1718-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=neithon-1718-draig",
      "alt": "Neithon Draig",
      "format": "portrait"
    },
    "hof-heirs-5": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/gawain-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=gawain-draig",
      "alt": "Gawain Draig",
      "format": "portrait"
    },
    "hof-offices-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-balchder/dalvin-balchder.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-balchder&mode=view&person=dalvin-balchder",
      "alt": "Dalvin Balchder",
      "format": "portrait"
    },
    "hof-offices-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/odyar-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=odyar-draig",
      "alt": "Odyar Draig",
      "format": "portrait"
    },
    "hof-offices-3": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/steffan-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=steffan-draig",
      "alt": "Steffan Draig",
      "format": "portrait"
    },
    "hof-offices-4": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Zeremonienmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-5": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/gawain-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=gawain-draig",
      "alt": "Gawain Draig",
      "format": "portrait"
    },
    "hof-offices-6": {
      "src": "../Stammbäume/assets/images/portraits/haus-gafyr/duncan-gafyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-gafyr&mode=view&person=duncan-gafyr",
      "alt": "Duncan Gafyr",
      "format": "portrait"
    },
    "hof-offices-7": {
      "src": "../Stammbäume/assets/images/portraits/haus-wyrm/mailgwin-wyrm.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=mailgwin-wyrm",
      "alt": "Mailgwin Wyrm",
      "format": "portrait"
    },
    "hof-offices-8": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Kerkermeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-9": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Jagdmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-10": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Hafenmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-11": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Küchenmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-12": {
      "src": "../Stammbäume/assets/images/placeholders/female.png",
      "href": "",
      "alt": "Silhouette · Brotmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-13": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Haus_Draig/assets/ruarc-balguen.png",
      "href": "",
      "alt": "Ruarc Balguen",
      "format": "portrait"
    },
    "hof-offices-14": {
      "src": "../Stammbäume/assets/images/placeholders/female.png",
      "href": "",
      "alt": "Silhouette · Gartenmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-15": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Hofkaplan nicht benannt",
      "format": "portrait"
    },
    "hof-offices-16": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Hofmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-17": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/heledd-gwyvern.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=heledd-gwyvern",
      "alt": "Heledd Draig",
      "format": "portrait"
    },
    "hof-offices-18": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/trahern-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=trahern-draig",
      "alt": "Trahaern Draig",
      "format": "portrait"
    },
    "hof-offices-19": {
      "src": "../Stammbäume/assets/images/placeholders/female.png",
      "href": "",
      "alt": "Silhouette · Hoffalkner nicht benannt",
      "format": "portrait"
    },
    "hof-offices-20": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Zwingermeister nicht benannt",
      "format": "portrait"
    },
    "kadetten-haus-saethwyr": {
      "src": "../Stammbäume/assets/images/houses/Llamreis Ankunft/haus-saethwyr.png",
      "alt": "Wappen von Haus Saethwyr",
      "format": "square",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view"
    },
    "kadetten-haus-wyrm": {
      "src": "../Stammbäume/assets/images/houses/Llamreis Ankunft/haus-wyrm.png",
      "alt": "Wappen von Haus Wyrm",
      "format": "square",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view"
    },
    "kadetten-haus-gwyvern": {
      "src": "../Stammbäume/assets/images/houses/Gwendolyns Ufer/haus-gwyvern.png",
      "alt": "Wappen von Haus Gwyvern",
      "format": "square",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-gwyvern&mode=view"
    },
    "haus-figur-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/celtigern-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=celtigern-draig",
      "alt": "Celtigern Draig",
      "format": "portrait"
    },
    "haus-figur-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-draig/vortigern-pendrag.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=vortigern-pendrag",
      "alt": "Vortigern Pendrag",
      "format": "portrait"
    }
  },
  "court": {
    "groups": [
      {
        "id": "founder",
        "title": "Gründer",
        "entries": [
          {
            "name": "Celtigern Draig",
            "role": "",
            "detail": "Amtszeit unbekannt",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=celtigern-draig",
            "imageKey": "hof-founder-1"
          }
        ]
      },
      {
        "id": "heads",
        "title": "Oberhauptfolge · Haus Draig O'Gwynthor",
        "note": "Überlieferte Amtszeiten; unbekannte Zeiträume bleiben offen.",
        "entries": [
          {
            "name": "Celtigern Draig",
            "role": "",
            "detail": "Amtszeit unbekannt",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=celtigern-draig",
            "imageKey": "hof-heads-1"
          },
          {
            "name": "Artus Draig",
            "role": "",
            "detail": "Amtszeit unbekannt",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=artus-draig",
            "imageKey": "hof-heads-2"
          },
          {
            "name": "Godwyn Draig",
            "role": "",
            "detail": "Amtszeit unbekannt",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=godwyn-draig",
            "imageKey": "hof-heads-3"
          },
          {
            "name": "Morholt Draig",
            "role": "",
            "detail": "Amtszeit unbekannt",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=morholt-draig",
            "imageKey": "hof-heads-4"
          },
          {
            "name": "Marared Draig",
            "role": "",
            "detail": "Beginn unbekannt – 1169",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=marared-draig",
            "imageKey": "hof-heads-5"
          },
          {
            "name": "Gruffyd Draig",
            "role": "",
            "detail": "1169–1172",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=gruffyd-draig",
            "imageKey": "hof-heads-6"
          },
          {
            "name": "Neithon Draig",
            "role": "",
            "detail": "1172–1184",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=neithon-1136-draig",
            "imageKey": "hof-heads-7"
          },
          {
            "name": "Iorwerth Draig",
            "role": "",
            "detail": "1184–1271",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=iorwerth-draig",
            "imageKey": "hof-heads-8"
          },
          {
            "name": "Kenehyr Draig",
            "role": "",
            "detail": "Beginn unbekannt – 1295",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=kenehyr-draig",
            "imageKey": "hof-heads-9"
          },
          {
            "name": "Cynan Draig",
            "role": "",
            "detail": "Amtszeit unbekannt",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=cynan-draig",
            "imageKey": "hof-heads-10"
          },
          {
            "name": "Cunedda Draig",
            "role": "",
            "detail": "Beginn unbekannt – 1617",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=cunedda-draig",
            "imageKey": "hof-heads-11"
          },
          {
            "name": "Cadwalladar Draig",
            "role": "",
            "detail": "1617–1654",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=cadwalladar-draig",
            "imageKey": "hof-heads-12"
          },
          {
            "name": "Howell Draig",
            "role": "",
            "detail": "1654–1669",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=howell-draig",
            "imageKey": "hof-heads-13"
          },
          {
            "name": "Merfyn Draig",
            "role": "",
            "detail": "1669–1685",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=merfyn-draig",
            "imageKey": "hof-heads-14"
          },
          {
            "name": "Cahir Draig",
            "role": "",
            "detail": "1685–1702",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=cahir-draig",
            "imageKey": "hof-heads-15"
          },
          {
            "name": "Rhodri Draig",
            "role": "",
            "detail": "1702–1720",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=rhodri-draig",
            "imageKey": "hof-heads-16"
          },
          {
            "name": "Galahad Draig",
            "role": "",
            "detail": "Seit 1720 · gegenwärtiger Graf",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=galahad-draig",
            "imageKey": "hof-heads-17"
          }
        ]
      },
      {
        "id": "heirs",
        "title": "Erbfolge",
        "entries": [
          {
            "name": "Anaraut Draig",
            "role": "",
            "detail": "1. in der Erbfolge",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=anaraut-draig",
            "imageKey": "hof-heirs-1"
          },
          {
            "name": "Idwal Draig",
            "role": "",
            "detail": "2. in der Erbfolge",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=idwal-draig",
            "imageKey": "hof-heirs-2"
          },
          {
            "name": "Tudwal Draig",
            "role": "",
            "detail": "3. in der Erbfolge",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=tudwal-draig",
            "imageKey": "hof-heirs-3"
          },
          {
            "name": "Neithon Draig",
            "role": "",
            "detail": "4. in der Erbfolge",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=neithon-1718-draig",
            "imageKey": "hof-heirs-4"
          },
          {
            "name": "Gawain Draig",
            "role": "",
            "detail": "5. in der Erbfolge",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=gawain-draig",
            "imageKey": "hof-heirs-5"
          }
        ]
      },
      {
        "id": "offices",
        "title": "Hofämter",
        "entries": [
          {
            "name": "Dalvin Balchder",
            "role": "Vogt",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-balchder&mode=view&person=dalvin-balchder",
            "imageKey": "hof-offices-1"
          },
          {
            "name": "Odyar Draig",
            "role": "Schatzmeister",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=odyar-draig",
            "imageKey": "hof-offices-2"
          },
          {
            "name": "Steffan Draig",
            "role": "Kommandant der Garde",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=steffan-draig",
            "imageKey": "hof-offices-3"
          },
          {
            "name": "Nicht benannt",
            "role": "Zeremonienmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-4"
          },
          {
            "name": "Gawain Draig",
            "role": "Mundschenk",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=gawain-draig",
            "imageKey": "hof-offices-5"
          },
          {
            "name": "Duncan Gafyr",
            "role": "Waffenmeister",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-gafyr&mode=view&person=duncan-gafyr",
            "imageKey": "hof-offices-6"
          },
          {
            "name": "Mailgwin Wyrm",
            "role": "Stallmeister",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=mailgwin-wyrm",
            "imageKey": "hof-offices-7"
          },
          {
            "name": "Nicht benannt",
            "role": "Kerkermeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-8"
          },
          {
            "name": "Nicht benannt",
            "role": "Jagdmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-9"
          },
          {
            "name": "Nicht benannt",
            "role": "Hafenmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-10"
          },
          {
            "name": "Nicht benannt",
            "role": "Küchenmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-11"
          },
          {
            "name": "Nicht benannt",
            "role": "Brotmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-12"
          },
          {
            "name": "Ruarc Balguen",
            "role": "Handwerksmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-13"
          },
          {
            "name": "Nicht benannt",
            "role": "Gartenmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-14"
          },
          {
            "name": "Nicht benannt",
            "role": "Hofkaplan",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-15"
          },
          {
            "name": "Nicht benannt",
            "role": "Hofmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-16"
          },
          {
            "name": "Heledd Draig",
            "role": "Hofdame",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=heledd-gwyvern",
            "imageKey": "hof-offices-17"
          },
          {
            "name": "Trahaern Draig",
            "role": "Archivar",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view&person=trahern-draig",
            "imageKey": "hof-offices-18"
          },
          {
            "name": "Nicht benannt",
            "role": "Hoffalkner",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-19"
          },
          {
            "name": "Nicht benannt",
            "role": "Zwingermeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-20"
          }
        ]
      }
    ],
    "cadets": [
      {
        "name": "Haus Saethwyr",
        "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view",
        "imageKey": "kadetten-haus-saethwyr"
      },
      {
        "name": "Haus Wyrm",
        "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view",
        "imageKey": "kadetten-haus-wyrm"
      },
      {
        "name": "Haus Gwyvern",
        "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-gwyvern&mode=view",
        "imageKey": "kadetten-haus-gwyvern"
      }
    ]
  },
  "figures": {
    "heading": "12. Historische Figuren",
    "tableTitle": "Begründer der Bruderhäuser",
    "entries": [
      {
        "group": "Begründer der Bruderhäuser",
        "role": "Gründer des Hauses",
        "name": "Celtigern Draig",
        "description": "Prinz der Dynastie Dreigiau und Bruder Vortigerns. Nach der Flucht aus Avallorn gründete er Haus Draig an der Südküste Cenyrs. Seine Ehe mit einer Albin verband das Haus mit der einheimischen Kultur.",
        "imageKey": "haus-figur-1"
      },
      {
        "group": "Begründer der Bruderhäuser",
        "role": "Bruder des Gründers · König von Cenyr",
        "name": "Vortigern Pendrag",
        "description": "Vortigern begründete Haus Pendrag und wurde König von Cenyr. Die gemeinsame Herkunft mit Celtigern bildet die Grundlage des bis heute engen Verhältnisses zwischen den beiden Bruderhäusern.",
        "imageKey": "haus-figur-2"
      }
    ]
  },
  "familyTreeEmbed": {
    "src": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-draig&mode=view",
    "title": "Stammbaum von Haus Draig O'Gwynthor"
  },
  "trivia": [
    "Der Hofzauberer nimmt nur alle 100 bis 200 Jahre einen neuen Lehrling an.",
    "Das hochklappbare Visier der Drachenhelme bildet den Oberkiefer eines Drachen nach.",
    "Hausgefolge und Stadtwache unterscheiden sich durch die Wappen auf ihren Wappenröcken."
  ]
};
