[build]
  publish = "."

[[redirects]]
  from = "/firebase/*"
  to = "/not_found.html"
  status = 404
  force = true

[[redirects]]
  from = "/firebase.json"
  to = "/not_found.html"
  status = 404
  force = true

[[redirects]]
  from = "/Stammb%C3%A4ume/tests/*"
  to = "/not_found.html"
  status = 404
  force = true

[[redirects]]
  from = "/AleriaAlmanach/scripts/*"
  to = "/not_found.html"
  status = 404
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
