// Generated from Religionen/kulte/nimuiten/eintrag.json; edit the canonical religion entry.
function createNimuitenReligionEntry() {
  return {
  "id": "nimuiten",
  "title": "Die Nimuiten",
  "subtitle": "Die Gemeinschaft der Heimkehr nach Avallorn",
  "type": "Verbotene Sekte",
  "category": "Religion · Häresien, Kulte & Sekten",
  "image": "../Religionen/kulte/nimuiten/assets/nimuiten-kuestenwache-v1.png",
  "stamp": "DIE GEMEINSCHAFT DER HEIMKEHR NACH AVALLORN",
  "multipage": true,
  "appendCommentsPage": false,
  "locked": false,
  "icon": "✧",
  "symbol": "../Religionen/kulte/nimuiten/assets/nimuiten-symbol-v2.png",
  "pages": [
    {
      "pageTitle": "I. — Die verlorene Heimat",
      "image": "../Religionen/kulte/nimuiten/assets/nimuiten-kuestenwache-v1.png",
      "imageFit": "contain",
      "imagePosition": "center",
      "imageWidth": 40,
      "description": "<strong>Die verlorene Heimat</strong><br><br>Die Nimuiten sind eine in Cenyr verbotene Glaubensgemeinschaft, deren Hoffnung nicht auf einer Verbesserung des gegenwärtigen Königreiches, sondern auf der Heimkehr nach Avallorn ruht. Sie verehren die Göttlichen der Alerischen Kirche, richten ihre Gebete und Erwartungen jedoch vor allem an Nimue. Wie der Glaube an die Dame des Sees einst den Weg aus dem untergehenden Avallorn wies, so soll sie ihre Getreuen eines Tages zurückführen.<br><br>Für die Gemeinschaft ist Avallorn mehr als ein verlorener Ort. Es ist eine Heimat, die ihre Vorfahren durch Hochmut und Dekadenz verwirkten und die nur ein geläutertes Volk wieder bewohnen dürfe. Die Nimuiten betrachten ihr gegenwärtiges Leben deshalb als eine Zeit des Wartens, der Bewährung und der Vorbereitung auf eine noch ausstehende Rückkehr.<br><br>Unter den Armen findet diese Verheißung Gehör, weil sie nicht nur Erlösung nach dem Tod verspricht. Sie verheißt auch eine andere Zukunft für die Lebenden: ein erneuertes Königreich jenseits jener Herrschaften, deren Versagen die Gemeinschaft beklagt. Zugleich verbindet sich diese Hoffnung mit einer Opferpraxis und einer Verehrung gefährlicher Meeresgeschöpfe, die den Glauben von Nimues tatsächlichem Wesen entfernen.<br><br><strong>Avallorn, Oseneach und die Herkunft der Cenyri</strong><br><br>Die Vorfahren der Cenyri stammten aus Avallorn. Dessen Untergang folgte einer Zeit der Dekadenz und des Hochmuts. In dieser Epoche führte der Glaube an Nimue Avallornier aus ihrer alten Heimat fort. Ihre Wanderung steht mit Estryll und Oseneach, dem antiken Cenyr, in Verbindung. Aus ihrer Verschmelzung mit dem Volk der Crannath-Alben gingen die Cenyri hervor.<br><br>Die Nimuiten deuten diese Herkunft als eine unvollendete Geschichte. Die Rettung aus Avallorn war nach ihrer Auffassung kein endgültiger Abschied, sondern der Beginn einer langen Zeit fern der verlorenen Heimat. Nimue habe die Vorfahren bewahrt, damit ihre Nachkommen eines Tages als erneuertes Volk zurückkehren könnten.<br><br>Die Sekte will nicht die Ausschweifungen des alten Avallorn wiederherstellen. Sie unterscheidet zwischen dem verlorenen Königreich und der Lebensweise, durch die es zugrunde ging. Das künftige Avallorn soll gerade nicht wiederholen, was das alte zerstörte. Diese Unterscheidung erlaubt es den Nimuiten, den Untergang als gerechtes Warnzeichen zu betrachten und dennoch die Heimkehr zu ersehnen.<br><br>Diese Herkunft schließt das Erbe der Crannath-Alben ein. Die Heimkehrlehre begründet weder Blutreinheit noch eine Ablehnung dieses albischen Erbes.<br><br><a href=\"../Religionen/kulte/nimuiten/index.html\">Zum Religionsarchiv: Die Nimuiten</a>",
      "stats": [
        [
          "Eigenname",
          "Gemeinschaft der Heimkehr"
        ],
        [
          "Herkunft",
          "Cenyr · entstanden während einer Hungersnot"
        ],
        [
          "Glaubensumfeld",
          "Abspaltung aus dem Umfeld der Alerischen Kirche"
        ],
        [
          "Hauptverehrung",
          "Nimue · die übrigen Göttlichen bleiben wichtig"
        ]
      ]
    },
    {
      "pageTitle": "II. — Der Prophet der Heimkehr",
      "image": "../Religionen/kulte/nimuiten/assets/nimuiten-prys-predigt-v1.png",
      "imageFit": "contain",
      "imagePosition": "center",
      "imageWidth": 40,
      "description": "<strong>Entstehung in der Hungersnot</strong><br><br>Die Gemeinschaft entstand während einer Hungersnot aus tiefer Unzufriedenheit mit Adel und Klerus. Menschen, die von ihren weltlichen Beschützern und geistlichen Hirten Hilfe erwartet hatten, erlebten stattdessen Mangel und Enttäuschung. In dieser Lage trat ein freier Prediger und Zauberer aus Mathragon hervor: Iorwerth Prys.<br><br>Prys verband die gegenwärtige Not mit der alten Erzählung von Avallorns Untergang. Er predigte, Cenyr sei nicht gegen jene Versuchungen gefeit, an denen die Vorfahren gescheitert waren. Besitz, Ansehen und ritterliche Herkunft schützten niemanden vor Hochmut. Eine Herrschaft, die ihre Schutzbefohlenen im Elend zurückließ, konnte nach seiner Auslegung keinen sicheren Weg in die Zukunft weisen.<br><br>Seine Botschaft bot den Enttäuschten eine religiöse Deutung ihres Leidens. Sie seien nicht vergessen, sondern Teil einer Gemeinschaft, die sich auf Nimues kommende Führung vorbereiten müsse. Aus dem Kreis um den Prediger entwickelte sich eine eigenständige Bewegung mit eigenen Auslegungen, Opferbräuchen und Erwartungen.<br><br>Die Gründung gehört in die spätere Hungersnot in Cenyr, nicht in die Zeit von Avallorns Untergang. Ein genaues Gründungsjahr ist nicht überliefert; das hohe Alter des Propheten allein bestimmt nicht das Alter der Gemeinschaft.<br><br><strong>Iorwerth Prys, Prophet der Heimkehr</strong><br><br>Iorwerth Prys ist der lebende Gründer und Anführer der Nimuiten. Der aus Mathragon stammende Zauberer ist über vierhundert Jahre alt und wird von seinen Anhängern als Prophet Nimues geehrt. Seine fortdauernde Gegenwart verbindet die Gemeinschaft mit ihrem Ursprung: Während Generationen von Gläubigen kommen und gehen, bleibt der Mann, dessen Verkündigung die Bewegung begründete.<br><br>Für die Anhänger sind sein Alter, seine magische Begabung und sein Auftreten Zeichen einer besonderen Sendung. Seine Worte besitzen mehr Gewicht als die Auslegung eines gewöhnlichen Predigers. Er deutet vermeintliche Offenbarungen, beurteilt Zeichen und beansprucht maßgeblichen Einfluss auf jene Entscheidungen, die als Nimues Wille gelten.<br><br>Prys ist nicht automatisch der angekündigte Gemahl. Der Prophet verkündet die kommende Erwählung; die Göttin soll den Auserwählten selbst bestimmen. Gerade diese Unterscheidung lässt seine Autorität bestehen, obwohl die große Verheißung noch nicht erfüllt ist.<br><br>Seine Anhänger halten ihn für von Nimue bewahrt. Die tatsächliche Ursache seiner Langlebigkeit ist jedoch unbekannt."
    },
    {
      "pageTitle": "III. — Nimues unerfüllte Verheißung",
      "image": "../Religionen/kulte/nimuiten/assets/nimuiten-versunkener-tempel-v1.png",
      "imageFit": "contain",
      "imagePosition": "center",
      "imageWidth": 40,
      "description": "<strong>Nimue und die Erwartung der Heimkehr</strong><br><br>Nimue steht im Mittelpunkt der Gebete, weil die Nimuiten in ihr die Führerin der Auswanderung und der künftigen Rückkehr sehen. Die übrigen Göttlichen werden dadurch nicht bedeutungslos. Sie gehören weiterhin zur vertrauten religiösen Welt der Gemeinschaft, während die entscheidende Verheißung mit der Dame des Sees verbunden wird.<br><br>Die Ordnung der Neun Göttlichen, der fünf Souveräne und der fünf Untergötter bleibt bestehen. Nimues besondere Verehrung begründet keine neue Rangordnung und macht sie nicht zu einer zehnten Celestialen.<br><br>Die Nimuiten behaupten nicht notwendig, Nimue stehe ihrem Wesen nach über den Neun. Ihr Vorrang liegt in der gelebten Frömmigkeit: An sie richten sich die Hoffnung auf Avallorn, die Deutung der Meereszeichen und die Erwartung einer persönlichen Erscheinung.<br><br>Nach ihrer Lehre wird Nimue eines Tages vor ihren Jüngern erscheinen und einen Auserwählten zum Gemahl nehmen. Diese Vermählung soll den Beginn der großen Heimkehr anzeigen. Unter der Führung des Erwählten werden die Gläubigen nach Avallorn segeln und dort das Königreich neu begründen.<br><br>Die angekündigte Überfahrt der Lebenden ist von den Meeresbestattungen zu unterscheiden. Die Sekte erwartet eine wirkliche gemeinsame Ausfahrt und eine Erneuerung des Königreiches, nicht lediglich ein anderes Wort für den Tod. Wie das untergegangene Avallorn erneut erreichbar und bewohnbar werden soll, gehört zur unerfüllten Verheißung und ist keine bereits gesicherte geografische Tatsache.<br><br>Die Erscheinung, die Erwählung und die Heimkehr stehen noch aus. Einen gesicherten Termin oder eine bekannte Überfahrt gibt es nicht. Die Bezeichnung „Auserwählter“ meint den erhofften Gemahl; sie bezeichnet nicht das jährliche Menschenopfer.<br><br><strong>Cenyr und das Versagen der Herrschaft</strong><br><br>Cenyr ist ein Königreich mit der Alerischen Kirche als Staatsreligion und gilt als Begründer und Vorbild des Rittertums. Gerade dieser Anspruch verleiht der Kritik der Nimuiten Gewicht. Sie stellen nicht irgendeiner Herrschaft ein fernes Ideal entgegen, sondern messen das Land an den Schutz- und Tugendversprechen, auf die es selbst stolz ist.<br><br>In den Augen der Gemeinschaft hat der Adel bereits versagt oder befindet sich auf einem Weg, der früher oder später erneut in Dekadenz münden wird. Die Erinnerung an die Hungersnot gilt ihr als Warnung: Auch ehrwürdige Geschlechter und ritterliche Gelübde verhindern nicht, dass Wohlstand und Rang die Sorge um die Schutzbefohlenen verdrängen.<br><br>Die Sekte muss dafür nicht jeden einzelnen Ritter für schlecht halten. Ein rechtschaffener Herr kann nach ihrer Auffassung bestehen und dennoch Teil einer Ordnung sein, die auf lange Sicht dieselben Fehler wiederholt. Ihre Hoffnung richtet sich deshalb nicht vorrangig auf einen besseren Grafen oder eine neue Regierung, sondern auf den Auszug unter Nimues Führung."
    },
    {
      "pageTitle": "IV. — Gemeinschaft und Opfer",
      "image": "../Religionen/kulte/nimuiten/assets/nimuiten-stille-opferstaette-v1.png",
      "imageFit": "contain",
      "imagePosition": "center",
      "imageWidth": 40,
      "description": "<strong>Gemeinschaft und religiöse Autorität</strong><br><br>Die Anhänger sind größtenteils arme Bauern, Außenseiter, Exzentriker oder Menschen, die bereits in nimuitischen Familien aufgewachsen sind. Für Letztere ist der Glaube nicht erst das Ergebnis einer bewussten Abkehr von der Staatskirche. Er ist die Religion ihrer Eltern, ihrer Trauerfeiern und ihrer Vorstellung von Herkunft und Zukunft.<br><br>Die Verheißung Avallorns verbindet persönliche Not mit einer gemeinsamen Geschichte. Wer wenig besitzt oder von bestehenden Institutionen enttäuscht ist, erhält einen Platz unter den künftigen Heimkehrenden. Zugehörigkeit beruht dabei nicht auf einer neu festgelegten Beschränkung auf bestimmte Abstammungslinien.<br><br>An der Spitze steht Iorwerth Prys. Unter ihm können örtliche Prediger und erfahrene Gemeindemitglieder die Lehre weitergeben, Versammlungen führen und Begräbnisse begleiten.<br><br>Nicht jeder Anhänger ist ein Zauberer, Opfernder oder mit sämtlichen Vorgängen vertraut. Die Gemeinschaft umfasst ehrliche Frömmigkeit, familiäre Bindung, Furcht, Zweifel und die Autorität eines jahrhundertealten Propheten. Armut und Außenseitertum sagen für sich genommen nichts über den Verstand eines Menschen aus.<br><br><strong>Opfer und die Gabe des Jahres</strong><br><br>Die Nimuiten bringen Nimue Opfer dar. Dazu gehören Tiere und Menschen. Die Menschenopfer werden innerhalb der Gemeinschaft als freiwillige Hingabe verstanden: Ein Mitglied stellt sein Leben in den Dienst jener Verheißung, die für alle gelten soll.<br><br>Jährlich wird eine Person für diese besondere Opfergabe bestimmt. Die Auswahl erfolgt unter denjenigen, die ihre Bereitschaft erklärt haben. Sie kann durch ein als heilig verstandenes Los geschehen oder durch eine Benennung des Propheten, die er als Offenbarung von Nimues Willen auslegt. In beiden Fällen gilt der Gemeinschaft nicht menschliche Willkür, sondern die Göttin als eigentliche Urheberin der Wahl.<br><br>Die Bezeichnung „Gabe des Jahres“ trennt diese Person sprachlich vom künftigen Gemahl Nimues. Die Opferung erfüllt nicht automatisch die Heimkehrprophezeiung. Sie gilt den Gläubigen vielmehr als Hingabe während der noch andauernden Erwartung.<br><br>Dass ein Opfer als freiwillig gilt, bedeutet nicht, dass alle Beteiligten frei von Erwartungen, Furcht oder religiösem Druck sind. Die erklärte Bereitschaft kann mit der Angst verbunden sein, die Gemeinschaft oder die Göttin zu enttäuschen. Die Auswahl ist deshalb weder mit einer heimlichen Entführung gleichzusetzen noch jede Losziehung als Betrug erwiesen. Prys besitzt jedoch erheblichen Einfluss darauf, welche Entscheidung als göttlicher Wille verstanden wird.<br><br>Die Gabe des Jahres ist ein jährliches Ritual. Daneben stehen Tieropfer und die Begleittode im Bestattungsbrauch; die Zahl eins begrenzt deshalb nicht sämtliche möglichen Todesfälle eines Jahres."
    },
    {
      "pageTitle": "V. — Das vermeintliche Meeresvolk",
      "image": "../Religionen/kulte/nimuiten/assets/nimuiten-meeresvolk-v1.png",
      "imageFit": "contain",
      "imagePosition": "center",
      "imageWidth": 40,
      "description": "<strong>Die Geschöpfe am Strand</strong><br><br>Die Nimuiten legen Opfergaben an Stränden nieder, wo sie auf Sirenen und Thraalkin treffen oder deren Nähe vermuten. Diese Wesen gelten ihnen als Geschöpfe Nimues. Ihre Erscheinung ist in der Auslegung der Sekte kein Beweis einer infernalen Nähe, sondern ein Zeichen dafür, dass die Dame des Sees ihre Gemeinschaft wahrnimmt.<br><br>Die Sirenen werden mit den Meerjungfrauen Nimues verwechselt. Die Thraalkin, amphibische Echsenwesen und wirkliche Kinder Thraals, erscheinen den Gläubigen ebenfalls als Angehörige von Nimues verborgenem Meeresvolk. Die Gemeinschaft deutet beide nach ihrem eigenen Glauben, statt deren wirkliche Herkunft zu erkennen.<br><br>Das Interesse dieser Wesen an den Gaben kann die Erwartung weiterer Begegnungen verstärken. Ihr Verhalten muss dabei nicht gutartig werden. Eine Sirene wird durch Verehrung nicht zu einer Meerjungfrau, und Thraalkin bleiben Thraals Geschöpfe. Gefährliche Begegnungen können innerhalb der Sekte als Prüfung oder als Reaktion auf vermeintliche Unreinheit ausgelegt werden.<br><br><strong>Die Toten und das Leben unter dem Meer</strong><br><br>Stirbt ein Nimuit, erhält er nach dem Brauch der Gemeinschaft ein Meeresbegräbnis. Die Angehörigen fahren mit dem Leichnam hinaus und begleiten die Übergabe an das Wasser mit Klageliedern. Der Körper wird beschwert und dem Meeresgrund überlassen.<br><br>Die Gläubigen verbinden mit dieser Bestattung eine besondere Hoffnung. Sie glauben, Nimue nehme würdige Verstorbene auf und mache sie zu Meerjungfern oder Meermännern. Jene Wesen, denen sie an den Küsten begegnen und die andere als Sirenen oder Thraalkin bezeichnen, gelten ihnen als Erscheinungsformen solcher Verwandelten.<br><br>Damit erscheinen die Meerwesen nicht nur als Diener der Göttin. In ihnen können die Nimuiten auch Angehörige ihrer eigenen Gemeinschaft vermuten, die ihnen in ein anderes Dasein vorausgegangen sind. Die Gaben am Strand erhalten dadurch eine Verbindung zur Erinnerung an die Toten.<br><br>Die Sekte fürchtet jedoch ein anderes Schicksal. Verdorbene Seelen würden nach ihrer Vorstellung nicht in Nimues Meeresvolk aufgenommen, sondern zu Versunkenen: rastlosen Wasserleichen, die als untote Überreste zurückkehren können. Diese Unterscheidung erlaubt es den Gläubigen, ihre Hoffnung auf Verwandlung mit der wirklichen Gefahr der Versunkenen zu vereinbaren.<br><br>Diese Lehre ist nicht die tatsächliche Entstehungsgeschichte von Sirenen, Thraalkin oder Versunkenen. Insbesondere wird aus dem Auftreten eines Versunkenen kein objektiver Beweis der moralischen Verdorbenheit seines früheren Lebens."
    },
    {
      "pageTitle": "VI. — Die Toten und die Trauernden",
      "image": "../Religionen/kulte/nimuiten/assets/nimuiten-trauer-am-meer-v1.png",
      "imageFit": "contain",
      "imagePosition": "center",
      "imageWidth": 40,
      "description": "<strong>Die Beschwerung und das Folgen der Trauernden</strong><br><br>Die Beschwerung des Leichnams hat innerhalb der Sektenlehre zwei miteinander vereinbare Bedeutungen. Sie übergibt den Toten dem Reich, in dem die erhoffte Verwandlung stattfinden soll, und soll zugleich verhindern, dass ein verworfener Leib als Versunkener zu den Lebenden zurückkehrt.<br><br>Die Nimuiten erklären den scheinbaren Widerspruch damit, dass die Beschwerung nur den sterblichen Leib festhalte. Wen Nimue tatsächlich verwandle, dem werde sie auch die Kraft oder die neue Gestalt verleihen, sich davon zu lösen. Ein bloß wiedererwachter, unreiner Körper besitze diese Befreiung nicht.<br><br>Dies ist die Erklärung der Gläubigen, kein verlässliches Prüfverfahren. Ein versenkter Körper, der nicht wiedergefunden wird, beweist keine Verwandlung. Ebenso garantiert eine Beschwerung keinen Schutz vor jedem Untoten.<br><br>Bei manchen Begräbnissen wird darüber hinaus erwartet oder ausdrücklich begrüßt, dass Freiwillige das Schicksal des Verstorbenen teilen und ihm in den Tod folgen. Die Gemeinschaft deutet diese zusätzliche Hingabe als Begleitung des Toten und als Vertrauen auf Nimues versprochene Aufnahme.<br><br>Der gewöhnliche Tote, der bestattet wird, und die Lebenden, die ihm folgen, haben dabei unterschiedliche Rollen. Das Folgen wird nicht bei jedem Begräbnis verlangt und ist nicht mit der Gabe des Jahres identisch. Wo die Gemeinschaft eine solche Begleitung erwartet, kann sich religiöse Hoffnung mit erheblichem Druck auf die Trauernden verbinden."
    },
    {
      "pageTitle": "VII. — Verbot und kirchlicher Bruch",
      "image": "../Religionen/kulte/nimuiten/assets/nimuiten-sanktoren-untersuchung-v1.png",
      "imageFit": "contain",
      "imagePosition": "center",
      "imageWidth": 40,
      "description": "<strong>Verbot, Überstellung und die Sanktoren</strong><br><br>Die Nimuiten sind in Cenyr verboten. Aufgegriffene Mitglieder werden der Alerischen Kirche überstellt, die ihre Zugehörigkeit, Lehre und Beteiligung an konkreten Handlungen untersucht und darüber richtet. Der Adel ist verpflichtet, die Häretiker der kirchlichen Gerichtsbarkeit zuzuführen.<br><br>Das Verbot richtet sich nicht gegen gewöhnliche Nimueverehrung. Die Dame des Sees gehört selbst zur anerkannten göttlichen Ordnung. Gegenstand des Konflikts sind die eigenmächtige Offenbarungsautorität, die Opferpraxis, die gefährliche Verwechslung der Meereswesen und die Lehren, die unter Nimues Namen verbreitet werden.<br><br>Von Zeit zu Zeit entsendet die Alerische Kirche Sanktoren aus der Blutstadt. Sie unterstützen die örtlichen Geistlichen, untersuchen schwerwiegende Fälle und helfen, vermeintliche Offenbarungen und mögliche infernale Einflüsse zu prüfen.<br><br>Die Überstellung bedeutet nicht automatisch die Hinrichtung jedes Mitglieds. Ein in der Gemeinschaft aufgewachsener Angehöriger, ein Prediger und jemand, der unmittelbar an Opferungen beteiligt ist, besitzen unterschiedliche Verantwortlichkeiten. Untersuchung und gerichtliche Entscheidung liegen bei der Kirche. Das Verbot ermächtigt den Adel nicht zu willkürlicher Selbstjustiz.<br><br><strong>Der Bruch mit der Alerischen Kirche</strong><br><br>Die Nimuiten lösen sich nicht deshalb von der Alerischen Kirche, weil sie plötzlich alle anderen Göttlichen leugnen. Ihr Bruch entsteht daraus, dass sie eine besondere Rückkehrerwartung und die Auslegung eines lebenden Propheten über die Prüfung durch die überlieferte Lehre stellen.<br><br>Nimues Hilfe bei der Flucht aus Avallorn wird zur behaupteten Zusage einer Heimkehr. Die Hoffnung auf ihre Gnade wird zur Erwartung einer bestimmten Verwandlung nach dem Tod. Verehrung wird mit Menschenopfern verbunden, und infernale Geschöpfe werden als Angehörige ihres Meeresvolkes angesprochen.<br><br>Für die Alerische Kirche widerspricht dieser Zusammenhang dem Wesen der Göttin, in deren Namen die Gemeinschaft handelt. Ein Prophet kann Nimues Güte nicht dadurch neu bestimmen, dass er eine grausame Forderung als höhere Offenbarung ausgibt. Die Frage ist deshalb nicht, ob Nimue verehrt werden darf, sondern ob die angebliche Stimme tatsächlich ihre Stimme ist.<br><br>Die Nimuiten halten dem entgegen, dass die etablierte Kirche ihre Enttäuschung nicht überwunden und die Verheißung der Heimkehr nicht verstanden habe. So kann eine Untersuchung als weiterer Beweis jener geistlichen Blindheit erscheinen, von der Prys seit der Hungersnot spricht.<br><br>Die Tragik der Gemeinschaft liegt darin, dass Menschen nach Rettung suchen und ihre gefährlichsten Irrtümer gerade durch wirkliche übernatürliche Erfahrungen bestätigt sehen. Nicht jede Hoffnung ist gelogen; nicht jede antwortende Macht ist die, deren Namen sie trägt."
    },
    {
      "pageTitle": "VIII. — Spielleitungswissen: Hinter dem Glauben",
      "image": "../Religionen/kulte/nimuiten/assets/nimuiten-thraals-tiefe-v1.png",
      "imageFit": "contain",
      "imagePosition": "center",
      "imageWidth": 40,
      "description": "<strong>Spielleitungswissen · Hinter dem Glauben</strong><br><br>Die Macht, die einen entscheidenden Teil der Opfer und Verehrung der Nimuiten entgegennimmt, ist Thraal. Die Gemeinschaft nennt Nimue, richtet aber Handlungen und Erwartungen auf eine vermeintliche Göttin, deren grausame Forderungen nicht zu Nimues tatsächlichem Wesen passen. Thraal benötigt keine korrekte Anrede, um diese Verirrung auszunutzen.<br><br>Er nimmt die Verehrung an, fördert die Bindung an seine Geschöpfe und verleiht tatsächliche Gaben. Solche Wirkungen bestätigen für die Betroffenen ausgerechnet den Glauben, von Nimue erhört worden zu sein. Dass eine Erscheinung wirksam ist, beantwortet für sie nicht die entscheidende Frage nach ihrem Ursprung.<br><br>Die Täuschung wird dadurch erleichtert, dass Nimue und Thraal beide mit Wasser verbunden sind und verwandte äußere Wirkungen hervorrufen können. Eine verbesserte Fähigkeit, unter Wasser zu atmen, ist für sich genommen kein eindeutiger Herkunftsnachweis. Hinzu kommt die eigene arkane Begabung von Iorwerth Prys, die ebenfalls nicht mit göttlicher Bestätigung gleichgesetzt werden darf.<br><br>Das bedeutet nicht, dass jedes Gebet eines Nimuiten ins Leere geht oder ausschließlich Thraal erreicht. Einzelne aufrichtige Anhänger handeln in echter Güte, beten ehrlich zu Nimue und werden tatsächlich von ihr berührt. Solche Erfahrungen können Trost oder Mahnung enthalten und dennoch durch die Lehre des Propheten fehlgedeutet werden. Echte Nähe zur Göttin bestätigt weder die Opferpraxis noch die ganze Gemeinschaft.<br><br>Nimue und Thraal arbeiten dabei nicht zusammen. Die Vermischung liegt in Wahrnehmung und Deutung der Gläubigen. Ein von Thraal gewährtes Zeichen macht ihn nicht zum Ursprung aller Güte; ein echter Trost Nimues rechtfertigt keine Menschenopfer in ihrem Namen.<br><br>Thraal ist weder Nimue noch ihre verborgene zweite Persönlichkeit. Er besetzt ihre Rolle im religiösen Erleben der Getäuschten, nicht ihren wirklichen Platz unter den Göttlichen. Wie viel Iorwerth Prys davon weiß, bleibt offen. Ebenso unbekannt sind der Ursprung jeder einzelnen Vision und das endgültige Schicksal jeder verstorbenen Seele."
    }
  ]
};
}
