// Generated by scripts/build-house-content.mjs. Edit haus.content.mjs instead.
window.HAEUSER_DATA = {
  "meta": {
    "id": "haus-tlawd",
    "title": "Haus Tlawd – Aleria",
    "type": "Ritterhaus",
    "status": "Active",
    "template": "kleinehaeuser",
    "storage": {
      "document": "haus-tlawd"
    }
  },
  "name": "Haus Tlawd",
  "hierarchy": [
    {
      "type": "Sammlung",
      "name": "Familien Häuser und Clans",
      "slug": "familien-hauser-und-clans"
    },
    {
      "type": "Kontinent",
      "name": "Estryll",
      "slug": "estryll"
    },
    {
      "type": "Königreich",
      "name": "Cenyr",
      "slug": "cenyr"
    },
    {
      "type": "Grafschaft",
      "name": "Celtigerns Wacht",
      "slug": "celtigerns-wacht"
    },
    {
      "type": "Region",
      "name": "Llamreis Ankunft",
      "slug": "llamreis-ankunft"
    },
    {
      "type": "Sitz",
      "name": "Gwynthor",
      "slug": "gwynthor"
    },
    {
      "type": "Haus",
      "name": "Haus Tlawd",
      "slug": "haus-tlawd"
    }
  ],
  "layout": "responsive",
  "classification": {
    "category": "Familien Häuser und Clans",
    "houseType": "Ritterhaus",
    "scale": "Ritterhaus",
    "parentHouseId": "",
    "rootHouseId": "haus-tlawd",
    "territoryId": "herrschaft-gafyr"
  },
  "profile": {
    "highestTitle": "Ritterherr",
    "rank": "Ritterherr",
    "houseType": "Ritterhaus",
    "motto": "",
    "quoteAuthor": "",
    "seat": "Gwynthor",
    "affiliation": "Haus Gafyr",
    "liege": "Haus Gafyr",
    "patron": "Ritterfürst Duncan Gafyr",
    "knightingPatron": "Maldwyn Gafyr",
    "troopStrength": "",
    "tiarna": "",
    "kerns": "",
    "fleet": "",
    "founding": "",
    "milestoneOne": "1273: Edric wird Page; 1277: Aufnahme als Knappe.",
    "milestoneTwo": "1285: Ritterschlag durch Maldwyn Gafyr.",
    "people": "Cenyrisch, mit albischen Wurzeln",
    "wealth": "Wohlhabend",
    "religion": "Alerische Kirche",
    "patronDeities": "Der Knecht; der Streiter",
    "origin": "Sir Edric Tlawd war Knappe von Maldwyn Gafyr und wurde von diesem in den niederen Adelsstand berufen.",
    "cadetBranches": "",
    "allies": "Die Gafyr",
    "enemies": ""
  },
  "profileLabels": {
    "tiarna": "Ritter",
    "kerns": "Knechte"
  },
  "showMotto": false,
  "sections": {
    "overview": "Haus Tlawd geht auf Edric Tlawd zurück, der als Knappe Maldwyn Gafyr diente und 1285 zum Ritter geschlagen wurde. Es zählt zu den älteren und treuesten Ritterhäusern im Dienst der Gafyr.\n\nDie Tlawd sind ein schlichtes Ritterhaus. Viele ihrer Söhne und Töchter ziehen als fahrende Ritter durchs Land, doch die meisten versehen ihren Dienst unmittelbar bei den Gafyr – sei es am Hofe oder als Lehenswarte: Landherren, die im Auftrag der Gafyr über deren Siedlungen herrschen und deren Interessen vor Ort vertreten.",
    "history": "Sir Edric Tlawd begann als eifriger Knappe im Dienste seines Herren, Sir Maldwyn Gafyr, der später als Ritterfürst das Haus Gafyr anführte. Als Edric zum Ritter geschlagen wurde, schwor er den Gafyr feierlich ewigen Lehnseid. Ritterfürst Maldwyn erkannte seine Treue an und gestattete ihm, ein eigenes Haus zu gründen. So wurde Edric Tlawd als Vasall in die Gefolgschaft der Gafyr aufgenommen.\n\nMit der Erhebung fanden die Tlawd Eingang in den niederen Adel. Das genaue Gründungsjahr ist noch ungeklärt.",
    "traditions": "Die Tlawd sind berühmt für ihre Ritter der Teulu-Kaste, den Schwertkämpfern der Cenyri. Staatsmännische Ämter liegen ihnen weniger; als Kämmerer oder Justiziare sucht man sie vergeblich. Doch wenn es um das Kriegshandwerk geht, sind die Tlawd unersetzlich. In den Reihen der Gafyr dienen sie als Kommandanten, Marschälle, Konstabler, Waffenmeister oder Schmiede – überall dort, wo Stärke, Disziplin und Führung auf dem Schlachtfeld gefragt sind. Will ein Fürst seine Heere mit zähen Kämpfern füllen, sind die Tlawd die erste Wahl.",
    "knighthood": "Folgt …",
    "succession": "Folgt …",
    "holdings": "Das Haus Tlawd residiert auf einer Burg unmittelbar vor den Toren der Hauptstadt Gwynthor, in den Vororten der Stadt des Grafen aus dem Hause Draig. Zu ihren Gütern zählt eine Erzmine in den umliegenden Bergen, deren Ertrag den Tlawd erheblichen Wohlstand sichert. Darüber hinaus unterhalten sie zahlreiche Handwerker, Waffen- und Rüstungsschmiede, die ihren Ruf als versierte Kriegsmänner untermauern. So zählen die Tlawd trotz ihres schlichten Ursprungs zu den wohlhabenderen Ritterhäusern im Gefolge der Gafyr.",
    "cultureReligion": "Wie die meisten Cenyri bekennen sich die Tlawd zur Alerischen Kirche. Besonders verehren sie den Knecht, Gott der Arbeit, Aufrichtigkeit und des Fleißes, sowie den Streiter, Gott des Krieges, der Ehre und der Pflicht. Ihre Frömmigkeit ist schlicht, doch tief verankert in Pflichtbewusstsein und Tatkraft.\n\nKulturell wird den Tlawd eine stärkere crannathische Abstammung, als eine Avallornische nachgesagt.",
    "conflictsAlliances": "Die Tlawd sind unmittelbare Feudalritter der Gafyr. Zwar kommt es vor, dass einzelne Mitglieder zeitweise anderen Herren dienen, doch bleibt dies die Ausnahme. Mit anderen Häusern pflegen die Tlawd gewöhnlich ein konfliktfreies Verhältnis.\n\nJüngst jedoch erschütterte ein Skandal ihren Ruf: Roderic Gafyr und drei Ritter aus dem Hause Tlawd gerieten in eine unzüchtige Affäre, die am Hof offen diskutiert wird. Dieser Vorfall hat nicht nur den Namen der Gafyr befleckt, sondern auch den der Tlawd in Mitleidenschaft gezogen.",
    "values": "Das Haus Tlawd verkörpert die Tugenden des Dienstes, der Treue und der Wehrhaftigkeit. Ihr Ehrenkodex stellt Pflichtbewusstsein, Aufrichtigkeit und Fleiß über diplomatische Raffinesse. Für die Tlawd zählen Schwert, Schild und Schwur mehr als Redekunst oder Hofintrige. Ihr Leitprinzip lautet, den Gafyr unverbrüchlich die Treue zu halten und im Kampf stets Stärke, Disziplin und Ehre zu beweisen.",
    "court": "Überlieferte Personen und Aufgaben. Nicht belegte Angaben bleiben offen.",
    "familyTree": "Die Hausbio öffnet sich über das Wappen im Stammbaum. Personen und Verbindungen sind in der Familienakte verzeichnet.",
    "historicalFigures": "Überlieferte Persönlichkeiten und ihre Bedeutung für das Haus."
  },
  "sectionTitles": {
    "knighthood": "4. Rittertum"
  },
  "scenes": [
    {
      "title": "Gespräch am Lagerfeuer",
      "paragraphs": [
        "[Das Lager ist ruhig, die Männer schlafen. Maldwyn und Edric sitzen am Feuer, Fleisch brutzelt auf dem Spieß]",
        "Maldwyn: „Beiß zu, Junge. Morgen reitest du nicht auf leerem Magen.“",
        "Edric (nimmt das Fleisch, lacht leise): „Manchmal frage ich mich, ob Rittersein mehr Essen oder mehr Schlagen bedeutet.“",
        "Maldwyn: „Beides, Edric. Aber wer satt ist, schlägt härter. Merk dir das.“",
        "Edric: „Dann werde ich doppelt essen. Vielleicht nennt man mich eines Tages den Schwerthungerigen.“",
        "Maldwyn: (schmunzelt) „Iss lieber ordentlich, schlaf recht und halt dein Schwert scharf. Spitznamen kommen von allein.“"
      ]
    }
  ],
  "images": {
    "haus-wappen": {
      "src": "../Stammbäume/assets/images/houses/Llamreis Ankunft/haus-tlawd.png",
      "alt": "Wappen von Haus Tlawd",
      "format": "square"
    },
    "haus-hauptbild": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Llamreis_Ankunft/Haus_Tlawd/assets/hausmotiv.png",
      "alt": "Hausmotiv · Haus Tlawd",
      "format": "portrait",
      "maxHeight": 580
    },
    "haus-banner": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Llamreis_Ankunft/Haus_Gafyr/assets/herrschaftsbanner.png",
      "href": "../Kontinente/Estryll/Königreich Cenyr/Grafschaft Celtigerns Wacht/Herrschaft der Gafyr/Herrschaft der Gafyr.html",
      "alt": "Herrschaftsbanner von Herrschaft der Gafyr",
      "format": "square"
    },
    "hof-founder-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-tlawd/edric-tlawd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view&person=edric-tlawd",
      "alt": "Edric Tlawd",
      "format": "portrait"
    },
    "hof-heads-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-tlawd/edric-tlawd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view&person=edric-tlawd",
      "alt": "Edric Tlawd",
      "format": "portrait"
    },
    "hof-heads-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-tlawd/owain-tlawd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view&person=owain-tlawd",
      "alt": "Owain",
      "format": "portrait"
    },
    "hof-heads-3": {
      "src": "../Stammbäume/assets/images/portraits/haus-tlawd/gareth-tlawd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view&person=gareth-tlawd",
      "alt": "Gareth",
      "format": "portrait"
    },
    "hof-heads-4": {
      "src": "../Stammbäume/assets/images/portraits/haus-tlawd/cadfael-tlawd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view&person=cadfael-tlawd",
      "alt": "Cadfael",
      "format": "portrait"
    },
    "hof-heirs-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-tlawd/siarl-tlawd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view&person=siarl-tlawd",
      "alt": "Siarl",
      "format": "portrait"
    },
    "hof-heirs-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-tlawd/rhyderch-tlawd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view&person=rhyderch-tlawd",
      "alt": "Rhyderch",
      "format": "portrait"
    },
    "hof-heirs-3": {
      "src": "../Stammbäume/assets/images/portraits/haus-tlawd/edric-tlawd-1716.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view&person=edric-tlawd-1716",
      "alt": "Edric",
      "format": "portrait"
    },
    "haus-figur-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-tlawd/edric-tlawd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view&person=edric-tlawd",
      "alt": "Edric Tlawd",
      "format": "portrait"
    },
    "haus-figur-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-tlawd/nedri-tlawd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view&person=nedri-tlawd",
      "alt": "Nedri",
      "format": "portrait"
    },
    "haus-figur-3": {
      "src": "../Stammbäume/assets/images/portraits/haus-tlawd/modlen-tlawd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view&person=modlen-tlawd",
      "alt": "Modlen",
      "format": "portrait"
    }
  },
  "court": {
    "groups": [
      {
        "id": "founder",
        "title": "Gründer",
        "entries": [
          {
            "name": "Edric Tlawd",
            "role": "",
            "detail": "Lebensdaten: 1264–1328",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view&person=edric-tlawd",
            "imageKey": "hof-founder-1"
          }
        ]
      },
      {
        "id": "heads",
        "title": "Oberhauptfolge · Haus Tlawd",
        "note": "Überlieferte Oberhäupter. Zeitangaben werden nur übernommen, soweit sie belegt sind.",
        "entries": [
          {
            "name": "Edric Tlawd",
            "role": "",
            "detail": "Lebensdaten: 1264–1328",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view&person=edric-tlawd",
            "imageKey": "hof-heads-1"
          },
          {
            "name": "Owain",
            "role": "",
            "detail": "Amtszeit: 1328–…",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view&person=owain-tlawd",
            "imageKey": "hof-heads-2"
          },
          {
            "name": "Gareth",
            "role": "",
            "detail": "Amtszeit: …–1690",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view&person=gareth-tlawd",
            "imageKey": "hof-heads-3"
          },
          {
            "name": "Cadfael",
            "role": "",
            "detail": "Amtszeit: 1690–…",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view&person=cadfael-tlawd",
            "imageKey": "hof-heads-4"
          }
        ]
      },
      {
        "id": "heirs",
        "title": "Erbfolge",
        "entries": [
          {
            "name": "Siarl",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view&person=siarl-tlawd",
            "imageKey": "hof-heirs-1"
          },
          {
            "name": "Rhyderch",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view&person=rhyderch-tlawd",
            "imageKey": "hof-heirs-2"
          },
          {
            "name": "Edric",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view&person=edric-tlawd-1716",
            "imageKey": "hof-heirs-3"
          }
        ]
      }
    ],
    "cadets": []
  },
  "figures": {
    "heading": "11. Historische Figuren",
    "tableTitle": "Persönlichkeiten des Hauses",
    "entries": [
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Persönlichkeit des Hauses",
        "name": "Edric Tlawd",
        "description": "Edric Tlawd, der erste seines Namens, trat im Alter von neun Jahren als Page in den Dienst des jungen Ritters Maldwyn Gafyr. Vier Jahre später wurde er dessen Knappe und begleitete ihn in Gefecht und Feldzug. Im Jahre 1285, da Edric einundzwanzig war, schlug ihn Maldwyn eigenhändig zum Ritter. Edric schwor ihm daraufhin einen ewigen Lehnseid und blieb fortan in unverbrüchlicher Treue an seiner Seite. Nach seinem Ritterschlag gestattete ihm Maldwyn, ein eigenes Haus zu gründen. Das genaue Gründungsjahr ist offen. So wurde Edric zum Stammvater des Geschlechts Tlawd, dessen Linie bis heute im Dienst der Gafyr steht. Er starb 1328 im Alter von vierundsechzig Jahren, geehrt als treuer Vasall, Kriegsmann und Begründer eines Hauses, das über Jahrhunderte für Schwert, Schwur und Pflichtbewusstsein bekannt bleiben sollte.",
        "imageKey": "haus-figur-1"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Persönlichkeit des Hauses",
        "name": "Nedri",
        "description": "Sir Nedri entstammt der Generation um Siarl, Lloyd und Modlen – ein Sohn Cadfaels, geprägt von einer Erziehung, die Pflicht, Zähigkeit und altehrwürdige Treue zum Hause Gafyr verlangte. Dennoch sticht er aus der Linie hervor: Während fast alle Tlawd-Ritter ihr Leben ausschließlich in den Diensten der Gafyr verbringen, wurde Nedri ausnahmsweise in den Gefolgsdienst Rhodri des Großen gestellt. Unter dessen Banner zog er in die Kriege des Nordens und Südens, ein ungewöhnlicher Schritt für sein Geschlecht, den er stets als Ehre betrachtet hat. Besonders prägend aber ist seine lebenslange Verbundenheit mit Duncan Gafyr, dem heutigen Haupt des Hauses Gafyr. Gemeinsam wuchsen die beiden heran, wurden Knappen, dann Ritter – Schulter an Schulter. Duncan stieg zum Herr seines Hauses auf, Nedri blieb Ritter im Gefolge, doch ihr Verhältnis blieb stets das eines gleichaltrigen Waffenbruders und Jugendfreundes. In der Erinnerung der Tlawd wird Nedri weniger für große Ämter oder Titel stehen, sondern für diese besondere Verbindung zwischen Vasall und Lehnsherr, wie sie selten so eng geknüpft war.",
        "imageKey": "haus-figur-2"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Persönlichkeit des Hauses",
        "name": "Modlen",
        "description": "Modlen Tlawd, Schwester von Siarl, Nedri und Lloyd, hat sich einen ganz anderen Platz im Stammbaum erobert als ihre kriegerischen Brüder. Während diese den Stahl führten, griff sie zur Laute und zur Feder. Heute ist sie in Gwynthor und in der gesamten Grafschaft von Celtigerns Wacht eine kleine Berühmtheit: Bardin, Schriftstellerin und Künstlerin. Sie gehört dem Musikanten-Quartett „Cymrith“ an, das zur angesehenen Künstlergilde „Musen der Maid“ zählt – einer Bruderschaft reisender Sänger und Geschichtenerzähler, die in Celtigerns Wacht einen Ruf wie Donnerhall genießen. Ausgebildet wurde Modlen in Lynthor, der berühmten Bardenstätte der Grafschaft. Ihr bekanntestes Werk ist das Lied „Krone auf, Herz heraus“, eine romantisch-komische Ballade, die in Tavernen wie in Fürstenhallen gleichermaßen gespielt wird. Mit viel Wortwitz zeichnet sie darin die Eitelkeiten von Hof und Alltag nach, verwebt Tanz, Liebe und den ewigen Schlagabtausch der Geschlechter zu einer Hymne, die zum Schmunzeln ebenso taugt wie zum Mitsingen.",
        "imageKey": "haus-figur-3"
      }
    ]
  },
  "familyTreeEmbed": {
    "src": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-tlawd&mode=view",
    "title": "Stammbaum von Haus Tlawd"
  },
  "trivia": [
    "Folgt …"
  ]
};
