// Generated by scripts/build-house-content.mjs. Edit haus.content.mjs instead.
window.HAEUSER_DATA = {
  "meta": {
    "id": "haus-awenor",
    "title": "Haus Awenor – Aleria",
    "type": "Ritterhaus",
    "status": "Active",
    "template": "kleinehaeuser",
    "storage": {
      "document": "haus-awenor"
    }
  },
  "name": "Haus Awenor",
  "hierarchy": [
    {
      "type": "Sammlung",
      "name": "Familien Häuser und Clans",
      "slug": "familien-hauser-und-clans"
    },
    {
      "type": "Kontinent",
      "name": "Estryll",
      "slug": "estryll"
    },
    {
      "type": "Königreich",
      "name": "Cenyr",
      "slug": "cenyr"
    },
    {
      "type": "Grafschaft",
      "name": "Celtigerns Wacht",
      "slug": "celtigerns-wacht"
    },
    {
      "type": "Region",
      "name": "Llamreis Ankunft",
      "slug": "llamreis-ankunft"
    },
    {
      "type": "Sitz",
      "name": "Gwynthor",
      "slug": "gwynthor"
    },
    {
      "type": "Haus",
      "name": "Haus Awenor",
      "slug": "haus-awenor"
    }
  ],
  "layout": "responsive",
  "classification": {
    "category": "Familien Häuser und Clans",
    "houseType": "Ritterhaus",
    "scale": "Ritterhaus",
    "parentHouseId": "",
    "rootHouseId": "haus-awenor",
    "territoryId": "celtigerns-wacht"
  },
  "profile": {
    "highestTitle": "Ritterherr",
    "rank": "Ritterherr",
    "houseType": "Ritterhaus",
    "motto": "",
    "quoteAuthor": "",
    "seat": "Gwynthor",
    "affiliation": "Haus Draig",
    "liege": "Haus Draig",
    "patron": "",
    "knightingPatron": "",
    "troopStrength": "",
    "tiarna": "",
    "kerns": "",
    "fleet": "",
    "founding": "",
    "milestoneOne": "",
    "milestoneTwo": "",
    "people": "Cenyri",
    "wealth": "Beschaulich",
    "religion": "Die Alerische Kirche",
    "patronDeities": "",
    "origin": "",
    "cadetBranches": "",
    "allies": "",
    "enemies": ""
  },
  "profileLabels": {
    "tiarna": "Ritter",
    "kerns": "Knechte"
  },
  "showMotto": false,
  "sections": {
    "overview": "Haus Awenor ist ein älteres ritterliches Geschlecht im festen Dienst des Hauses Draig, bekannt für militärische Verlässlichkeit, Disziplin und pflichtbewussten Gehorsam. Ohne großen Namen oder Legenden stellen die Awenor für die Draigs bevorzugt Lehenswarte, Statthalter, Hauptmänner und Kommandanten, sichern Bergbauregionen wie Mwynfaen und dienen regelmäßig unter dem Marschall des Grafen. Ihre Burg in Gwynthor, ihre Minen und Schmieden geben ihnen strategische Unabhängigkeit, ihr Glaube an die Alerische Kirche bleibt nüchtern und ordnend. Die Awenor streben nicht nach Ruhm – sie existieren, um Befehle auszuführen, Gebiete zu halten und Ordnung durchzusetzen, solange der Dienst es verlangt.",
    "history": "Der Ursprung des Hauses Awenor reicht mehrere Generationen weiter zurück als jener vieler anderer ritterlicher Vasallen der Draigs. Schon früh stellten sie bewaffnete Gefolgsleute, übernahmen Grenzaufgaben und dienten als verlängerter Arm der gräflichen Autorität. Ihr Schwerpunkt lag nie auf Verwaltung oder Kanzlei, sondern auf militärischer Präsenz und lokaler Herrschaftsausübung.",
    "traditions": "Die Traditionen des Hauses Awenor sind klar, militärisch und frei von Zierde. Ihre Sprösslinge werden früh an Waffen, Disziplin und Befehlsketten gewöhnt. Ausbildung bedeutet bei ihnen Dienstfähigkeit: kämpfen, führen, halten. Schreiben, Rechnen und Etikette werden gelehrt, aber nur soweit, wie es für Amt, Befehl und Verantwortung nötig ist.\n\nFrömmigkeit spielt eine sichtbare, aber nüchterne Rolle. Die Awenor beten, halten Gelübde und achten kirchliche Pflichten, ohne sich als heilige Krieger zu inszenieren. Ehre entsteht nicht durch Ruhm, sondern durch Standhalten. Wer Awenor ist, wird nicht gefragt, ob er dient – sondern wo.",
    "knighthood": "Folgt …",
    "succession": "Folgt …",
    "holdings": "Der Besitz des Hauses Awenor ist zweckmäßig und eng mit Krieg und Versorgung verbunden. Nördlich von Gwynthor liegen mehrere Minen, die dem Haus unterstehen. Sie liefern vor allem Erze für Waffen, Werkzeuge und Bau – ein strategisch wertvoller Besitz, besonders in Zeiten erhöhter militärischer Aktivität.\n\nErgänzend dazu unterhalten die Awenor mehrere Schmieden, teils in direkter Nähe ihrer Ländereien, teils angebunden an ihre Aufgaben im Norden, insbesondere rund um Mwynfaen. Diese Schmieden dienen weniger dem Handel als der Eigenversorgung und der Ausrüstung von Truppen.\n\nIhr Besitz macht die Awenor nicht reich, aber unabhängig – und genau das schätzen die Draigs an ihnen: Waffen, Männer und Nachschub aus einer Hand, ohne Verzögerung, ohne Ausreden.",
    "cultureReligion": "Wie andere Häuser bekennen sich auch die Awenor in selbstverständlicher Weise zur Alerischen Kirche. Ihre Frömmigkeit ist geordnet, pflichtbewusst und frei von Überschwang. Gebete, Feste und kirchliche Abgaben werden eingehalten, Gelübde respektiert, Priester geachtet – nicht aus Ekstase, sondern aus Überzeugung und Gewohnheit.\n\nDie Awenor gelten weder als heilig noch als besonders fromme Ritter. Sie tragen ihren Glauben still, ohne Predigt und ohne Symbolik. Für sie ist Religion Teil der Ordnung, die das Reich zusammenhält, so wie Befehl und Disziplin es im Heer tun. Sie glauben, weil es richtig ist, nicht weil es sie auszeichnet.",
    "conflictsAlliances": "Haus Awenor unterhält keine nennenswerten Fehden und keine eigenständigen Rivalitäten. Politisch wie militärisch richtet es sich geschlossen nach dem Willen des Hauses Draig und verfolgt keine eigene Machtagenda.\n\nAllianzen bestehen vor allem im Dienstverhältnis: enge, sachliche Zusammenarbeit mit anderen ritterlichen Vasallen der Draigs, insbesondere Häusern wie dem Haus Gelyn, mit denen sie regelmäßig gemeinsame Kommandos und Lehenspflichten teilen. Diese Verbindungen sind funktional, nicht familiär oder politisch aufgeladen.\n\nKurz gesagt: Die Awenor suchen keinen Konflikt, pflegen keine Feindschaften und gelten genau deshalb als verlässliche Stütze – ein Haus, das nicht spaltet, sondern hält.",
    "values": "Die Moral des Hauses Awenor gründet auf Pflicht, Gehorsam und Standhaftigkeit. Sie messen den Wert eines Ritters nicht an Ruhm oder Herkunft, sondern daran, ob er hält, wenn er gebraucht wird. Befehl wird ausgeführt, Verantwortung getragen, Stellung gewahrt.\n\nEin Awenor fragt nicht nach Auszeichnung, sondern nach Auftrag. Er dient, kämpft und bleibt, bis er abgelöst wird – überzeugt davon, dass Ordnung, Disziplin und Treue mehr Bestand haben als jedes Heldentum.",
    "court": "Überlieferte Personen und Aufgaben. Nicht belegte Angaben bleiben offen.",
    "familyTree": "Die Hausbio öffnet sich über das Wappen im Stammbaum. Personen und Verbindungen sind in der Familienakte verzeichnet.",
    "historicalFigures": "Überlieferte Persönlichkeiten und ihre Bedeutung für das Haus."
  },
  "sectionTitles": {
    "knighthood": "4. Rittertum"
  },
  "images": {
    "haus-wappen": {
      "src": "../Stammbäume/assets/images/houses/Llamreis Ankunft/haus-awenor.png",
      "alt": "Wappen von Haus Awenor",
      "format": "square"
    },
    "haus-hauptbild": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Llamreis_Ankunft/Haus_Awenor/assets/hausmotiv.png",
      "alt": "Hausmotiv · Haus Awenor",
      "format": "portrait",
      "maxHeight": 580
    },
    "haus-banner": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Haus_Draig/assets/gwynthor.png",
      "href": "../Kontinente/Estryll/Königreich Cenyr/Grafschaft Celtigerns Wacht/Grafschaft Celtigerns Wacht.html",
      "alt": "Herrschaftsbanner von Celtigerns Wacht",
      "format": "square"
    },
    "hof-founder-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenor/aergol-awenor.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenor&mode=view&person=aergol-awenor",
      "alt": "Aergol Awenor",
      "format": "portrait"
    },
    "hof-heads-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenor/aergol-awenor.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenor&mode=view&person=aergol-awenor",
      "alt": "Aergol Awenor",
      "format": "portrait"
    },
    "hof-heads-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenor/glynfael-awenor.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenor&mode=view&person=glynfael-awenor",
      "alt": "Glynfael Awenor",
      "format": "portrait"
    },
    "hof-heads-3": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenor/ffraid-awenor.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenor&mode=view&person=ffraid-awenor",
      "alt": "Ffraid Awenor",
      "format": "portrait"
    },
    "hof-heirs-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenor/derwain-awenor.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenor&mode=view&person=derwain-awenor",
      "alt": "Derwain Awenor",
      "format": "portrait"
    },
    "hof-heirs-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenor/urfael-awenor.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenor&mode=view&person=urfael-awenor",
      "alt": "Urfael Awenor",
      "format": "portrait"
    },
    "hof-heirs-3": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenor/isgar-awenor.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenor&mode=view&person=isgar-awenor",
      "alt": "Isgar Awenor",
      "format": "portrait"
    },
    "haus-figur-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenor/rhyd-awenor.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenor&mode=view&person=rhyd-awenor",
      "alt": "Rhyd Awenor",
      "format": "portrait"
    },
    "haus-figur-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenor/rhys-awenor.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenor&mode=view&person=rhys-awenor",
      "alt": "Rhys Awenor",
      "format": "portrait"
    }
  },
  "court": {
    "groups": [
      {
        "id": "founder",
        "title": "Gründer",
        "entries": [
          {
            "name": "Aergol Awenor",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenor&mode=view&person=aergol-awenor",
            "imageKey": "hof-founder-1"
          }
        ]
      },
      {
        "id": "heads",
        "title": "Oberhauptfolge · Haus Awenor",
        "note": "Überlieferte Oberhäupter. Zeitangaben werden nur übernommen, soweit sie belegt sind.",
        "entries": [
          {
            "name": "Aergol Awenor",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenor&mode=view&person=aergol-awenor",
            "imageKey": "hof-heads-1"
          },
          {
            "name": "Glynfael Awenor",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenor&mode=view&person=glynfael-awenor",
            "imageKey": "hof-heads-2"
          },
          {
            "name": "Ffraid Awenor",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenor&mode=view&person=ffraid-awenor",
            "imageKey": "hof-heads-3"
          }
        ]
      },
      {
        "id": "heirs",
        "title": "Erbfolge",
        "entries": [
          {
            "name": "Derwain Awenor",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenor&mode=view&person=derwain-awenor",
            "imageKey": "hof-heirs-1"
          },
          {
            "name": "Urfael Awenor",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenor&mode=view&person=urfael-awenor",
            "imageKey": "hof-heirs-2"
          },
          {
            "name": "Isgar Awenor",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenor&mode=view&person=isgar-awenor",
            "imageKey": "hof-heirs-3"
          }
        ]
      }
    ],
    "cadets": []
  },
  "figures": {
    "heading": "11. Historische Figuren",
    "tableTitle": "Persönlichkeiten des Hauses",
    "entries": [
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Persönlichkeit des Hauses",
        "name": "Rhyd Awenor",
        "description": "Rhyd ist einer der Lehensritter des Zauberers Myrddin. Dieses Lehen ist weniger von Rang als von Nähe geprägt: Myrddin benötigt selten einen Ritter – doch wenn etwas erledigt werden muss, greift er zuerst zu den Zwillingen. Rhyd fungiert dabei als erste Anlaufstelle, sei der Auftrag noch so unscheinbar oder heikel. Im Wesen ist Rhyd der mürrischere der beiden. Wortkarg, nüchtern, skeptisch. Er stellt keine Fragen, sondern sorgt dafür, dass Dinge verschwinden, beschafft oder geordnet werden. Wo andere diskutieren, handelt Rhyd.",
        "imageKey": "haus-figur-1"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Persönlichkeit des Hauses",
        "name": "Rhys Awenor",
        "description": "Rhys, Rhyds Zwillingsbruder, teilt Dienst, Aufgabe und Lehen, unterscheidet sich jedoch deutlich im Auftreten. Er ist meist offener, freundlicher und wirkt zugänglicher – fast so, als wolle er den Ernst ihres Dienstes ausgleichen. Gemeinsam bilden die Brüder ein eingespieltes Paar: Rhyd als der harte Rand, Rhys als das menschliche Gesicht. Für Myrddin sind sie keine Repräsentanten, sondern Werkzeuge mit Verstand – zuverlässig, loyal und immer dort, wo man sie braucht.",
        "imageKey": "haus-figur-2"
      }
    ]
  },
  "familyTreeEmbed": {
    "src": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenor&mode=view",
    "title": "Stammbaum von Haus Awenor"
  },
  "trivia": [
    "Folgt …"
  ]
};
