// Generated by scripts/build-house-content.mjs. Edit haus.content.mjs instead.
window.HAEUSER_DATA = {
  "meta": {
    "id": "haus-cysgodion",
    "title": "Haus Cysgodion – Aleria",
    "type": "Ritterhaus",
    "status": "Active",
    "template": "kleinehaeuser",
    "storage": {
      "document": "haus-cysgodion"
    }
  },
  "name": "Haus Cysgodion",
  "hierarchy": [
    {
      "type": "Sammlung",
      "name": "Familien Häuser und Clans",
      "slug": "familien-hauser-und-clans"
    },
    {
      "type": "Kontinent",
      "name": "Estryll",
      "slug": "estryll"
    },
    {
      "type": "Königreich",
      "name": "Cenyr",
      "slug": "cenyr"
    },
    {
      "type": "Grafschaft",
      "name": "Celtigerns Wacht",
      "slug": "celtigerns-wacht"
    },
    {
      "type": "Region",
      "name": "Gwendolyns Ufer",
      "slug": "gwendolyns-ufer"
    },
    {
      "type": "Sitz",
      "name": "Abergwint",
      "slug": "abergwint"
    },
    {
      "type": "Haus",
      "name": "Haus Cysgodion",
      "slug": "haus-cysgodion"
    }
  ],
  "layout": "responsive",
  "classification": {
    "category": "Familien Häuser und Clans",
    "houseType": "Ritterhaus",
    "scale": "Ritterhaus",
    "parentHouseId": "",
    "rootHouseId": "haus-cysgodion",
    "territoryId": "baronie-gwendolyns-ufer"
  },
  "profile": {
    "highestTitle": "Ritterherr",
    "rank": "Ritterherr",
    "houseType": "Ritterhaus",
    "motto": "Im Schatten des Wyvern.",
    "quoteAuthor": "Cadwalader Cysgodion",
    "seat": "Abergwint",
    "affiliation": "Haus Gwyvern",
    "liege": "Haus Gwyvern",
    "patron": "Haus Gwyvern",
    "knightingPatron": "Haus Draig",
    "troopStrength": "",
    "tiarna": "",
    "kerns": "",
    "fleet": "",
    "founding": "",
    "milestoneOne": "",
    "milestoneTwo": "",
    "people": "Cenyri",
    "wealth": "Beschaulich",
    "religion": "",
    "patronDeities": "",
    "origin": "Cadwalader Cysgodion",
    "cadetBranches": "",
    "allies": "",
    "enemies": ""
  },
  "profileLabels": {
    "tiarna": "Ritter",
    "kerns": "Knechte"
  },
  "showMotto": true,
  "sections": {
    "overview": "Das Haus Cysgodion ist ein niederes ritterliches Haus aus der Stadt Abergwint und steht als Vasall im Dienst des baronialen Hauses Gwyvern. Sein Name ist in der Region bekannt, doch selten mit offenen Taten oder öffentlicher Präsenz verbunden.\n\nBegründet wurde das Haus durch Cadwalader Cysgodion, einen Ritter und Staatsmann, der bereits in früher Zeit im Dienst des Hauses Draig stand. Aus diesem Dienst heraus entstand ein Geschlecht, dessen Aufgabe nie offen definiert, aber stets fest verankert war.\n\nBis heute nimmt Haus Cysgodion eine zurückhaltende Rolle innerhalb der Herrschaft Abergwints ein – bewusst unauffällig, fest eingebunden in die Ordnung der Baronie und eng an seine Lehnsherren gebunden.\n\nDas Haus Cysgodion ist ein niederes ritterliches Geschlecht aus Abergwint, dessen Bedeutung weniger in Landbesitz oder militärischer Stärke liegt als in seiner Funktion innerhalb der baronialen Ordnung. Das Haus ist klein gehalten, streng organisiert und auf Kontinuität statt Ausbreitung ausgerichtet.\n\nSein Ruf ist geprägt von Zurückhaltung und Distanz. Die Cysgodion treten selten öffentlich auf, pflegen wenig Nähe zum einfachen Volk und sind außerhalb der höfischen und verwaltungstechnischen Kreise kaum greifbar. Gerade diese Unauffälligkeit gilt innerhalb der Baronie als Zeichen von Verlässlichkeit.\n\nGegenwärtig stehen die Cysgodion fest im Dienst des Hauses Gwyvern. Ihre Stellung ist gesichert, ihr Einfluss nicht offen sichtbar, doch innerhalb der politischen Strukturen Abergwints fest verankert und anerkannt.",
    "history": "Das Haus Cysgodion geht auf Cadwalader Cysgodion zurück, einen Ritter und Staatsmann im Dienst des Hauses Draig, der in früher Zeit als vertrauenswürdiger Diener der Grafschaft Celtigerns Wacht wirkte. Für seine Loyalität und Dienste wurde er zum Ritterherren erhoben und begründete ein eigenes Haus.\n\nÜber Generationen hinweg dienten die Cysgodion den Draig, bis mit der Abspaltung des Kadettenhauses Gwyvern ein Wechsel des Lehnsherrn erfolgte. Seitdem stehen sie in Abergwint im Dienst der Gwyvern und blieben ihrer ursprünglichen Aufgabe treu, ohne ihre Rolle je offen zu verändern.",
    "traditions": "Das Haus Cysgodion ist ein ritterliches Geschlecht, das sich seit seiner Gründung der Staatsbildung und Verwaltung der Baronie verschrieben hat. Ihr Kodex lautet: „Wir wandeln im Schatten des Wyvern.“ Dieses Selbstverständnis prägt ihr Handeln ebenso wie ihr Auftreten – stets im Dienst des Hauses Gwyvern, niemals im Vordergrund.\n\nDie Mitglieder des Hauses werden als vollwertige Ritter ausgebildet, jedoch gleichermaßen in Staatskunde, Recht, Verwaltung und höfischer Ordnung unterwiesen. Nicht jeder Cysgodion tritt als „Schatten“ in Erscheinung; viele dienen offen als Ritter, Würdenträger, Justiziare oder Kämmerer im Auftrag ihrer Lehnsherren.\n\nGemeinsame Tradition ist dabei stets die Zurückhaltung. Prunk, öffentliche Glorie und demonstrative Machtentfaltung gelten als unziemlich. Die Cysgodion halten sich bewusst bedeckt, bevorzugen schlichte Darstellung und wirken dort, wo ihre Arbeit nötig ist – nicht dort, wo sie gesehen wird.",
    "knighthood": "Folgt …",
    "succession": "Folgt …",
    "holdings": "Die Cysgodion bewohnen kein wehrhaftes Kastell, sondern ein schlichtes Anwesen innerhalb der Stadtmauern Abergwints, gelegen in einem der unscheinbarsten Viertel der Stadt. Lage und Bauweise sind bewusst unauffällig gewählt und dienen mehr der Nähe zu Verwaltung und Hof als der Repräsentation.\n\nZum Besitz des Hauses zählen mehrere Tavernen und Herbergen innerhalb Abergwints sowie vereinzelt im Umland. Diese stehen nicht unter der direkten Verwaltung der Cysgodion, entrichten jedoch Pacht und liefern Informationen. Klassische Lehnsverhältnisse bestehen nicht: Gehöfte, Bauern oder Fischer gehören ausdrücklich nicht zu ihren Vasallen. Stattdessen treten die Cysgodion gelegentlich als Gönner einzelner Händler ihres Viertels auf, ohne formale Bindung oder öffentliche Patronage.\n\nDer eigentliche Wohlstand des Hauses entspringt seinen Ämtern bei Hofe. Einkünfte aus Verwaltung, Recht und Beratung sichern ihren Stand, ohne sichtbaren Reichtum anzuhäufen. Auffälliger Besitz gilt als Risiko – Wohlstand zieht Aufmerksamkeit auf sich, und Aufmerksamkeit widerspricht dem Selbstverständnis des Hauses.\n\nDennoch ist es eine bekannte, wenn auch selten erwähnte Wahrheit, dass es in nahezu jeder Generation ein schwarzes Schaf gibt – ein Mitglied, das genau jene Aufmerksamkeit sucht, die der Rest des Hauses meidet.",
    "cultureReligion": "Nach außen hin gibt das Haus Cysgodion keinerlei Auskunft über seine kulturellen oder religiösen Prägungen. Diese bewusste Verschlossenheit hat über die Jahre Raum für Gerüchte geschaffen, ohne je etwas zu bestätigen oder zu widerlegen.\n\nSo wird gemunkelt, das Haus habe aldrimarische Wurzeln; andere Stimmen behaupten gar, seine Ursprünge lägen jenseits des Kontinents, in fernen Landen wie Lothir oder Aldervan. Keines dieser Gerüchte wurde je belegt – und die Cysgodion zeigen keinerlei Interesse, Licht in diese Fragen zu bringen.\n\nReligiös gilt das Haus als zurückhaltend bis gleichgültig. Es pflegt keine auffälligen Kulte, Stiftungen oder religiösen Verpflichtungen. Stattdessen gilt ihre Loyalität allein dem Haus Gwyvern. Diese unbedingte Treue genügt ihren Lehnsherren vollkommen – die Gwyvern schätzen die Cysgodion nicht für ihren Glauben, sondern für ihre Verlässlichkeit.",
    "conflictsAlliances": "In den Adelszirkeln Abergwints werden die Cysgodion meist gemieden oder bewusst umgangen. Nicht aus Feindschaft, Angst oder offener Abneigung, sondern aus Vorsicht. Das Haus handelt nicht mit Land, Schwertern oder Titeln, sondern mit Wissen und Informationen – und genau das macht den Umgang mit ihnen unangenehm.\n\nFür die meisten Häuser stellen die Cysgodion keine unmittelbare Gefahr dar. Sie führen keine Fehden, beanspruchen kein fremdes Besitztum und treten selten als politische Gegenspieler auf. Dennoch gilt: Wer mit ihnen zu offen spricht, spricht womöglich zu viel. Und wer zu viel preisgibt, verliert Kontrolle.\n\nOffene Konflikte sind daher selten, Allianzen ebenso. Die wenigen stabilen Bindungen des Hauses bestehen fast ausschließlich zum Haus Gwyvern, dem ihre Loyalität unangefochten gilt. Abseits davon bleiben die Cysgodion bewusst isoliert – nicht ausgestoßen, aber auch nie wirklich eingeladen.",
    "values": "Das Haus Cysgodion misst Wert nicht an Ruhm, Frömmigkeit oder öffentlicher Anerkennung, sondern an Nützlichkeit, Loyalität und Kontrolle. Moral ist für sie kein Ideal, sondern ein Werkzeug, das dem Erhalt der Ordnung dient.\n\nAn oberster Stelle steht die Treue zum Lehnsherrn. Verpflichtungen gegenüber dem Haus Gwyvern wiegen schwerer als persönliche Bindungen, Ehre oder Tradition. Entscheidungen werden nicht danach getroffen, was als gerecht gilt, sondern danach, was stabilisiert.\n\nDie Cysgodion schätzen Verschwiegenheit, Zurückhaltung und Disziplin. Wissen ist Macht, und Macht wird nicht gezeigt, sondern verwaltet. Offene Konfrontation gilt als Versagen der Vorbereitung. Wer laut werden muss, hat zu spät gehandelt.\n\nPersönlicher Ehrgeiz ist erlaubt, solange er dem Haus dient. Auffälligkeit, Eitelkeit und das Streben nach Glorie gelten hingegen als Schwächen. Ein Cysgodion soll wirken, ohne gesehen zu werden – und verschwinden können, ohne Spuren zu hinterlassen.",
    "court": "Überlieferte Oberhäupter, Erben und Aufgaben. Unbekannte Angaben bleiben offen.",
    "familyTree": "Die Hausbio öffnet sich über das Wappen im Stammbaum. Personen und Verbindungen sind in der Familienakte verzeichnet.",
    "historicalFigures": "Überlieferte Persönlichkeiten des Hauses."
  },
  "sectionTitles": {
    "knighthood": "4. Rittertum"
  },
  "images": {
    "haus-wappen": {
      "src": "../Stammbäume/assets/images/houses/Gwendolyns Ufer/Ritterliche/Cysgodion.png",
      "alt": "Wappen von Haus Cysgodion",
      "format": "square"
    },
    "haus-hauptbild": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Gwendolyns_Ufer/Haus_Cysgodion/assets/hausmotiv.png",
      "alt": "Hausmotiv · Haus Cysgodion",
      "format": "portrait",
      "maxHeight": 580
    },
    "haus-banner": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Gwendolyns_Ufer/Haus_Gwyvern/assets/herrschaftsbanner.png",
      "href": "../Kontinente/Estryll/Königreich Cenyr/Grafschaft Celtigerns Wacht/Baronie Gwendolyns Ufer/Baronie Gwendolyns Ufer.html",
      "alt": "Herrschaftsbanner von Baronie Gwendolyns Ufer",
      "format": "square"
    },
    "hof-founder-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-cysgodion/cadwalader-cysgodion.png",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view&person=cadwalader-cysgodion",
      "alt": "Cadwalader Cysgodion",
      "format": "portrait"
    },
    "hof-heads-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-cysgodion/cadwalader-cysgodion.png",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view&person=cadwalader-cysgodion",
      "alt": "Cadwalader Cysgodion",
      "format": "portrait"
    },
    "hof-heads-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-cysgodion/yorath-cysgodion.png",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view&person=yorath-cysgodion",
      "alt": "Yorath Cysgodion",
      "format": "portrait"
    },
    "hof-heirs-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-cysgodion/cefin-cysgodion.png",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view&person=cefin-cysgodion",
      "alt": "Cefin Cysgodion",
      "format": "portrait"
    },
    "hof-heirs-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-cysgodion/carys-cysgodion.png",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view&person=carys-cysgodion",
      "alt": "Carys Cysgodion",
      "format": "portrait"
    },
    "haus-figur-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-cysgodion/cadwalader-cysgodion.png",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view&person=cadwalader-cysgodion",
      "alt": "Cadwalader Cysgodion",
      "format": "portrait"
    },
    "haus-figur-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-cysgodion/yorath-cysgodion.png",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view&person=yorath-cysgodion",
      "alt": "Yorath Cysgodion",
      "format": "portrait"
    },
    "haus-figur-3": {
      "src": "../Stammbäume/assets/images/portraits/haus-cysgodion/gronw-cysgodion.png",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view&person=gronw-cysgodion",
      "alt": "Gronw Cysgodion",
      "format": "portrait"
    },
    "haus-figur-4": {
      "src": "../Stammbäume/assets/images/portraits/haus-cysgodion/pryce-cysgodion.png",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view&person=pryce-cysgodion",
      "alt": "Pryce Cysgodion",
      "format": "portrait"
    },
    "haus-figur-5": {
      "src": "../Stammbäume/assets/images/portraits/haus-cysgodion/morgan-cysgodion.png",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view&person=morgan-cysgodion",
      "alt": "Morgan Cysgodion",
      "format": "portrait"
    },
    "haus-figur-6": {
      "src": "../Stammbäume/assets/images/portraits/haus-cysgodion/cystennin-cysgodion.png",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view&person=cystennin-cysgodion",
      "alt": "Cystennin Cysgodion",
      "format": "portrait"
    },
    "haus-figur-7": {
      "src": "../Stammbäume/assets/images/portraits/haus-cysgodion/cadogan-cysgodion.png",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view&person=cadogan-cysgodion",
      "alt": "Cadogan Cysgodion",
      "format": "portrait"
    },
    "haus-figur-8": {
      "src": "../Stammbäume/assets/images/portraits/haus-cysgodion/folant-cysgodion.png",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view&person=folant-cysgodion",
      "alt": "Folant Cysgodion",
      "format": "portrait"
    },
    "haus-figur-9": {
      "src": "../Stammbäume/assets/images/portraits/haus-cysgodion/cefin-cysgodion.png",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view&person=cefin-cysgodion",
      "alt": "Cefin Cysgodion",
      "format": "portrait"
    }
  },
  "court": {
    "groups": [
      {
        "id": "founder",
        "title": "Gründer",
        "entries": [
          {
            "name": "Cadwalader Cysgodion",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view&person=cadwalader-cysgodion",
            "imageKey": "hof-founder-1"
          }
        ]
      },
      {
        "id": "heads",
        "title": "Oberhauptfolge · Haus Cysgodion",
        "note": "Überlieferte Oberhäupter; Lücken und nicht belegte Amtszeiten bleiben offen.",
        "entries": [
          {
            "name": "Cadwalader Cysgodion",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view&person=cadwalader-cysgodion",
            "imageKey": "hof-heads-1"
          },
          {
            "name": "Yorath Cysgodion",
            "role": "",
            "detail": "Amtszeit: 1720–…",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view&person=yorath-cysgodion",
            "imageKey": "hof-heads-2"
          }
        ]
      },
      {
        "id": "heirs",
        "title": "Erbfolge",
        "entries": [
          {
            "name": "Cefin Cysgodion",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view&person=cefin-cysgodion",
            "imageKey": "hof-heirs-1"
          },
          {
            "name": "Carys Cysgodion",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view&person=carys-cysgodion",
            "imageKey": "hof-heirs-2"
          }
        ]
      }
    ],
    "cadets": []
  },
  "figures": {
    "heading": "11. Historische Figuren",
    "tableTitle": "Persönlichkeiten des Hauses",
    "entries": [
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Persönlichkeit des Hauses",
        "name": "Cadwalader Cysgodion",
        "description": "Cadwalader Cysgodion war Ritter und Staatsmann. Er diente der Grafschaft Celtigerns Wacht und dem damaligen Hause Draig nicht als Feldherr oder Bannerträger, sondern als politischer Verwalter und Vertrauensmann. Seine Aufgabe lag im Ordnen, Beobachten und Absichern der Grafschaft – ein Mann des Wortes, des Urteils und der stillen Durchsetzung, nicht der offenen Gewalt. Für diese Dienste wurde er zum Ritterherren erhoben und begründete das Haus Cysgodion. Seine Rolle prägte das Haus dauerhaft: nicht als Kriegerdynastie, sondern als ritterliches Geschlecht mit staatstragender Funktion.",
        "imageKey": "haus-figur-1"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Ritterherr Yorath",
        "name": "Yorath Cysgodion",
        "description": "Ritterherr Yorath Cysgodion ist das Oberhaupt des Hauses. Er bekleidet derzeit kein offizielles Amt im Hofstaat des Barons oder der Gwyvern. Stattdessen konzentriert er sich vollständig auf die Führung und Organisation des Hauses. Yorath verteilt Aufgaben, lenkt seine Mitglieder und sorgt dafür, dass die Cysgodion reibungslos und geschlossen funktionieren. Nach außen tritt er kaum in Erscheinung, doch innerhalb des Hauses ist seine Autorität unumstritten.",
        "imageKey": "haus-figur-2"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Sir Gronw",
        "name": "Gronw Cysgodion",
        "description": "Sir Gronw Cysgodion ist der derzeitige Schatten der Baronie. Er koordiniert und dirigiert das Spionage- und Aufklärungsnetzwerk der Baronie und trägt die volle Verantwortung für Sammlung, Bewertung und Weitergabe relevanter Informationen. In dieser Funktion berät er den Baron direkt und setzt dessen Anweisungen in verdeckten Angelegenheiten um. Derzeit liegt sein Hauptaugenmerk auf dem Aufspüren der Raubritter, die in der gesamten Grafschaft und Baronie als die Schwarzen Zitteraale bekannt sind und seit rund fünfzehn Jahren mordend und plündernd wüten.",
        "imageKey": "haus-figur-3"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Sir Pryce",
        "name": "Pryce Cysgodion",
        "description": "Sir Pryce Cysgodion ist der Registrator des Schattens und damit direkter Stellvertreter Sir Gronws. Er dokumentiert, sammelt und ordnet Informationen und entwickelt daraus strategische Einschätzungen, die er zunächst mit seinem Vorgesetzten und Vetter bespricht, bevor sie dem Baron vorgelegt werden. In dieser Funktion fungiert er als Filter und Strukturgeber zwischen rohem Wissen und politischer Entscheidung. Gelegentlich begleitet er Sir Gronw auch persönlich, wenn dieser den Baron berät, bleibt dabei jedoch meist im Hintergrund.",
        "imageKey": "haus-figur-4"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Sir Morgan",
        "name": "Morgan Cysgodion",
        "description": "Sir Morgan Cysgodion weicht innerhalb des Hauses von der Norm ab. Er erfüllt seine Pflicht ohne Zögern, zeigt jedoch weder Interesse an Staatskunst noch an verdeckten Aufgaben. Seine Rolle ist klar und bewusst schlicht: Er bildet die Sprösslinge des Hauses zu Rittern aus. Sir Morgan ist ein Ritter – nicht mehr, aber auch nicht weniger. Trotz seiner Abweichung vom üblichen Weg des Hauses verlässt sich Haus Cysgodion auf ihn. Seine Verlässlichkeit liegt nicht in List oder Planung, sondern in Disziplin, Erfahrung und Pflichtbewusstsein.",
        "imageKey": "haus-figur-5"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Sir Cystennin",
        "name": "Cystennin Cysgodion",
        "description": "Sir Cystennin Cysgodion ist mit seinen 23 Jahren eines der jüngsten, aber bereits aktiven Mitglieder des Hauses. Er ist als Spitzel in das Spionagenetzwerk der Baronie eingebunden und wird schrittweise an die Rolle des nächsten Schattens herangeführt. Noch trägt er keine Verantwortung, sondern sammelt Erfahrung. Bis dahin gilt für ihn nur eines: lernen, lauschen und flüstern.",
        "imageKey": "haus-figur-6"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Sir Cadogan",
        "name": "Cadogan Cysgodion",
        "description": "Sir Cadogan Cysgodion ist der Vater von Sir Morgan und ein alter Ritter des Hauses. Innerhalb der Cysgodion ist er für Sicherheit, Ausbildung und das Anwesen verantwortlich. Die allgegenwärtige Geheimniskrämerei und das Spionagewesen liegen ihm nicht und interessieren ihn wenig. Entsprechend hält er sich bewusst aus diesen Bereichen heraus. Stattdessen übernimmt er jene Aufgaben, für die er geeignet ist – so wie auch sein Sohn. In diesen Belangen gilt er als verlässlich und unersetzlich.",
        "imageKey": "haus-figur-7"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Sir Folant",
        "name": "Folant Cysgodion",
        "description": "Sir Folant Cysgodion ist der Sohn von Sir Pryce und Astrid Cysgodion. Er kommt deutlich nach seiner Mutter: blond, attraktiv und sich dessen sehr bewusst. Folant zieht Aufmerksamkeit auf sich – und genießt sie. Genau das missfällt dem Haus, das Zurückhaltung und Unauffälligkeit schätzt. Folant hingegen will glänzen, sehnt sich nach Ruhm, Ehre und Abenteuern und spricht gern davon, den Schwarzen Zitteraalen eigenhändig das Handwerk zu legen. In der Praxis bleibt es meist bei Worten. Statt ritterlicher Pflichterfüllung jagt er eher Schürzen als Feinde. Ob aus ihm je mehr wird als ein prahlender Schönling, ist offen – das Haus beobachtet ihn mit Skepsis.",
        "imageKey": "haus-figur-8"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Sir Cefin",
        "name": "Cefin Cysgodion",
        "description": "Sir Cefin Cysgodion ist der Sohn von Ritterherr Yorath und der Erbe des Hauses. Sein Vater erzieht ihn streng, aber fair. Cefin soll eines Tages das Haus führen und dessen Werte vollständig verinnerlichen. Bis dahin gilt für ihn Gehorsam, Disziplin und die konsequente Teilnahme an Ausbildung und Dienst. Schritt für Schritt übernimmt er bereits erste Pflichten des Erben. Ritterherr Yorath ist mit ihm zufrieden.",
        "imageKey": "haus-figur-9"
      }
    ]
  },
  "familyTreeEmbed": {
    "src": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-cysgodion&mode=view",
    "title": "Stammbaum von Haus Cysgodion"
  },
  "trivia": [
    "Folgt …"
  ]
};
