// Generated by scripts/build-house-content.mjs. Edit haus.content.mjs instead.
window.HAEUSER_DATA = {
  "meta": {
    "id": "haus-loer",
    "title": "Haus Loer – Aleria",
    "type": "Ritterhaus",
    "status": "Active",
    "template": "kleinehaeuser",
    "storage": {
      "document": "haus-loer"
    }
  },
  "name": "Haus Loer",
  "hierarchy": [
    {
      "type": "Sammlung",
      "name": "Familien Häuser und Clans",
      "slug": "familien-hauser-und-clans"
    },
    {
      "type": "Kontinent",
      "name": "Estryll",
      "slug": "estryll"
    },
    {
      "type": "Königreich",
      "name": "Cenyr",
      "slug": "cenyr"
    },
    {
      "type": "Grafschaft",
      "name": "Celtigerns Wacht",
      "slug": "celtigerns-wacht"
    },
    {
      "type": "Region",
      "name": "Llamreis Ankunft",
      "slug": "llamreis-ankunft"
    },
    {
      "type": "Sitz",
      "name": "Gwynthor",
      "slug": "gwynthor"
    },
    {
      "type": "Haus",
      "name": "Haus Loer",
      "slug": "haus-loer"
    }
  ],
  "layout": "responsive",
  "classification": {
    "category": "Familien Häuser und Clans",
    "houseType": "Ritterhaus",
    "scale": "Ritterhaus",
    "parentHouseId": "",
    "rootHouseId": "haus-loer",
    "territoryId": "herrschaft-wyrm"
  },
  "profile": {
    "highestTitle": "Ritterherr",
    "rank": "Ritterherr",
    "houseType": "Ritterhaus",
    "motto": "",
    "quoteAuthor": "",
    "seat": "Höhenburg bei Craithglyn; Herrenhaus in Gwynthor",
    "affiliation": "Haus Wyrm",
    "liege": "Haus Wyrm",
    "patron": "",
    "knightingPatron": "",
    "troopStrength": "",
    "tiarna": "",
    "kerns": "",
    "fleet": "",
    "founding": "",
    "milestoneOne": "",
    "milestoneTwo": "",
    "people": "Cenyri",
    "wealth": "",
    "religion": "Die Alerische Kirche",
    "patronDeities": "",
    "origin": "",
    "cadetBranches": "",
    "allies": "",
    "enemies": ""
  },
  "profileLabels": {
    "tiarna": "Ritter",
    "kerns": "Knechte"
  },
  "showMotto": false,
  "sections": {
    "overview": "Das Haus Loer ist ein niederes Rittergeschlecht aus den Gebirgen Craithglyns und Vasall des Ritterfürstenhauses Wyrm. Seine Macht gründet sich weniger auf große Heere als auf wirtschaftlichen Einfluss.\n\nDurch seine Beteiligungen an den Edelsteinminen Craithglyns sowie eigene Bergwerke, Goldschmieden und Juwelierbetriebe kontrolliert das Haus einen bedeutenden Teil des Edelsteinhandels innerhalb Gwynthors.\n\nDie Familie gilt als wohlhabend, zurückhaltend und äußerst geschäftstüchtig. Ihre Ritter treten in außergewöhnlich prachtvollen Rüstungen auf, reich verziert mit Gold, Silber und Edelsteinen, ohne dabei ihre militärische Disziplin einzubüßen.\n\nIn Craithglyn stellte Haus Loer mehrfach den Hauptmann der Stadt und zeitweise sogar den Lehensherrn. In Gwynthor unterhält das Haus lediglich ein repräsentatives Herrenhaus, das den Angehörigen während ihrer Aufenthalte am Grafenhof als Residenz dient.",
    "history": "Die Ursprünge des Hauses reichen bis in die Erschließung der Gebirge rund um Craithglyn zurück. Der Überlieferung nach entdeckten ihre Vorfahren die ersten ergiebigen Edelsteinadern der Region und errichteten zum Schutz der Bergwerke ihre Burg zwischen den Gipfeln.\n\nWährend andere Ritterhäuser ihre Macht durch Ritterlichkeit vergrößerten, investierten die Loer in Bergbau, Schmiedekunst und Handel. Mit jedem neu erschlossenen Stollen wuchs ihr Vermögen ebenso wie ihr Einfluss.\n\nMehrfach übernahmen Angehörige des Hauses die Verwaltung Craithglyns und sorgten für den Ausbau der Minen, Handelsstraßen und Werkstätten. Dadurch entwickelte sich die Stadt zu einem der bedeutendsten Zentren für Edelsteine und Schmuck innerhalb Gwynthors.\n\nBis heute gilt Haus Loer als eines der wirtschaftlich stabilsten Ritterhäuser der Grafschaft.",
    "traditions": "Die Loer messen handwerklicher Vollkommenheit höchsten Wert bei.\n\nJunge Angehörige verbringen traditionell mehrere Jahre in den Werkstätten der Goldschmiede oder Edelsteinschleifer, bevor sie ritterliche oder verwalterische Aufgaben übernehmen.\n\nZur Schwertleite erhält jedes Familienmitglied einen persönlich geschliffenen Edelstein, dessen Farbe den eigenen Charakter oder die Berufung symbolisieren soll. Dieser Stein begleitet seinen Träger oft ein Leben lang.\n\nPrunk gilt innerhalb des Hauses nicht als Eitelkeit, sondern als Zeichen der Verbundenheit gegenüber der Regenbogenschmiede.",
    "knighthood": "Folgt …",
    "succession": "Folgt …",
    "holdings": "Der Stammsitz des Hauses ist eine befestigte Höhenburg im Gebirge nahe Craithglyn, umgeben von Steinbrüchen, Minenschächten und weit verzweigten Stollensystemen.\n\nZum Besitz und Verbindungen gehören:\n\nEdelsteinminen Erzbergwerke Gold- und Silberschmieden Juwelierwerkstätten Verbindungen zur Regenbogenschmiede Anteile an der großen Edelsteinmine Craithglyns ein repräsentatives Herrenhaus in Gwynthor\n\nDer größte Teil des Einkommens stammt aus dem Edelsteinhandel, der Schmuckherstellung sowie der Verarbeitung kostbarer Metalle.",
    "cultureReligion": "Die Loer gehören der Alerischen Kirche an und pflegen eine enge Verbindung zur Regenbogenschmiede. Weitere Einzelheiten folgen.",
    "conflictsAlliances": "Als Vasallen stehen die Loer in enger Loyalität zum Ritterfürstenhaus Wyrm und pflegen gute Beziehungen zum Grafenhaus Draig.\n\nIhre bedeutendste Rivalität besteht mit Haus Rhyddid.\n\nWährend die Loer für Reichtum, Bergbau und wirtschaftliche Stärke stehen, verkörpert Haus Rhyddid eher Bodenständigkeit, Wehrhaftigkeit und den Schutz der Grenzlande. Zwischen beiden Häusern bestehen seit Generationen Konkurrenz um Einfluss im Hause Wyrm, um Verwaltungsämter und um wirtschaftliche Vorherrschaft.\n\nOffene Feindschaft herrscht selten, doch politische Intrigen, Handelskonkurrenz und prestigeträchtige Wettstreite gehören beinahe zum Alltag.",
    "values": "Die Leitsätze des Hauses lauten:\n\nWohlstand ist die Frucht kluger Arbeit. Schönheit ist Ausdruck göttlicher Ordnung. Ein Edelstein gewinnt seinen Wert erst durch den Schliff. Reichtum verpflichtet zu Verantwortung. Handwerk und Rittertum ergänzen einander.\n\nFür einen Loer ist eine makellose Klinge ebenso ehrenvoll wie ein makellos geschliffener Edelstein. Beides zeugt von Geduld, Disziplin und dem Streben nach Perfektion.",
    "court": "Überlieferte Personen und Aufgaben. Nicht belegte Angaben bleiben offen.",
    "familyTree": "Die Hausbio öffnet sich über das Wappen im Stammbaum. Personen und Verbindungen sind in der Familienakte verzeichnet.",
    "historicalFigures": "Folgt …"
  },
  "sectionTitles": {
    "knighthood": "4. Rittertum"
  },
  "images": {
    "haus-wappen": {
      "src": "../Stammbäume/assets/images/houses/Llamreis Ankunft/haus-loer.png",
      "alt": "Wappen von Haus Loer",
      "format": "square"
    },
    "haus-hauptbild": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Llamreis_Ankunft/Haus_Loer/assets/hausmotiv.png",
      "alt": "Hausmotiv · Haus Loer",
      "format": "portrait",
      "maxHeight": 580
    },
    "haus-banner": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Llamreis_Ankunft/Haus_Wyrm/assets/herrschaftsbanner.png",
      "href": "../Kontinente/Estryll/Königreich Cenyr/Grafschaft Celtigerns Wacht/Herrschaft der Wyrm/Herrschaft der Wyrm.html",
      "alt": "Herrschaftsbanner von Herrschaft der Wyrm",
      "format": "square"
    },
    "hof-founder-1": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-loer&mode=view&person=cadfarch-loer",
      "alt": "Cadfarch Loer",
      "format": "portrait"
    },
    "hof-heads-1": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-loer&mode=view&person=cadfarch-loer",
      "alt": "Cadfarch Loer",
      "format": "portrait"
    },
    "hof-heads-2": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-loer&mode=view&person=maddocc-loer",
      "alt": "Maddocc Loer",
      "format": "portrait"
    },
    "hof-heads-3": {
      "src": "../Stammbäume/assets/images/portraits/haus-loer/eurgain-loer.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-loer&mode=view&person=eurgain-loer",
      "alt": "Eurgain Loer",
      "format": "portrait"
    },
    "hof-heirs-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-loer/ynyrion-loer.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-loer&mode=view&person=ynyrion-loer",
      "alt": "Ynyrion Loer",
      "format": "portrait"
    },
    "hof-heirs-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-loer/aeron-loer.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-loer&mode=view&person=aeron-loer",
      "alt": "Aeron Loer",
      "format": "portrait"
    }
  },
  "court": {
    "groups": [
      {
        "id": "founder",
        "title": "Gründer",
        "entries": [
          {
            "name": "Cadfarch Loer",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-loer&mode=view&person=cadfarch-loer",
            "imageKey": "hof-founder-1"
          }
        ]
      },
      {
        "id": "heads",
        "title": "Oberhauptfolge · Haus Loer",
        "note": "Überlieferte Oberhäupter. Zeitangaben werden nur übernommen, soweit sie belegt sind.",
        "entries": [
          {
            "name": "Cadfarch Loer",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-loer&mode=view&person=cadfarch-loer",
            "imageKey": "hof-heads-1"
          },
          {
            "name": "Maddocc Loer",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-loer&mode=view&person=maddocc-loer",
            "imageKey": "hof-heads-2"
          },
          {
            "name": "Eurgain Loer",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-loer&mode=view&person=eurgain-loer",
            "imageKey": "hof-heads-3"
          }
        ]
      },
      {
        "id": "heirs",
        "title": "Erbfolge",
        "entries": [
          {
            "name": "Ynyrion Loer",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-loer&mode=view&person=ynyrion-loer",
            "imageKey": "hof-heirs-1"
          },
          {
            "name": "Aeron Loer",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-loer&mode=view&person=aeron-loer",
            "imageKey": "hof-heirs-2"
          }
        ]
      }
    ],
    "cadets": []
  },
  "figures": {
    "heading": "11. Historische Figuren",
    "tableTitle": "Persönlichkeiten des Hauses",
    "entries": []
  },
  "familyTreeEmbed": {
    "src": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-loer&mode=view",
    "title": "Stammbaum von Haus Loer"
  },
  "trivia": [
    "Folgt …"
  ]
};
