// Generated by scripts/build-house-content.mjs. Edit haus.content.mjs instead.
window.HAEUSER_DATA = {
  "meta": {
    "id": "haus-taranvyr",
    "title": "Haus Taranvyr – Aleria",
    "type": "Ritterhaus",
    "status": "Active",
    "template": "kleinehaeuser",
    "storage": {
      "document": "haus-taranvyr"
    }
  },
  "name": "Haus Taranvyr",
  "hierarchy": [
    {
      "type": "Sammlung",
      "name": "Familien Häuser und Clans",
      "slug": "familien-hauser-und-clans"
    },
    {
      "type": "Kontinent",
      "name": "Estryll",
      "slug": "estryll"
    },
    {
      "type": "Königreich",
      "name": "Cenyr",
      "slug": "cenyr"
    },
    {
      "type": "Grafschaft",
      "name": "Celtigerns Wacht",
      "slug": "celtigerns-wacht"
    },
    {
      "type": "Region",
      "name": "Gwendolyns Ufer",
      "slug": "gwendolyns-ufer"
    },
    {
      "type": "Sitz",
      "name": "Abergwint",
      "slug": "abergwint"
    },
    {
      "type": "Haus",
      "name": "Haus Taranvyr",
      "slug": "haus-taranvyr"
    }
  ],
  "layout": "responsive",
  "classification": {
    "category": "Familien Häuser und Clans",
    "houseType": "Ritterhaus",
    "scale": "Ritterhaus",
    "parentHouseId": "",
    "rootHouseId": "haus-taranvyr",
    "territoryId": "baronie-gwendolyns-ufer"
  },
  "profile": {
    "highestTitle": "Ritterherr",
    "rank": "Ritterherr",
    "houseType": "Ritterhaus",
    "motto": "In Treue wachen wir.",
    "quoteAuthor": "Kenyon Taranvyr",
    "seat": "Abergwint",
    "affiliation": "Haus Gwyvern",
    "liege": "Haus Gwyvern",
    "patron": "Haus Gwyvern",
    "knightingPatron": "Haus Draig",
    "troopStrength": "",
    "tiarna": "",
    "kerns": "",
    "fleet": "",
    "founding": "",
    "milestoneOne": "",
    "milestoneTwo": "",
    "people": "Cenyri",
    "wealth": "Beschaulich",
    "religion": "Alerische Kirche",
    "patronDeities": "Knecht, Streiter, Nimue",
    "origin": "Rhydian Taranvyr",
    "cadetBranches": "",
    "allies": "Gwyvern, Draig, Tawelgar",
    "enemies": ""
  },
  "profileLabels": {
    "tiarna": "Ritter",
    "kerns": "Knechte"
  },
  "showMotto": true,
  "sections": {
    "overview": "Das Haus Taranvyr entstammt der Stadt Abergwint, dem Herzen der Baronie Gwendolyns Ufer.\n\nObwohl es zu den kleineren Ritterhäusern zählt, genießt es großes Vertrauen und hohes Ansehen. Als treue Gefolgsleute des Barons sind die Taranvyr bekannt für ihre Loyalität, Pflichtauffassung und Nähe zur Bevölkerung. Wo ihre Banner wehen, dort finden die Menschen Schutz – nicht nur in Abergwint, sondern in der gesamten Baronie.\n\nDie Taranvyr stammen ursprünglich aus Gwynthor und wurden einst dem Baron von Abergwint an die Seite gestellt, um ihn in seiner Herrschaft zu unterstützen. Diese Aufgabe prägt das Haus bis heute und ist fester Bestandteil seiner Identität geblieben.\n\nFür viele gelten die Taranvyr als das erste Ritterhaus Abergwints. Gemeint ist damit weniger ein formeller Rang als vielmehr ihr besonderer Status des Vertrauens: Wann immer es um Schutz, Ordnung oder entscheidende Aufgaben geht, verlässt sich der Baron gewöhnlich zuerst auf sie. Ihr Ruf ist untadelig und reicht weit über die Grenzen der Baronie hinaus – ja, selbst in der gesamten Grafschaft spricht man fast ausschließlich mit Anerkennung von ihnen.\n\nIn der Gegenwart ist das Haus größer und einflussreicher als je zuvor. Über die Jahre sind zahlreiche Mitglieder hinzugekommen, und mehrere Taranvyr wurden vom Baron zu Lehenswarten wichtiger Ortschaften ernannt.\n\nZudem nehmen sie eine zentrale Rolle innerhalb der Truppen von Abergwint und der gesamten Baronie ein und tragen maßgeblich zu deren Sicherheit und Stabilität bei.",
    "history": "Die Taranvyr führen ihren Namen auf Rhydian Taranvyr zurück, einen einfachen, aber außergewöhnlich tapferen Ritter des Hauses Draig. Er war ein enger Freund jenes Mannes, der lange vor der Gründung des Hauses Gwyvern als Statthalter nach Abergwint entsandt wurde. In dieser frühen Zeit war Rhydian nicht nur Hauptmann, sondern auch Kamerad, Berater und Vertrauter des damaligen Barons. Durch seinen unermüdlichen Dienst und seine Loyalität verankerte er den Namen Taranvyr fest in der Baronie Gwendolyns Ufer, bis dieser nicht mehr aus ihr wegzudenken war.\n\nAls später das Haus Gwyvern als Kadettenhaus der Draig gegründet und zu den Baronen von Gwendolyns Ufer erhoben wurde, blieb die Treue der Taranvyr ungebrochen. Mit derselben Hingabe, mit der sie zuvor den Draig gedient hatten, stellten sie sich nun in den Dienst der neuen Barone und bewahrten so ihre Rolle als verlässliche Stütze der Herrschaft.\n\nIm Laufe der Geschichte brachte das Haus viele bedeutende Ritter und angesehene Namen hervor. Besonders hervorzuheben ist Kenyon Taranvyr, der über Jahrzehnte hinweg mehreren Baronen als Marschall diente. Er kämpfte in zwei großen Kriegen und gilt bis heute als Sinnbild für Tapferkeit, Pflichtbewusstsein und unerschütterliche Loyalität – Eigenschaften, die das Haus Taranvyr bis in die Gegenwart prägen.",
    "traditions": "Die Taranvyr sind ein Ritterhaus durch und durch. Nur selten schlagen Mitglieder der Familie einen anderen Lebensweg ein oder sehen ihre Berufung außerhalb des ritterlichen Dienstes. Kampf, Pflicht und Schutz sind tief in ihrer Identität verankert und werden von Generation zu Generation weitergegeben.\n\nBesonders bekannt sind die Taranvyr für ihre Teulu-Schwertkämpfer und die große Sorgfalt, mit der deren Ausbildung gepflegt wird. Tradition, Disziplin und persönliche Weitergabe von Wissen spielen dabei eine zentrale Rolle. Diese Herangehensweise hat ihnen den Ruf eingebracht, nicht nur verlässliche Krieger, sondern auch vorbildliche Ausbilder hervorzubringen.\n\nSeit jeher bekleiden Mitglieder des Hauses wichtige Positionen innerhalb der Baronie und der Stadt Abergwint. Häufig dienen sie als Hauptmänner, Truppführer oder gar als Marschall des Barons selbst. Die bedeutendste Wachgarnison Abergwints steht in der Regel unter dem Kommando eines Taranvyr – ein Zeichen des besonderen Vertrauens, das man dem Haus entgegenbringt.",
    "knighthood": "Folgt …",
    "succession": "Folgt …",
    "holdings": "Die Burg der Taranvyr steht innerhalb der Mauern von Abergwint selbst und zählt dort zu den größeren Sitzen der einfachen Ritterhäuser. Trotz ihrer Größe verfügt das Haus jedoch weder über weitläufige Ländereien noch über ein eigenes, klar umrissenes Wirtschaftsfeld, wie es bei manch anderem Adelshaus der Fall ist.\n\nStattdessen treten die Taranvyr vor allem als Grundbesitzer in Erscheinung. Innerhalb Abergwints besitzen sie mehrere Grundstücke und Häuser, die sie an Tavernenwirte, Handwerker oder Kaufleute verpachten. Auch außerhalb der Stadt gehören ihnen kleinere Ländereien, die an Bauern vergeben werden. Aus diesen Pachteinnahmen bestreitet das Haus den Großteil seines Unterhalts.\n\nDarüber hinaus ist den Taranvyr seit Generationen die größte Garnison Abergwints anvertraut. Die Verantwortung für deren Organisation, Ausbildung und Einsatz liegt faktisch in ihren Händen – ein weiteres Zeichen des tiefen Vertrauens, das Stadt und Baron dem Haus entgegenbringen.",
    "cultureReligion": "Wie die meisten Cenyri bekennen sich auch die Taranvyr zur Alerischen Kirche. Ihr Glaube ist fest verwurzelt und Teil ihres Alltags, ohne dabei je aufdringlich oder demonstrativ zu sein. Besonders verehren sie den Knecht, den Gott der Arbeit, der Aufrichtigkeit und des Fleißes, dessen Werte sie in ihrem täglichen Handeln verkörpern. Ebenso gilt ihre Achtung dem Streiter, dem Gott des Krieges, der Ehre und der Pflicht, dessen Lehren ihr ritterliches Selbstverständnis prägen. Auch Nimue, die Dame der See, wird als Vorbild für Reinheit und Güte hoch geschätzt.\n\nDie Taranvyr gelten als gottesfürchtige, treue und verlässliche Kirchgänger. Dennoch hat bislang kein Mitglied des Hauses einen direkten Weg in den Klerus als Priester oder geweihter Kleriker eingeschlagen. Stattdessen sehen sie ihre Aufgabe darin, den Glauben durch Schutz und Ordnung zu bewahren.\n\nBesonders wichtig ist es dem Haus, dafür Sorge zu tragen, dass Feste, Zeremonien und der allgemeine Kirchgang für alle Gläubigen sicher und geordnet ablaufen können. In dieser stillen, dienenden Rolle verstehen die Taranvyr ihren Glauben nicht als Predigt, sondern als Pflicht gegenüber Gemeinschaft und Kirche.",
    "conflictsAlliances": "Die Taranvyr sind seit jeher treue Ritter des Hauses Gwyvern und zuvor auch des Hauses Draig. Ihre Loyalität gilt dem Lehnsherrn, dem sie dienen, und nur selten schlägt ein Mitglied des Hauses einen anderen Weg oder stellt sich unter ein fremdes Banner. Beständigkeit und Treue gelten ihnen als höchste Tugenden.\n\nEigentliche Feinde kennen die Taranvyr nicht. Als Gegner betrachten sie allein jene, die Ordnung und Recht untergraben oder die Sicherheit der Bevölkerung gefährden. Gegen solche Bedrohungen richten sich ihr Schwert und ihre Pflicht – nicht aus Hass, sondern aus Verantwortung.\n\nInnerhalb der Ritterhäuser von Abergwint und der gesamten Baronie Gwendolyns Ufer genießen die Taranvyr zahlreiche Fürsprecher. Ihr guter Ruf bringt jedoch auch vereinzelt Neid mit sich, der nicht immer offen ausgesprochen wird. Eine besondere und seit Langem bestehende Freundschaft verbindet das Haus Taranvyr mit dem Haus Tawelgar, deren Bande von gegenseitigem Respekt und gewachsener Verlässlichkeit geprägt sind.",
    "values": "Das Haus Taranvyr lebt nach den festen Werten von Mut, Loyalität und Pflichtbewusstsein. Diese Tugenden bestimmen nicht nur ihr Handeln, sondern auch ihr Selbstverständnis. Die Taranvyr sehen es als ihre Aufgabe an, die Einwohner von Abergwint ebenso zu schützen wie die Menschen der gesamten Baronie Gwendolyns Ufer.\n\nDer Schutz der Heimat und die Ehre des Hauses stehen für sie an oberster Stelle. Jedes Mitglied wächst mit dem Bewusstsein auf, dass Sicherheit und Ordnung nicht selbstverständlich sind, sondern bewahrt werden müssen. Für den Wohlstand und die Stabilität Gwendolyns Ufers sind die Taranvyr bereit, Opfer zu bringen, wenn es die Pflicht erfordert.\n\nVor allem aber ist es die Loyalität, für die das Haus steht wie für nichts anderes. Sie bildet den Kern ihres Handelns, ihrer Geschichte und ihres Rufes. In dieser unerschütterlichen Treue liegt die wahre Identität der Taranvyr – gestern, heute und auch für kommende Generationen.",
    "court": "Überlieferte Oberhäupter, Erben und Aufgaben. Unbekannte Angaben bleiben offen.",
    "familyTree": "Die Hausbio öffnet sich über das Wappen im Stammbaum. Personen und Verbindungen sind in der Familienakte verzeichnet.",
    "historicalFigures": "Überlieferte Persönlichkeiten des Hauses."
  },
  "sectionTitles": {
    "knighthood": "4. Rittertum"
  },
  "images": {
    "haus-wappen": {
      "src": "../Stammbäume/assets/images/houses/Gwendolyns Ufer/Ritterliche/Taranvyr.png",
      "alt": "Wappen von Haus Taranvyr",
      "format": "square"
    },
    "haus-hauptbild": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Gwendolyns_Ufer/Haus_Taranvyr/assets/hausmotiv.png",
      "alt": "Hausmotiv · Haus Taranvyr",
      "format": "portrait",
      "maxHeight": 580
    },
    "haus-banner": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Gwendolyns_Ufer/Haus_Gwyvern/assets/herrschaftsbanner.png",
      "href": "../Kontinente/Estryll/Königreich Cenyr/Grafschaft Celtigerns Wacht/Baronie Gwendolyns Ufer/Baronie Gwendolyns Ufer.html",
      "alt": "Herrschaftsbanner von Baronie Gwendolyns Ufer",
      "format": "square"
    },
    "hof-founder-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-taranvyr/rhydian-taranvyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=rhydian-taranvyr",
      "alt": "Rhydian Taranvyr",
      "format": "portrait"
    },
    "hof-heads-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-taranvyr/rhydian-taranvyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=rhydian-taranvyr",
      "alt": "Rhydian Taranvyr",
      "format": "portrait"
    },
    "hof-heads-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-gwyvern/kenyon-taranvyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=kenyon-taranvyr",
      "alt": "Kenyon Taranvyr",
      "format": "portrait"
    },
    "hof-heirs-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-taranvyr/hywel-taranvyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=hywel-taranvyr",
      "alt": "Hywel Taranvyr",
      "format": "portrait"
    },
    "hof-heirs-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-taranvyr/powell-taranvyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=powell-taranvyr",
      "alt": "Powell Taranvyr",
      "format": "portrait"
    },
    "hof-heirs-3": {
      "src": "../Stammbäume/assets/images/portraits/haus-taranvyr/kane-taranvyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=kane-taranvyr",
      "alt": "Kane Taranvyr",
      "format": "portrait"
    },
    "hof-heirs-4": {
      "src": "../Stammbäume/assets/images/portraits/haus-taranvyr/marvo-taranvyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=marvo-taranvyr",
      "alt": "Marvo Taranvyr",
      "format": "portrait"
    },
    "hof-offices-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-taranvyr/fiannait-spouse-taranvyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=fiannait-spouse-taranvyr",
      "alt": "Fiannait",
      "format": "portrait"
    },
    "hof-offices-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-taranvyr/mervynne-spouse-taranvyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=mervynne-spouse-taranvyr",
      "alt": "Mervynne",
      "format": "portrait"
    },
    "hof-offices-3": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Vogt nicht benannt",
      "format": "portrait"
    },
    "haus-figur-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-taranvyr/rhydian-taranvyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=rhydian-taranvyr",
      "alt": "Rhydian Taranvyr",
      "format": "portrait"
    },
    "haus-figur-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-gwyvern/kenyon-taranvyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=kenyon-taranvyr",
      "alt": "Kenyon Taranvyr",
      "format": "portrait"
    },
    "haus-figur-3": {
      "src": "../Stammbäume/assets/images/portraits/haus-taranvyr/hywel-taranvyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=hywel-taranvyr",
      "alt": "Hywel Taranvyr",
      "format": "portrait"
    },
    "haus-figur-4": {
      "src": "../Stammbäume/assets/images/portraits/haus-taranvyr/alestan-taranvyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=alestan-taranvyr",
      "alt": "Alestan Taranvyr",
      "format": "portrait"
    },
    "haus-figur-5": {
      "src": "../Stammbäume/assets/images/portraits/haus-taranvyr/brendan-taranvyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=brendan-taranvyr",
      "alt": "Brendan Taranvyr",
      "format": "portrait"
    },
    "haus-figur-6": {
      "src": "../Stammbäume/assets/images/portraits/haus-taranvyr/rhon-taranvyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=rhon-taranvyr",
      "alt": "Rhon Taranvyr",
      "format": "portrait"
    }
  },
  "court": {
    "groups": [
      {
        "id": "founder",
        "title": "Gründer",
        "entries": [
          {
            "name": "Rhydian Taranvyr",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=rhydian-taranvyr",
            "imageKey": "hof-founder-1"
          }
        ]
      },
      {
        "id": "heads",
        "title": "Oberhauptfolge · Haus Taranvyr",
        "note": "Überlieferte Oberhäupter; Lücken und nicht belegte Amtszeiten bleiben offen.",
        "entries": [
          {
            "name": "Rhydian Taranvyr",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=rhydian-taranvyr",
            "imageKey": "hof-heads-1"
          },
          {
            "name": "Kenyon Taranvyr",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=kenyon-taranvyr",
            "imageKey": "hof-heads-2"
          }
        ]
      },
      {
        "id": "heirs",
        "title": "Erbfolge",
        "entries": [
          {
            "name": "Hywel Taranvyr",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=hywel-taranvyr",
            "imageKey": "hof-heirs-1"
          },
          {
            "name": "Powell Taranvyr",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=powell-taranvyr",
            "imageKey": "hof-heirs-2"
          },
          {
            "name": "Kane Taranvyr",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=kane-taranvyr",
            "imageKey": "hof-heirs-3"
          },
          {
            "name": "Marvo Taranvyr",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=marvo-taranvyr",
            "imageKey": "hof-heirs-4"
          }
        ]
      },
      {
        "id": "offices",
        "title": "Hofämter",
        "entries": [
          {
            "name": "Fiannait",
            "role": "Kämmerin / Schatzmeisterin",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=fiannait-spouse-taranvyr",
            "imageKey": "hof-offices-1"
          },
          {
            "name": "Mervynne",
            "role": "Rechtsprecherin",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view&person=mervynne-spouse-taranvyr",
            "imageKey": "hof-offices-2"
          },
          {
            "name": "Nicht benannt",
            "role": "Vogt",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-3"
          }
        ]
      }
    ],
    "cadets": []
  },
  "figures": {
    "heading": "11. Historische Figuren",
    "tableTitle": "Persönlichkeiten des Hauses",
    "entries": [
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Persönlichkeit des Hauses",
        "name": "Rhydian Taranvyr",
        "description": "Der Gründer des Hauses.",
        "imageKey": "haus-figur-1"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Persönlichkeit des Hauses",
        "name": "Kenyon Taranvyr",
        "description": "Er war früher der Marschall des Barons, Kriegsheld und heutiger Waffenmeister des Barons.",
        "imageKey": "haus-figur-2"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Persönlichkeit des Hauses",
        "name": "Hywel Taranvyr",
        "description": "Er war seines Vaters Nachfolger als Marschall des Barons. Vor einem Jahr gab er dieses Amt an Gwynnan Gwyvern ab und kümmert sich seitdem um die Garnison von Abergwint.",
        "imageKey": "haus-figur-3"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Persönlichkeit des Hauses",
        "name": "Alestan Taranvyr",
        "description": "Er ist der Hauptmann der Wache in Craithfael.",
        "imageKey": "haus-figur-4"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Persönlichkeit des Hauses",
        "name": "Brendan Taranvyr",
        "description": "Er ist Lehenswart in Castell Rhewglyn.",
        "imageKey": "haus-figur-5"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Persönlichkeit des Hauses",
        "name": "Rhon Taranvyr",
        "description": "Er ist Lehenswart in Glasdraeth.",
        "imageKey": "haus-figur-6"
      }
    ]
  },
  "familyTreeEmbed": {
    "src": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-taranvyr&mode=view",
    "title": "Stammbaum von Haus Taranvyr"
  },
  "trivia": [
    "Folgt …"
  ]
};
