// Generated by scripts/build-house-content.mjs. Edit haus.content.mjs instead.
window.HAEUSER_DATA = {
  "meta": {
    "id": "haus-bleiddorn",
    "title": "Haus Bleiddorn – Aleria",
    "type": "Ritterhaus",
    "status": "Active",
    "template": "kleinehaeuser",
    "storage": {
      "document": "haus-bleiddorn"
    }
  },
  "name": "Haus Bleiddorn",
  "hierarchy": [
    {
      "type": "Sammlung",
      "name": "Familien Häuser und Clans",
      "slug": "familien-hauser-und-clans"
    },
    {
      "type": "Kontinent",
      "name": "Estryll",
      "slug": "estryll"
    },
    {
      "type": "Königreich",
      "name": "Cenyr",
      "slug": "cenyr"
    },
    {
      "type": "Grafschaft",
      "name": "Celtigerns Wacht",
      "slug": "celtigerns-wacht"
    },
    {
      "type": "Region",
      "name": "Llamreis Ankunft",
      "slug": "llamreis-ankunft"
    },
    {
      "type": "Sitz",
      "name": "Gwynthor",
      "slug": "gwynthor"
    },
    {
      "type": "Haus",
      "name": "Haus Bleiddorn",
      "slug": "haus-bleiddorn"
    }
  ],
  "layout": "responsive",
  "classification": {
    "category": "Familien Häuser und Clans",
    "houseType": "Ritterhaus",
    "scale": "Ritterhaus",
    "parentHouseId": "",
    "rootHouseId": "haus-bleiddorn",
    "territoryId": "celtigerns-wacht"
  },
  "profile": {
    "highestTitle": "Ritterherr",
    "rank": "Ritterherr",
    "houseType": "Ritterhaus",
    "motto": "",
    "quoteAuthor": "",
    "seat": "Gwynthor",
    "affiliation": "Haus Draig",
    "liege": "Haus Draig",
    "patron": "",
    "knightingPatron": "",
    "troopStrength": "",
    "tiarna": "",
    "kerns": "",
    "fleet": "",
    "founding": "",
    "milestoneOne": "",
    "milestoneTwo": "",
    "people": "",
    "wealth": "",
    "religion": "",
    "patronDeities": "",
    "origin": "",
    "cadetBranches": "",
    "allies": "",
    "enemies": ""
  },
  "profileLabels": {
    "tiarna": "Ritter",
    "kerns": "Knechte"
  },
  "showMotto": false,
  "sections": {
    "overview": "Das ritterliche Herrenhaus Bleiddorn entstand durch Hrolfs Auswanderung aus Aldrimar nach Cenyr. In Gwynthor unter Celtigerns Wacht blüht der aus Clan Wolfshorn hervorgegangene Familienzweig neu auf. Weitere Inhalte folgen.",
    "history": "Folgt …",
    "traditions": "Folgt …",
    "knighthood": "Folgt …",
    "succession": "Folgt …",
    "holdings": "Folgt …",
    "cultureReligion": "Folgt …",
    "conflictsAlliances": "Folgt …",
    "values": "Folgt …",
    "court": "Folgt …",
    "familyTree": "Die Hausbio öffnet sich über das Wappen im Stammbaum. Personen und Verbindungen sind in der Familienakte verzeichnet.",
    "historicalFigures": "Folgt …"
  },
  "sectionTitles": {
    "knighthood": "4. Rittertum"
  },
  "images": {
    "haus-wappen": {
      "src": "../Stammbäume/assets/images/houses/Llamreis Ankunft/haus-bleiddorn.png",
      "alt": "Wappen von Haus Bleiddorn",
      "format": "square"
    },
    "haus-hauptbild": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Llamreis_Ankunft/Haus_Bleiddorn/assets/krieger-g850v6f.png",
      "alt": "Krieger von Haus Bleiddorn",
      "format": "portrait",
      "maxHeight": 580
    },
    "haus-banner": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Haus_Draig/assets/gwynthor.png",
      "href": "../Kontinente/Estryll/Königreich Cenyr/Grafschaft Celtigerns Wacht/Grafschaft Celtigerns Wacht.html",
      "alt": "Herrschaftsbanner von Celtigerns Wacht",
      "format": "square"
    }
  },
  "court": {
    "groups": [],
    "cadets": []
  },
  "figures": {
    "heading": "11. Historische Figuren",
    "tableTitle": "Persönlichkeiten des Hauses",
    "entries": []
  },
  "familyTreeEmbed": {
    "src": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-bleiddorn&mode=view",
    "title": "Stammbaum von Haus Bleiddorn"
  },
  "trivia": [
    "Folgt …"
  ]
};
