// Generated by scripts/build-house-content.mjs. Edit haus.content.mjs instead.
window.HAEUSER_DATA = {
  "meta": {
    "id": "haus-garrael",
    "title": "Haus Garrael – Aleria",
    "type": "Ritterhaus",
    "status": "Active",
    "template": "kleinehaeuser",
    "storage": {
      "document": "haus-garrael"
    }
  },
  "name": "Haus Garrael",
  "hierarchy": [
    {
      "type": "Sammlung",
      "name": "Familien Häuser und Clans",
      "slug": "familien-hauser-und-clans"
    },
    {
      "type": "Kontinent",
      "name": "Estryll",
      "slug": "estryll"
    },
    {
      "type": "Königreich",
      "name": "Cenyr",
      "slug": "cenyr"
    },
    {
      "type": "Grafschaft",
      "name": "Celtigerns Wacht",
      "slug": "celtigerns-wacht"
    },
    {
      "type": "Region",
      "name": "Camruisge",
      "slug": "camruisge"
    },
    {
      "type": "Sitz",
      "name": "Aberllan",
      "slug": "aberllan"
    },
    {
      "type": "Haus",
      "name": "Haus Garrael",
      "slug": "haus-garrael"
    }
  ],
  "layout": "responsive",
  "classification": {
    "category": "Familien Häuser und Clans",
    "houseType": "Ritterhaus",
    "scale": "Ritterhaus",
    "parentHouseId": "",
    "rootHouseId": "haus-garrael",
    "territoryId": "insel-camruisge"
  },
  "profile": {
    "highestTitle": "Ritterherr",
    "rank": "Ritterherr",
    "houseType": "Ritterhaus",
    "motto": "",
    "quoteAuthor": "",
    "seat": "",
    "affiliation": "Haus Draig",
    "liege": "Haus Draig",
    "patron": "Haus Draig",
    "knightingPatron": "Ein früherer Graf aus dem Haus Draig",
    "troopStrength": "",
    "tiarna": "",
    "kerns": "",
    "fleet": "",
    "founding": "",
    "milestoneOne": "",
    "milestoneTwo": "",
    "people": "Cenyri",
    "wealth": "Beschaulich",
    "religion": "Alerische Kirche",
    "patronDeities": "",
    "origin": "Aledd Garrael",
    "cadetBranches": "",
    "allies": "",
    "enemies": ""
  },
  "profileLabels": {
    "tiarna": "Ritter",
    "kerns": "Knechte"
  },
  "showMotto": false,
  "sections": {
    "overview": "Haus Garrael ist ein altes, ritterliches Geschlecht aus Gwynthor, dessen Stellung weniger auf Ruhm oder Reichtum beruht als auf Vertrauen. Sie gelten als nüchtern, pflichtbewusst und wenig geneigt zu lokalen Machtspielen – genau deshalb wurden sie ausgewählt.\n\nAuf Camruisge fungieren die Garrael als dauerhafte Lehenswarte und neutrale Ordnungsmacht über die Stadt Aberllan im Norden der Insel. Ihr Auftrag ist nicht Expansion, sondern Stabilität: Schlichten, überwachen, durchsetzen. Sie herrschen nicht aus Eigeninteresse, sondern im Namen einer übergeordneten Ordnung, und genau das macht ihre Präsenz für viele akzeptabel – und für andere unerträglich.\n\nHaus Garrael ist ein seefahrendes Ritterhaus und dauerhafter Lehenswart der Nordseite Camruisges, dessen Macht auf Pflicht, Ordnung und der ununterbrochenen Verteidigung von Küste und Bevölkerung beruht. Im Norden der Insel sind sie höchste Autorität und Garant des Friedens, nach außen jedoch bewusst zurückhaltend – stark durch Konzentration, nicht durch Ausdehnung.",
    "history": "Die Entsendung des Hauses Garrael nach Camruisge war die direkte Folge jahrelanger innerstädtischer Fehden in Aberllan. Bürgerliche Familien, Handelsinteressen und lokale Würdenträger rangen wiederholt um Einfluss, Kontrolle über Abgaben und politische Vorherrschaft. Diese Konflikte eskalierten zeitweise offen und bedrohten den fragilen Frieden der Insel.\n\nUrsprünglich griff Haus Draig selbst ein und entsandte einzelne Familienmitglieder zur Schlichtung. Doch mit wachsender Bedeutung des Hauses auf dem Festland wurde diese Praxis zunehmend kostspielig, riskant und ineffizient. Jeder neue Streit auf Camruisge band Ressourcen, erzeugte diplomatische Reibung und lenkte von wichtigeren Verpflichtungen ab.\n\nDie Lösung war ein bewusster Schnitt: Haus Draig setzte ein externes, loyales und lokal unverstricktes Ritterhaus als dauerhafte Lehenswarte ein. Die Wahl fiel auf die Garrael, da sie weder verwandtschaftlich noch wirtschaftlich mit den Parteien Aberllans verbunden waren und sich bereits zuvor als verlässliche Vollstrecker fremder Interessen bewährt hatten.\n\nSeit ihrer Einsetzung halten die Garrael die Kontrolle über Aberllan aufrecht. Offene Fehden wurden unterbunden, rivalisierende Ansprüche eingefroren und die Stadt einer klaren, wenn auch strengen Ordnung unterstellt. Ihre Präsenz hat den offenen Konflikt beendet – aber nicht jede Unzufriedenheit.\n\nHaus Garrael ist damit kein geliebter Herr, sondern ein notwendiger: akzeptiert, weil das Chaos ohne sie schlimmer wäre.",
    "traditions": "Haus Garrael versteht sich seit Generationen nicht als Fremdherrscher, sondern als Inselhaus. Über viele Jahrhunderte hinweg trugen sie die Verantwortung für die Nordseite Camruisges und wuchsen dabei untrennbar mit Land, Küste und Bevölkerung zusammen. Ihre Stellung gründet weniger auf formaler Macht als auf Gewohnheit, Verlässlichkeit und dem stillen Wissen, dass sie geblieben sind, während andere kamen und gingen.\n\nDer Süden der Insel wird im Namen Leitheachs von ihren langjährigen Verbündeten, den Salach, verwaltet. Zwischen beiden Häusern besteht ein altes, gewachsenes Bündnis, getragen von gegenseitigem Respekt und klarer Aufgabenteilung. Streitigkeiten blieben über die Jahrhunderte nicht aus, doch wurden sie fast immer durch Verhandlung, Abwägung und gegenseitige Zugeständnisse beigelegt. Blutvergießen gilt auf Camruisge als Zeichen von Versagen – nicht von Stärke.\n\nDie Kerntraditionen der Garrael sind Seefahrt, Fischerei und Inselverteidigung. Sie sehen sich nicht als Landritter, sondern als Küstenherren: wachsam gegenüber dem Meer, vertraut mit Strömungen, Stürmen und Schiffen. Viele Angehörige des Hauses dienen zeitweise selbst zur See, führen Patrouillenboote, schützen Handelsrouten oder überwachen die Küstenlinien der Insel.\n\nIn ihrem Selbstverständnis sind die Garrael weniger Herren als Wächter. Sie begreifen sich als Schutzschild Camruisges und als erste Verteidigungslinie gegen äußere Bedrohungen. Diese Haltung prägt ihr Auftreten: nüchtern, diszipliniert, ohne Prunk – aber unnachgiebig, wenn die Sicherheit der Insel infrage steht.",
    "knighthood": "Folgt …",
    "succession": "Folgt …",
    "holdings": "Haus Garrael hält die volle Obrigkeit und Lehensherrschaft über die gesamte Nordseite Camruisges. Zu ihrem Herrschaftsgebiet zählen die Stadt Aberllan, zahlreiche Bauernhöfe und Einzelgehöfte, mehrere kleinere Siedlungspunkte sowie ein oder zwei ertragreiche Minenstandorte. Diese Besitzungen sichern dem Haus nicht nur wirtschaftliche Eigenständigkeit, sondern auch direkte Kontrolle über Versorgung, Abgaben und Infrastruktur des Nordens.\n\nInnerhalb Camruisges stellen die Garrael – neben dem Haus Salach im Süden – die höchste weltliche Autorität dar. Ihre Entscheidungen sind bindend, ihre Gerichtsbarkeit anerkannt, ihre Befehle durchsetzbar. Auf der Insel selbst existiert kein ritterliches Haus, das ihnen gleichgestellt wäre.\n\nEntgegen mancher Erwartung werden die Garrael von anderen ritterlichen Häusern nicht belächelt. Ihr Einfluss ist real, greifbar und dauerhaft – und damit wirkungsvoller als der vieler größerer Häuser des Festlands, deren Macht sich oft auf Titel und entfernte Lehen beschränkt. Die Garrael verfügen zwar nicht über ausgedehnte Besitzungen jenseits Camruisges, doch genau diese Konzentration macht sie stark: Ihre Macht ist lokal, geschlossen und unangefochten.\n\nAußerhalb der Insel spielen sie in der hohen Politik nur eine untergeordnete Rolle. Innerhalb Camruisges jedoch gelten sie als Maßstab, Ordnungsmacht und letzte Instanz. Wer hier etwas bewegen will, kommt an Haus Garrael nicht vorbei.",
    "cultureReligion": "Die Garrael sind fromme Anhänger der Alerischen Kirche.",
    "conflictsAlliances": "Haus Garrael unterhält ein festes Bündnis mit dem südlichen Haus Salach. Dieses wird durch Ehen, Mündelschaften und gegenseitige Schutzpflichten gestärkt. Nach außen treten beide Häuser geschlossen auf und sichern gemeinsam den Frieden Camruisges.\n\nZu ihren Oberherren, dem Haus Draig aus Gwynthor, stehen die Garrael in einem loyalen Vasallenverhältnis mit großer Eigenständigkeit in Inselangelegenheiten.\n\nKonflikte bestehen kaum mit anderen Adelshäusern, sondern vor allem mit Piraten und Kreaturen der See. Küstenangriffe, Überfälle auf Gehöfte und ständige Patrouillen binden einen Großteil ihrer Kräfte. Der Frieden der Insel wird durch permanente Wachsamkeit erkauft.",
    "values": "Haus Garrael steht für Pflicht, Beständigkeit und Schutz. Ihre Loyalität gilt weniger Titeln als der Verantwortung gegenüber Insel, Küste und Bevölkerung. Sie handeln nüchtern, halten Ordnung ohne Prunk und messen Stärke nicht an Ruhm, sondern an Verlässlichkeit.\n\nZusammenhalt, Disziplin und Wachsamkeit prägen ihr Selbstverständnis. Frieden gilt ihnen nicht als Zustand, sondern als Aufgabe, die täglich verteidigt werden muss.",
    "court": "Überlieferte Oberhäupter, Erben und Aufgaben. Unbekannte Angaben bleiben offen.",
    "familyTree": "Die Hausbio öffnet sich über das Wappen im Stammbaum. Personen und Verbindungen sind in der Familienakte verzeichnet.",
    "historicalFigures": "Folgt …"
  },
  "sectionTitles": {
    "knighthood": "4. Rittertum"
  },
  "images": {
    "haus-wappen": {
      "src": "../Stammbäume/assets/images/houses/Camruisge/haus-garrael.png",
      "alt": "Wappen von Haus Garrael",
      "format": "square"
    },
    "haus-hauptbild": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Camruisge/Haus_Garrael/assets/hausmotiv.png",
      "alt": "Hausmotiv · Haus Garrael",
      "format": "portrait",
      "maxHeight": 580
    },
    "haus-banner": {
      "src": "../Stammbäume/assets/images/regions/camruisge.png",
      "href": "../Kontinente/Estryll/Königreich Cenyr/Grafschaft Celtigerns Wacht/Insel Camruisge/Insel Camruisge.html",
      "alt": "Herrschaftsbanner von Insel Camruisge",
      "format": "square"
    },
    "hof-founder-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-garrael/aledd-garrael.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-garrael&mode=view&person=aledd-garrael",
      "alt": "Aledd Garrael",
      "format": "portrait"
    },
    "hof-heads-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-garrael/aledd-garrael.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-garrael&mode=view&person=aledd-garrael",
      "alt": "Aledd Garrael",
      "format": "portrait"
    },
    "hof-heads-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-garrael/lyonnel-garrael.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-garrael&mode=view&person=lyonnel-garrael",
      "alt": "Lyonnel Garrael",
      "format": "portrait"
    }
  },
  "court": {
    "groups": [
      {
        "id": "founder",
        "title": "Gründer",
        "entries": [
          {
            "name": "Aledd Garrael",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-garrael&mode=view&person=aledd-garrael",
            "imageKey": "hof-founder-1"
          }
        ]
      },
      {
        "id": "heads",
        "title": "Oberhauptfolge · Haus Garrael",
        "note": "Überlieferte Oberhäupter; Lücken und nicht belegte Amtszeiten bleiben offen.",
        "entries": [
          {
            "name": "Aledd Garrael",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-garrael&mode=view&person=aledd-garrael",
            "imageKey": "hof-heads-1"
          },
          {
            "name": "Lyonnel Garrael",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-garrael&mode=view&person=lyonnel-garrael",
            "imageKey": "hof-heads-2"
          }
        ]
      }
    ],
    "cadets": []
  },
  "figures": {
    "heading": "11. Historische Figuren",
    "tableTitle": "Persönlichkeiten des Hauses",
    "entries": []
  },
  "familyTreeEmbed": {
    "src": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-garrael&mode=view",
    "title": "Stammbaum von Haus Garrael"
  },
  "trivia": [
    "Folgt …"
  ]
};
