import { base, workspace, artifacts, artifact } from './browser-session.mjs';
import { join } from 'node:path';
import assert from 'node:assert/strict';
import { mkdir, readdir, readFile } from 'node:fs/promises';
import { command, evaluate, navigate, screenshot, errors, close } from './browser-session.mjs';
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
const set = (id, value) => evaluate(`{const field=document.getElementById(${JSON.stringify(id)});field.value=${JSON.stringify(value)};field.dispatchEvent(new Event('change',{bubbles:true}));}`);
const click = selector => evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
const waitBook = async () => {
  for (let n = 0; n < 100; n++) { if (await evaluate(`!!document.querySelector('[data-workshop-book][data-mode="book"] .book-flip') && !document.querySelector('[data-workshop-book]').hasAttribute('aria-busy')`)) return; await pause(100); }
  throw new Error(await evaluate(`JSON.stringify({message:document.querySelector('[data-role="message"]')?.textContent,status:document.querySelector('#status')?.textContent,errors:document.querySelector('[data-workshop-book]')?.outerHTML.slice(0,400)})`));
};
await command('Emulation.setDeviceMetricsOverride', { width: 1580, height: 1050, deviceScaleFactor: 1, mobile: false });
await navigate(base + '/AleriaAlmanach/DokumentenWerkstatt.html');
await set('doc-template', 'book'); await set('doc-font', "'EB Garamond'"); await set('doc-font-size', '19');
await set('doc-title', 'Chronik der vergessenen Wege'); await set('doc-width', '1120');
await waitBook();
assert.ok(await evaluate(`document.querySelectorAll('.book-flip .book-leaf').length >= 4`));
await screenshot(artifact('workshop-book.png'));
const original = await evaluate(`document.querySelector('[data-role="page-status"]').dataset.page`);
await click('[data-workshop-book] [data-action="next"]'); await pause(1100);
assert.notEqual(await evaluate(`document.querySelector('[data-role="page-status"]').dataset.page`), original);
await click('[data-action="article-view"]');
assert.equal(await evaluate(`document.querySelector('[data-workshop-book]').dataset.mode`), 'article');
await click('[data-action="book-view"]'); await waitBook();
await click('[data-action="close-book"]');
assert.equal(await evaluate(`document.querySelector('[data-workshop-book]').dataset.mode`), 'closed');
await click('[data-action="open-book"]'); await waitBook();
await command('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
await pause(800); await waitBook();
assert.equal(await evaluate(`document.querySelector('[data-role="mount"]').dataset.orientation`), 'portrait');
await evaluate(`document.querySelector('#preview-pane').scrollIntoView()`); await screenshot(artifact('workshop-book-mobile.png'));
await command('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'reduce' }] }); await pause(100);
assert.equal(await evaluate(`document.querySelector('[data-workshop-book]').dataset.mode`), 'article');
await command('Emulation.setEmulatedMedia', { features: [] });
await command('Emulation.setDeviceMetricsOverride', { width: 1580, height: 1050, deviceScaleFactor: 1, mobile: false });
await set('doc-slug', 'workshop-book-export'); await set('png-pages', 'all'); await set('png-scale', '1');
await mkdir(artifact('downloads'), { recursive: true });
await command('Browser.setDownloadBehavior', { behavior: 'allow', downloadPath: artifact('downloads') });
await click('[data-enhance-action="export-png"]');
for (let n = 0; n < 100 && !(await readdir(artifact('downloads'))).includes('workshop-book-export-buchseiten.zip'); n++) await pause(100);
assert.ok((await readdir(artifact('downloads'))).includes('workshop-book-export-buchseiten.zip'), await evaluate(`document.querySelector('#status').textContent`));
await click('[data-workshop-action="export-html"]');
for (let n = 0; n < 70 && !(await readdir(artifact('downloads'))).includes('workshop-book-export.html'); n++) await pause(100);
const html = await readFile(artifact('downloads/workshop-book-export.html'), 'utf8');
assert.ok(html.includes('StPageFlip')); assert.ok(html.includes('data-book-reader')); assert.ok(!html.includes('onclick='));
await command('Page.navigate', { url: base + '/.codex-temp/document-workshop/downloads/workshop-book-export.html' }); await pause(1200);
assert.equal(await evaluate(`document.querySelector('[data-book-reader]').dataset.mode`), 'book');
assert.ok(await evaluate(`document.querySelector('.book-flip').getBoundingClientRect().width > 400`));
await screenshot(artifact('workshop-standalone-book.png'));
await navigate(base + '/AleriaAlmanach/DokumentenWerkstatt.html');
await set('doc-template', 'wanted'); await set('doc-title', 'Gesucht: Der Rabenmann'); await set('doc-subtitle', 'Hinweise an die Wache am Nordtor');
await set('doc-author', 'Hauptmann der Stadtwache'); await set('doc-width', '820'); await set('doc-height', '1060');
await set('doc-font', "'EB Garamond'"); await set('doc-image-size', '180'); await set('doc-border', 'double');
await set('doc-image', base + '/Stammb%C3%A4ume/assets/images/portraits/haus-morforwyn/mapnimue.png');
await pause(500);
assert.equal(await evaluate(`document.querySelector('.wanted-banner')`), null);
assert.ok(!await evaluate(`document.querySelector('.wanted-poster').textContent.includes('Fahndung')`));
assert.ok(await evaluate(`!!document.querySelector('.wanted-sketch img') && !!document.querySelector('.wanted-seal-space')`));
assert.ok(await evaluate(`document.querySelector('.wanted-sketch').getBoundingClientRect().left > document.querySelector('.wanted-heading').getBoundingClientRect().left`));
await screenshot(artifact('workshop-poster.png'));
await command('Page.navigate', { url: base + '/Bestiarium/themen/wesen-des-infernalen/index.html' }); await pause(1000);
assert.equal(await evaluate(`document.querySelector('[data-book-reader]').dataset.mode`), 'book');
assert.equal(errors.length, 0, JSON.stringify(errors));
console.log('Bestiarium book engine, mobile, reduced motion, ZIP, standalone book, poster, and original Bestiarium passed'); close();
