import { base, workspace, artifacts, artifact } from './browser-session.mjs';
import { join } from 'node:path';
import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
import { command, evaluate, navigate, screenshot, errors, close } from './browser-session.mjs';
const workshop = base + '/AleriaAlmanach/DokumentenWerkstatt.html';
const pause = () => new Promise(resolve => setTimeout(resolve, 250));
const set = (id, value) => evaluate(`{const input=document.getElementById(${JSON.stringify(id)});input.value=${JSON.stringify(value)};input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));}`);
const click = selector => evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
await navigate(workshop);
await evaluate(`(async()=>{const {openDocumentRepository}=await import('/AleriaAlmanach/DokumentenWerkstatt/js/library/document-repository.js');await (await openDocumentRepository()).remove('werkstatt-smoke-test');})()`);
await set('doc-title', 'Die versiegelte Botschaft'); await set('doc-slug', 'werkstatt-smoke-test');
await set('doc-category', 'Prüfsammlung'); await set('doc-paper-edge', 'torn');
await set('doc-font', "'Karnrith Hochschnitt'");
await evaluate(`document.getElementById('doc-editor').innerHTML='<p>Bewahrt dieses Blatt. CH TH NG</p>';document.getElementById('doc-editor').dispatchEvent(new Event('input',{bubbles:true}));`);
await click('[data-enhance-action="translate"]');
assert.equal(await evaluate(`document.querySelector('[data-role="reading-panel"] .reading-text').textContent`), 'Bewahrt dieses Blatt. CH TH NG');
await click('[data-collection-action="queue"]'); await pause();
assert.equal(await evaluate(`document.querySelector('[data-role="queue-count"]').textContent`), '1 vorgemerkt');
await click('[data-tab="paper"]'); await pause();
await screenshot(artifact('workshop-paper.png'));
await navigate(workshop);
assert.equal(await evaluate(`document.querySelector('[data-role="queue-count"]').textContent`), '1 vorgemerkt');
await click('[data-tab="library"]'); await click('[data-library-action="edit"][data-id="werkstatt-smoke-test"]'); await pause();
assert.equal(await evaluate(`document.getElementById('doc-title').value`), 'Die versiegelte Botschaft');
assert.equal(await evaluate(`document.getElementById('doc-paper-edge').value`), 'torn');
await click('[data-library-action="publish"]'); await pause();
assert.equal(await evaluate(`document.querySelector('dialog').open`), true);
assert.match(await evaluate(`document.querySelector('[data-role="publish-summary"]').textContent`), /Die versiegelte Botschaft/);
await click('[data-role="publish-close"]');
await screenshot(artifact('workshop-library.png'));
const data = await evaluate(`(async()=>{ const {openDocumentRepository}=await import('/AleriaAlmanach/DokumentenWerkstatt/js/library/document-repository.js');const repo=await openDocumentRepository();const records=await repo.all();const meta=records.find(record=>record.id==='werkstatt-smoke-test').document;const {renderDocumentPng}=await import('/AleriaAlmanach/DokumentenWerkstatt/js/export/document-export.js'); const result=await renderDocumentPng(meta,{scale:3}); const blobUrl=URL.createObjectURL(result.blob);const image=new Image();image.src=blobUrl;await image.decode();const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);const corner=ctx.getImageData(0,0,1,1).data[3];URL.revokeObjectURL(blobUrl);return {width:result.width,height:result.height,corner,png:canvas.toDataURL()};})()`);
assert.equal(data.width, 2460); assert.ok(data.height >= 2340); assert.equal(data.corner, 0);
await writeFile(artifact('workshop-export.png'), Buffer.from(data.png.split(',')[1], 'base64'));
console.log('PNG', { width: data.width, height: data.height, cornerAlpha: data.corner });
const fontChecks = await evaluate(`(async()=>{const {PROJECT_FONTS}=await import('/AleriaAlmanach/DokumentenWerkstatt/js/fonts/font-catalog.js');const {ensureDocumentFont}=await import('/AleriaAlmanach/DokumentenWerkstatt/js/fonts/document-fonts.js');const results=[];for(const font of PROJECT_FONTS){await ensureDocumentFont({font:"'"+font.family+"'",fontSize:20});results.push(document.fonts.check('20px "'+font.family+'"'));}return results;})()`);
assert.equal(fontChecks.length, 8); assert.ok(fontChecks.every(Boolean));
const documentTree = await command('DOM.getDocument');
const fontInput = await command('DOM.querySelector', { nodeId: documentTree.root.nodeId, selector: '#custom-font-file' });
await command('DOM.setFileInputFiles', { nodeId: fontInput.nodeId, files: [join(workspace, 'Fonts/Faehrtenlaut-Font-1.000/Web/Faehrtenlaut-Regular.woff2')] });
await pause();
assert.equal(await evaluate(`document.getElementById('doc-font').value`), "'Workshop Custom'");
await click('[data-collection-action="save"]'); await pause();
await navigate(workshop);
await click('[data-library-action="edit"][data-id="werkstatt-smoke-test"]'); await pause();
assert.equal(await evaluate(`document.getElementById('custom-font-name').textContent`), 'Faehrtenlaut-Regular.woff2');
const sanitized = await evaluate(`(async()=>{const {sanitizeContent}=await import('/AleriaAlmanach/DokumentenWerkstatt/js/document-content.js');return sanitizeContent('<p style="text-align:center;background:url(https://bad.test)">Text<script>alert(1)</script><img src=x onerror=alert(1)><a href="javascript:alert(1)">Test</a></p>');})()`);
assert.ok(!/background|script|onerror|javascript|<img/.test(sanitized)); assert.ok(sanitized.includes('text-align: center'));
await command('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
await click('[data-tab="paper"]'); await pause();
await evaluate('window.scrollTo(0,0)'); await screenshot(artifact('workshop-mobile.png'));
console.log('mobile', await evaluate(`({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth})`));
await navigate(base + '/Dokumente%20aus%20der%20Werkstatt/dokument.html?id=brief-aus-dem-archiv');
assert.equal(await evaluate(`document.querySelector('[data-role="reader-title"]').textContent`), 'Ein Brief aus dem Archiv');
assert.ok(await evaluate(`document.querySelector('[data-role="reader-text"]').textContent.includes('Bewahrt dieses Blatt')`));
assert.equal(errors.length, 0, JSON.stringify(errors));
console.log('All browser assertions passed'); close();
