import assert from 'node:assert/strict';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const screenshotDirectory = process.env.CALENDAR_SCREENSHOTS;
const origin = process.env.CALENDAR_TEST_ORIGIN || 'http://127.0.0.1:5500';
const pathPrefix = process.env.CALENDAR_PATH_PREFIX || '';
const browser = await chromium.launch({ headless: true, executablePath: process.env.PLAYWRIGHT_EXECUTABLE });
const context = await browser.newContext({ viewport: { width: 1440, height: 1050 } });
await context.route('**/*', route => new URL(route.request().url()).origin === origin ? route.continue() : route.abort());
const page = await context.newPage(); const errors = [];
page.on('pageerror', error => errors.push(error.message));
try {
  await page.goto(`${origin}${pathPrefix}/AleriaAlmanach/kalender.html`, { waitUntil: 'load' });
  await page.locator('[data-calendar-day="9"]').waitFor();
  if (screenshotDirectory) await page.screenshot({ path: `${screenshotDirectory}/calendar-desktop.png`, fullPage: true });
  await page.getByRole('button', { name: '+ Termin eintragen', exact: true }).click();
  await page.locator('[name="title"]').fill('Audienz zur Prüfung');
  await page.locator('[name="type"]').selectOption('audience');
  await page.locator('[name="summary"]').fill('Eine Zusammenkunft im Saal des Grafen.');
  await page.locator('[name="location"]').fill('Gwynthor');
  await page.locator('[data-calendar-start] summary').click();
  await page.locator('[data-calendar-start] [data-calendar-day="12"]').click();
  await page.locator('[name="startTime"]').fill('10:00');
  await page.locator('[name="endTime"]').fill('11:00');
  await page.evaluate(() => { globalThis._fb = { loadCharacters: async () => [{ id: 'test-person', name: 'Prüffigur', portrait: '../IconOrdner/Siluetten/Unbekannt.png' }] }; window.dispatchEvent(new Event('fb-ready')); });
  await page.locator('.calendar-people-picker summary').click();
  await page.locator('[data-calendar-people] [data-calendar-person="test-person"]').click();
  await page.getByRole('button', { name: 'Icon aus dem Verzeichnis wählen' }).click();
  await page.locator('#icon-directory-search').fill('Kalender');
  await page.locator('#icon-directory-grid [data-icon-directory-action="select"]').first().click();
  if (screenshotDirectory) await page.screenshot({ path: `${screenshotDirectory}/calendar-editor.png`, fullPage: true });
  await page.locator('.calendar-editor [type="submit"]').click();
  await page.locator('#calendar-editor-overlay').waitFor({ state: 'hidden' });
  await page.reload({ waitUntil: 'load' });
  await page.getByRole('button', { name: 'Audienz zur Prüfung', exact: true }).first().click();
  await page.getByRole('button', { name: 'Termin bearbeiten', exact: true }).click();
  assert.equal(await page.locator('[name="title"]').inputValue(), 'Audienz zur Prüfung');
  assert.equal(await page.locator('[name="startTime"]').inputValue(), '10:00');
  assert.match(await page.locator('[data-calendar-selected-people]').innerText(), /Prüffigur/);
  await page.locator('[name="title"]').fill('Geänderte Audienz');
  await page.locator('.calendar-editor [type="submit"]').click();
  await page.locator('#calendar-editor-overlay').waitFor({ state: 'hidden' });
  for (const width of [390, 768, 1440]) {
    await page.setViewportSize({ width, height: 1000 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `page overflow ${width}`);
    if (screenshotDirectory) await page.screenshot({ path: `${screenshotDirectory}/calendar-${width}.png`, fullPage: true });
  }
  assert.deepEqual(errors, []);
  console.log('Calendar browser: create, date picker, icon, character, reload, edit and 3 viewports passed.');
  await page.setViewportSize({ width: 1440, height: 1050 });
  await page.goto(`${origin}${pathPrefix}/AleriaAlmanach/AleriaAlmanach.html`, { waitUntil: 'domcontentloaded' });
  await page.locator('[data-calendar-dashboard] .calendar-preview').first().waitFor();
  assert.match(await page.locator('[data-calendar-dashboard]').innerText(), /Geänderte Audienz/);
  await page.evaluate(() => openWorldDateDialog());
  await page.locator('[data-world-date-calendar] summary').click();
  assert.equal(await page.locator('[data-world-date-calendar] [data-calendar-day]').count(), 36);
  await page.locator('[data-world-date-calendar] [data-calendar-day="13"]').click();
  assert.match(await page.locator('[data-world-date-preview]').innerText(), /13\. Lichtkehr/);
  await page.getByRole('button', { name: 'Abbrechen', exact: true }).filter({ visible: true }).click();
  await page.evaluate(() => {
    globalThis.calendarTestThread = { kind: 'session', threadId: 'calendar-test', page: {}, entry: { id: 'calendar-test' }, pageIndex: 0 };
    getCurrentCommentThread = () => calendarTestThread;
    getCurrentCommentThreadId = () => 'calendar-test';
    _commentCache['calendar-test'] = [];
    setModuleSceneStartDateAleria = () => true;
  });
  await page.evaluate(() => openSceneTimeEventDialog());
  await page.locator('#scene-time-event-overlay.active').waitFor();
  assert.match(await page.locator('[data-scene-time-calendar] summary').innerText(), /9\. Lichtkehr/);
  assert.equal(await page.locator('#ste-anchor-day').getAttribute('type'), 'hidden');
  assert.equal(await page.locator('#ste-anchor-time').getAttribute('type'), 'text');
  const restoredIcons = await page.locator('.scene-time-preset-btn img').evaluateAll(images => images.map(image => image.getAttribute('src')));
  assert.deepEqual(restoredIcons, ['djPd9UD', 'm9ayflu', '2ldWsPp', 'VzP9VAA', 'EHo0HKi', 'r1dNxHU'].map(id => `https://i.imgur.com/${id}.png`));
  await page.locator('[data-scene-time-preset="next-day"]').click();
  assert.match(await page.locator('[data-scene-time-calendar] summary').innerText(), /10\. Lichtkehr/);
  assert.equal(await page.locator('#ste-anchor-time').inputValue(), '06:00:00');
  await page.locator('[data-scene-time-calendar] summary').click();
  await page.locator('[data-scene-time-calendar] [data-calendar-day="14"]').click();
  assert.match(await page.locator('#ste-day-label').inputValue(), /14\. Lichtkehr/);
  if (screenshotDirectory) await page.screenshot({ path: `${screenshotDirectory}/scene-time-calendar.png`, fullPage: false });
  await page.evaluate(() => {
    closeSceneTimeEventDialog();
    calendarTestThread.page.sessionDateAleria = { year: 1740, month: 3, day: 9 };
    _commentCache['calendar-test'] = [{ id: 'marker', sceneTimeEvent: { presetKey: 'evening', title: 'Alter Titel', anchorDay: 1, anchorSeconds: 66600 }, localOnly: true }];
  });
  await page.evaluate(() => editSceneTimeEvent('marker'));
  assert.equal(await page.locator('#ste-title').inputValue(), 'Alter Titel');
  assert.equal(await page.locator('#ste-anchor-time').inputValue(), '18:30:00');
  await page.locator('[data-scene-time-calendar] summary').click();
  await page.locator('[data-scene-time-calendar] [data-calendar-day="15"]').click();
  await page.locator('#ste-anchor-time').fill('12:00:00');
  const payload = await page.evaluate(() => getSceneTimeDialogPayload());
  assert.equal(payload.calendarDay, 7); assert.equal(payload.anchorSeconds, 43200);
  await page.evaluate(async () => {
    const backend = getLocalCommentBackend();
    const { id } = await backend.addComment('calendar-test', 'Erzähler', '', null, 'Alter Titel', COMMENT_DELETE_CODE, true, { commentMode: 'scene-time', sceneTimeEvent: _commentCache['calendar-test'][0].sceneTimeEvent });
    _commentCache['calendar-test'][0].id = id;
    _sceneTimeEditingId = id;
    globalThis.calendarTestMarkerId = id;
    getCommentBackend = async () => backend;
    loadCommentsIntoPage = async () => { _commentCache['calendar-test'] = await backend.loadComments('calendar-test'); };
    setCommentPageForCommentId = () => {};
  });
  await page.locator('#ste-title').fill('Neuer Titel');
  await page.locator('[data-scene-time-action="submit-event"]').click();
  await page.locator('#scene-time-event-overlay').waitFor({ state: 'hidden' });
  const savedMarker = await page.evaluate(async () => (await getLocalCommentBackend().loadComments('calendar-test')).find(item => item.id === calendarTestMarkerId));
  assert.equal(savedMarker.sceneTimeEvent.title, 'Neuer Titel'); assert.equal(savedMarker.sceneTimeEvent.calendarDay, 7); assert.equal(savedMarker.sceneTimeEvent.anchorSeconds, 43200);
  await page.evaluate(() => editSceneTimeEvent(calendarTestMarkerId));
  assert.equal(await page.locator('#ste-title').inputValue(), 'Neuer Titel');
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.locator('.scene-time-event-card').evaluate(el => el.scrollWidth <= el.clientWidth + 1));
  if (screenshotDirectory) await page.screenshot({ path: `${screenshotDirectory}/scene-time-mobile.png` });
  console.log('Almanach dashboard, world date picker, scene defaults, next day, editing and mobile passed.');
} finally { await browser.close(); }
