// Generated by scripts/build-house-content.mjs. Edit haus.content.mjs instead.
window.HAEUSER_DATA = {
  "meta": {
    "id": "haus-wyrm",
    "title": "Haus Wyrm O'Gwynthor – Aleria",
    "type": "Ritterfürstenhaus",
    "status": "Active",
    "template": "haus",
    "storage": {
      "document": "haus-wyrm"
    }
  },
  "name": "Haus Wyrm O'Gwynthor",
  "hierarchy": [
    {
      "type": "Sammlung",
      "name": "Familien Häuser und Clans",
      "slug": "familien-hauser-und-clans"
    },
    {
      "type": "Kontinent",
      "name": "Estryll",
      "slug": "estryll"
    },
    {
      "type": "Königreich",
      "name": "Cenyr",
      "slug": "cenyr"
    },
    {
      "type": "Grafschaft",
      "name": "Celtigerns Wacht",
      "slug": "celtigerns-wacht"
    },
    {
      "type": "Region",
      "name": "Llamreis Ankunft",
      "slug": "llamreis-ankunft"
    },
    {
      "type": "Sitz",
      "name": "Gwynthor",
      "slug": "gwynthor"
    },
    {
      "type": "Haus",
      "name": "Haus Wyrm",
      "slug": "haus-wyrm"
    }
  ],
  "layout": "responsive",
  "classification": {
    "category": "Familien Häuser und Clans",
    "houseType": "Ritterfürstenhaus",
    "scale": "Herrschaft",
    "parentHouseId": "haus-draig",
    "rootHouseId": "haus-draig",
    "territoryId": "herrschaft-wyrm"
  },
  "profile": {
    "highestTitle": "Ritterfürst",
    "houseType": "Herrschaft",
    "motto": "Nicht überliefert",
    "quoteAuthor": "",
    "seat": "Gwynthor",
    "affiliation": "Grafschaft Celtigerns Wacht · Graf Galahad Draig",
    "troopStrength": "Mittelmäßig",
    "tiarna": "Überwiegend Cantref, Uchelwyr",
    "kerns": "Mittelmäßig, überwiegend Kavallerie",
    "fleet": "Wenig",
    "founding": "12. Jahrhundert · erste überlieferte Amtszeit ab 1128",
    "milestoneOne": "Tryffin Draig, der „Fahrende Draig“, begründete den Zweig gemeinsam mit Rhianwyn Saethwyr. Seine Reisen und Heldentaten brachten ihm das Recht auf ein eigenes Haus ein. Die Wyrm führen auch Myrddins Abenteuerlust auf das Vorbild seines Onkels Tryffin zurück.",
    "milestoneTwo": "Mailgwin Wyrm · Seit 1717",
    "people": "Cenyri",
    "wealth": "Mittelmäßig",
    "religion": "Alerische Kirche",
    "patronDeities": "Die Dame der See",
    "origin": "Tryffin Draig und Rhianwyn Saethwyr",
    "cadetBranches": "Keine benannt",
    "allies": "Haus Draig",
    "enemies": "Keine gegenwärtige Hausfehde benannt"
  },
  "profileLabels": {
    "tiarna": "Ritter",
    "kerns": "Knechte"
  },
  "showMotto": false,
  "sections": {
    "overview": "Haus Wyrm ist ein altes Kadettenhaus der Draigs, begründet von Tryffin Draig und Rhianwyn Saethwyr. Mit Sitz in Gwynthor gehört es zu den Ritterfürstenhäusern von Celtigerns Wacht. Fahrende Ritter, höfische Romantik und ein ausgeprägtes Traditionsbewusstsein bestimmen seinen Ruf.",
    "history": "Sir Tryffin, ein Prinz des Hauses Draig, wurde als „Fahrender Draig“ bekannt. Er bereiste Cenyr und fremde Länder und erwarb durch Abenteuer und Heldentaten großen Ruhm. Seine Erlebnisse beeindruckten auch seinen jungen Neffen Myrddin, der später zum bedeutendsten Magier des Reiches aufstieg. Die Wyrm behaupten bis heute, Tryffin habe dessen Abenteuerlust geweckt und ihm den Weg zur Magie eröffnet.\n\nFür seine Verdienste erhielt Tryffin das Recht, ein eigenes Haus zu gründen. Aus dieser Auszeichnung entstand Haus Wyrm. Die überlieferte Oberhauptfolge setzt mit seiner Amtszeit von 1128 bis 1171 ein. Seine Nachkommen pflegten das Bild des fahrenden, galanten Ritters: mutig im Kampf, geschickt im Sattel und gewandt im höfischen Umgang.",
    "traditions": "Junge Männer werden ermutigt, als fahrende Ritter Tryffins Vorbild zu folgen. Abenteuerreisen, ritterliche Bewährung und die Kunst des Hofmachens gelten als ehrenvolle Wege, den Namen des Hauses bekannt zu machen.\n\nDie Familienordnung ist zugleich streng und von männlicher Vorrangstellung geprägt. Von Töchtern erwartet das Haus vor allem Eheschließungen, die Bündnisse stärken. Eigene Abenteuerreisen werden ihnen nur selten zugestanden. Dieser Unterschied gehört zu den überlieferten Erwartungen des Hauses.",
    "knighthood": "Das cenyrische Rittertum hat seine Wurzeln in Avallorn. Bei der Aufnahme wird der Knappe an einem See oder einem anderen Gewässer zum Ritter geschlagen und gesalbt. Er schwört auf jeden der Neun Göttlichen und dessen Tugenden; ein zehnter Eid gilt der Dame der See, der Schutzgöttin Cenyrs.\n\nDie Wyrm tragen dunkle Rüstungen mit roten Akzenten und schuppenartigen Platten. Ein stilisiertes Wyrm-Emblem auf der Brust erinnert an den Draig-Ursprung. Vor allem Cantref und Uchelwyr prägen ihr Ritteraufgebot; die Knechte dienen überwiegend als Kavallerie. Disziplin, Reitkunst und höfische Etikette ergänzen den Anspruch auf Tapferkeit und galantes Auftreten.",
    "cultureReligion": "Das Haus gehört zur cenyrischen Kultur und folgt der Alerischen Kirche. Besonders verehrt wird die Dame der See. Höfische Umgangsformen, romantische Erzählungen und die Erinnerung an Tryffins Abenteuer prägen sein kulturelles Selbstbild.",
    "conflictsAlliances": "Als Kadettenhaus ist Wyrm genealogisch mit Draig verbunden und dessen Grafen lehnspflichtig. Die Pferdezucht verknüpft das Haus wirtschaftlich mit Rhosmeres Rösser. Eine gegenwärtige Hausfehde ist nicht benannt.",
    "values": "Ehre, Tapferkeit und Romantik stehen neben Disziplin und Familientreue. Die Wyrm wollen das ritterliche Vermächtnis Tryffins bewahren. Persönlicher Ruhm und Abenteuerlust bleiben dabei in eine Hausordnung eingebunden, die unterschiedliche Erwartungen an Söhne und Töchter stellt.",
    "holdings": "Bergbau, Pferdezucht und Holzverarbeitung tragen die Wirtschaft der Herrschaft. Erze und seltene Metalle versorgen Handel und Waffenherstellung. In Zusammenarbeit mit Rhosmeres Rösser werden robuste, gut ausgebildete Kriegspferde gezüchtet. Die Wälder liefern Bau- und Brennholz sowie Material für den Schiffbau; dörfliche Handwerksbetriebe bedienen Ritter und städtische Märkte.",
    "succession": "Die überlieferte Erbfolge nennt Shan Wyrm, Gavin Wyrm. Die Reihenfolge und bekannten Amtszeiten sind unten aufgeführt; nicht überlieferte Zeiträume bleiben offen.",
    "court": "Mailgwin Wyrm führt das Haus. Die Übersicht versammelt Gründer, Oberhauptfolge, Erben und Hofämter. Nicht benannte Amtsinhaber sind mit den Silhouetten der Vorlage dargestellt.",
    "familyTree": "Der Stammbaum zeigt die überlieferten Generationen und ihre Heiratsverbindungen. Die verlinkten Portraits führen zu den jeweiligen Personen; das Hauswappen im Stammbaum öffnet die kurze Hausbiografie.",
    "historicalFigures": "Diese Personen prägten den Ursprung und die überlieferte Geschichte des Hauses."
  },
  "sectionTitles": {
    "knighthood": "4. Rittertum"
  },
  "images": {
    "haus-wappen": {
      "src": "../Stammbäume/assets/images/houses/Llamreis Ankunft/haus-wyrm.png",
      "alt": "Wappen von Haus Wyrm O'Gwynthor",
      "format": "square"
    },
    "haus-hauptbild": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Llamreis_Ankunft/Haus_Wyrm/assets/ritter.png",
      "alt": "Ritter von Haus Wyrm O'Gwynthor",
      "format": "portrait",
      "maxHeight": 580
    },
    "haus-banner": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Llamreis_Ankunft/Haus_Wyrm/assets/herrschaftsbanner.png",
      "href": "../Kontinente/Estryll/Königreich Cenyr/Grafschaft Celtigerns Wacht/Herrschaft der Wyrm/Herrschaft der Wyrm.html",
      "alt": "Herrschaftsbanner von Herrschaft der Wyrm",
      "format": "square"
    },
    "hof-founder-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-wyrm/tryffin-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view&person=tryffin-draig",
      "alt": "Tryffin Draig",
      "format": "portrait"
    },
    "hof-heads-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-wyrm/tryffin-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view&person=tryffin-draig",
      "alt": "Tryffin Draig",
      "format": "portrait"
    },
    "hof-heads-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-wyrm/gwastad-wyrm.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view&person=gwastad-wyrm",
      "alt": "Gwastad Wyrm",
      "format": "portrait"
    },
    "hof-heads-3": {
      "src": "../Stammbäume/assets/images/portraits/haus-wyrm/rhydderch-wyrm.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view&person=rhydderch-wyrm",
      "alt": "Rhydderch Wyrm",
      "format": "portrait"
    },
    "hof-heads-4": {
      "src": "../Stammbäume/assets/images/portraits/haus-wyrm/gallgoid-wyrm.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view&person=gallgoid-wyrm",
      "alt": "Gallgoid Wyrm",
      "format": "portrait"
    },
    "hof-heads-5": {
      "src": "../Stammbäume/assets/images/portraits/haus-wyrm/gwlyddyn-wyrm.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view&person=gwlyddyn-wyrm",
      "alt": "Gwlyddyn Wyrm",
      "format": "portrait"
    },
    "hof-heads-6": {
      "src": "../Stammbäume/assets/images/portraits/haus-wyrm/mailgwin-wyrm.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view&person=mailgwin-wyrm",
      "alt": "Mailgwin Wyrm",
      "format": "portrait"
    },
    "hof-heirs-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-wyrm/shan-wyrm.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view&person=shan-wyrm",
      "alt": "Shan Wyrm",
      "format": "portrait"
    },
    "hof-heirs-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-wyrm/gavin-wyrm.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view&person=gavin-wyrm",
      "alt": "Gavin Wyrm",
      "format": "portrait"
    },
    "hof-offices-1": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Vogt nicht benannt",
      "format": "portrait"
    },
    "hof-offices-2": {
      "src": "../Stammbäume/assets/images/placeholders/female.png",
      "href": "",
      "alt": "Silhouette · Schatzmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-3": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Kommandant der Garde nicht benannt",
      "format": "portrait"
    },
    "hof-offices-4": {
      "src": "../Stammbäume/assets/images/placeholders/female.png",
      "href": "",
      "alt": "Silhouette · Zeremonienmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-5": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Mundschenk nicht benannt",
      "format": "portrait"
    },
    "hof-offices-6": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Waffenmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-7": {
      "src": "../Stammbäume/assets/images/placeholders/female.png",
      "href": "",
      "alt": "Silhouette · Stallmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-8": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Kerkermeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-9": {
      "src": "../Stammbäume/assets/images/placeholders/female.png",
      "href": "",
      "alt": "Silhouette · Jagdmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-10": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Hafenmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-11": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Küchenmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-12": {
      "src": "../Stammbäume/assets/images/placeholders/female.png",
      "href": "",
      "alt": "Silhouette · Brotmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-13": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Handwerksmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-14": {
      "src": "../Stammbäume/assets/images/placeholders/female.png",
      "href": "",
      "alt": "Silhouette · Gartenmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-15": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Hofkaplan nicht benannt",
      "format": "portrait"
    },
    "hof-offices-16": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Hofmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-17": {
      "src": "../Stammbäume/assets/images/placeholders/female.png",
      "href": "",
      "alt": "Silhouette · Hofdame nicht benannt",
      "format": "portrait"
    },
    "hof-offices-18": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Archivar nicht benannt",
      "format": "portrait"
    },
    "hof-offices-19": {
      "src": "../Stammbäume/assets/images/placeholders/female.png",
      "href": "",
      "alt": "Silhouette · Hoffalkner nicht benannt",
      "format": "portrait"
    },
    "hof-offices-20": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Zwingermeister nicht benannt",
      "format": "portrait"
    },
    "haus-figur-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-wyrm/tryffin-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view&person=tryffin-draig",
      "alt": "Tryffin Draig",
      "format": "portrait"
    }
  },
  "court": {
    "groups": [
      {
        "id": "founder",
        "title": "Gründer",
        "entries": [
          {
            "name": "Tryffin Draig",
            "role": "",
            "detail": "1128–1171",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view&person=tryffin-draig",
            "imageKey": "hof-founder-1"
          }
        ]
      },
      {
        "id": "heads",
        "title": "Oberhauptfolge · Haus Wyrm O'Gwynthor",
        "note": "Überlieferte Amtszeiten; unbekannte Zeiträume bleiben offen.",
        "entries": [
          {
            "name": "Tryffin Draig",
            "role": "",
            "detail": "1128–1171",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view&person=tryffin-draig",
            "imageKey": "hof-heads-1"
          },
          {
            "name": "Gwastad Wyrm",
            "role": "",
            "detail": "1249–1311",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view&person=gwastad-wyrm",
            "imageKey": "hof-heads-2"
          },
          {
            "name": "Rhydderch Wyrm",
            "role": "",
            "detail": "Beginn unbekannt – 1665",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view&person=rhydderch-wyrm",
            "imageKey": "hof-heads-3"
          },
          {
            "name": "Gallgoid Wyrm",
            "role": "",
            "detail": "1665–1685",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view&person=gallgoid-wyrm",
            "imageKey": "hof-heads-4"
          },
          {
            "name": "Gwlyddyn Wyrm",
            "role": "",
            "detail": "1685–1717",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view&person=gwlyddyn-wyrm",
            "imageKey": "hof-heads-5"
          },
          {
            "name": "Mailgwin Wyrm",
            "role": "",
            "detail": "Seit 1717",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view&person=mailgwin-wyrm",
            "imageKey": "hof-heads-6"
          }
        ]
      },
      {
        "id": "heirs",
        "title": "Erbfolge",
        "entries": [
          {
            "name": "Shan Wyrm",
            "role": "",
            "detail": "1. in der Erbfolge",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view&person=shan-wyrm",
            "imageKey": "hof-heirs-1"
          },
          {
            "name": "Gavin Wyrm",
            "role": "",
            "detail": "2. in der Erbfolge",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view&person=gavin-wyrm",
            "imageKey": "hof-heirs-2"
          }
        ]
      },
      {
        "id": "offices",
        "title": "Hofämter",
        "entries": [
          {
            "name": "Nicht benannt",
            "role": "Vogt",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-1"
          },
          {
            "name": "Nicht benannt",
            "role": "Schatzmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-2"
          },
          {
            "name": "Nicht benannt",
            "role": "Kommandant der Garde",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-3"
          },
          {
            "name": "Nicht benannt",
            "role": "Zeremonienmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-4"
          },
          {
            "name": "Nicht benannt",
            "role": "Mundschenk",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-5"
          },
          {
            "name": "Nicht benannt",
            "role": "Waffenmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-6"
          },
          {
            "name": "Nicht benannt",
            "role": "Stallmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-7"
          },
          {
            "name": "Nicht benannt",
            "role": "Kerkermeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-8"
          },
          {
            "name": "Nicht benannt",
            "role": "Jagdmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-9"
          },
          {
            "name": "Nicht benannt",
            "role": "Hafenmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-10"
          },
          {
            "name": "Nicht benannt",
            "role": "Küchenmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-11"
          },
          {
            "name": "Nicht benannt",
            "role": "Brotmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-12"
          },
          {
            "name": "Nicht benannt",
            "role": "Handwerksmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-13"
          },
          {
            "name": "Nicht benannt",
            "role": "Gartenmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-14"
          },
          {
            "name": "Nicht benannt",
            "role": "Hofkaplan",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-15"
          },
          {
            "name": "Nicht benannt",
            "role": "Hofmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-16"
          },
          {
            "name": "Nicht benannt",
            "role": "Hofdame",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-17"
          },
          {
            "name": "Nicht benannt",
            "role": "Archivar",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-18"
          },
          {
            "name": "Nicht benannt",
            "role": "Hoffalkner",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-19"
          },
          {
            "name": "Nicht benannt",
            "role": "Zwingermeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-20"
          }
        ]
      }
    ],
    "cadets": []
  },
  "figures": {
    "heading": "12. Historische Figuren",
    "tableTitle": "Ursprung und Vermächtnis des Hauses",
    "entries": [
      {
        "group": "Ursprung und Vermächtnis des Hauses",
        "role": "Der Fahrende Draig · Gründer",
        "name": "Tryffin Draig",
        "description": "Tryffins Reisen und Heldentaten begründeten den Ruhm des Hauses Wyrm. Als Onkel Myrddins gilt er in der Hausüberlieferung als Vorbild für dessen Abenteuerlust. Seine überlieferte Amtszeit reicht von 1128 bis 1171.",
        "imageKey": "haus-figur-1"
      }
    ]
  },
  "familyTreeEmbed": {
    "src": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-wyrm&mode=view",
    "title": "Stammbaum von Haus Wyrm O'Gwynthor"
  },
  "trivia": [
    "Die Wyrm schreiben sich einen Anteil an Myrddins Erwachen zur Abenteuerlust zu.",
    "Ihre Pferdezucht arbeitet mit Rhosmeres Rösser zusammen."
  ]
};
