// Generated by scripts/build-house-content.mjs. Edit haus.content.mjs instead.
window.HAEUSER_DATA = {
  "meta": {
    "id": "haus-argall",
    "title": "Haus Argall – Aleria",
    "type": "Bürgerliches Haus",
    "status": "Active",
    "template": "kleinehaeuser",
    "storage": {
      "document": "haus-argall"
    }
  },
  "name": "Haus Argall",
  "hierarchy": [
    {
      "type": "Sammlung",
      "name": "Familien Häuser und Clans",
      "slug": "familien-hauser-und-clans"
    },
    {
      "type": "Kontinent",
      "name": "Estryll",
      "slug": "estryll"
    },
    {
      "type": "Königreich",
      "name": "Cenyr",
      "slug": "cenyr"
    },
    {
      "type": "Grafschaft",
      "name": "Celtigerns Wacht",
      "slug": "celtigerns-wacht"
    },
    {
      "type": "Region",
      "name": "Llamreis Ankunft",
      "slug": "llamreis-ankunft"
    },
    {
      "type": "Sitz",
      "name": "Llysfaen",
      "slug": "llysfaen"
    },
    {
      "type": "Haus",
      "name": "Haus Argall",
      "slug": "haus-argall"
    }
  ],
  "layout": "responsive",
  "classification": {
    "category": "Familien Häuser und Clans",
    "houseType": "Bürgerliches Haus",
    "scale": "Bürgerliches Haus",
    "parentHouseId": "",
    "rootHouseId": "haus-argall",
    "territoryId": "herrschaft-wyrm"
  },
  "profile": {
    "highestTitle": "Bürgerlich",
    "rank": "Bürgerlich",
    "houseType": "Bürgerliches Haus",
    "motto": "",
    "quoteAuthor": "",
    "seat": "Llysfaen",
    "affiliation": "Haus Wyrm",
    "liege": "Haus Wyrm",
    "patron": "",
    "knightingPatron": "",
    "troopStrength": "",
    "tiarna": "",
    "kerns": "",
    "fleet": "",
    "founding": "",
    "milestoneOne": "",
    "milestoneTwo": "",
    "people": "",
    "wealth": "",
    "religion": "",
    "patronDeities": "",
    "origin": "",
    "cadetBranches": "",
    "allies": "",
    "enemies": ""
  },
  "profileLabels": {
    "tiarna": "Ritter",
    "kerns": "Knechte"
  },
  "showMotto": false,
  "sections": {
    "overview": "Haus Argall ist eine bürgerliche Familie aus Llysfaen. Weitere Inhalte folgen.",
    "history": "Folgt …",
    "traditions": "Folgt …",
    "knighthood": "Folgt …",
    "succession": "Folgt …",
    "holdings": "Folgt …",
    "cultureReligion": "Folgt …",
    "conflictsAlliances": "Folgt …",
    "values": "Folgt …",
    "court": "Folgt …",
    "familyTree": "Die Hausbio öffnet sich über das Wappen im Stammbaum. Personen und Verbindungen sind in der Familienakte verzeichnet.",
    "historicalFigures": "Folgt …"
  },
  "sectionTitles": {
    "knighthood": "4. Rittertum"
  },
  "images": {
    "haus-wappen": {
      "src": "../Stammbäume/assets/images/houses/Llamreis Ankunft/Bürgerliche/Llysfaen/Argall.png",
      "alt": "Wappen von Haus Argall",
      "format": "square"
    },
    "haus-hauptbild": {
      "src": "",
      "alt": "Ritter von Haus Argall",
      "format": "portrait",
      "maxHeight": 580,
      "emptyLabel": "Illustration folgt …"
    },
    "haus-banner": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Llamreis_Ankunft/Haus_Wyrm/assets/herrschaftsbanner.png",
      "href": "../Kontinente/Estryll/Königreich Cenyr/Grafschaft Celtigerns Wacht/Herrschaft der Wyrm/Herrschaft der Wyrm.html",
      "alt": "Herrschaftsbanner von Herrschaft der Wyrm",
      "format": "square"
    }
  },
  "court": {
    "groups": [],
    "cadets": []
  },
  "figures": {
    "heading": "11. Historische Figuren",
    "tableTitle": "Persönlichkeiten des Hauses",
    "entries": []
  },
  "familyTreeEmbed": {
    "src": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-argall&mode=view",
    "title": "Stammbaum von Haus Argall"
  },
  "trivia": [
    "Folgt …"
  ]
};
