// Generated by scripts/build-house-content.mjs. Edit haus.content.mjs instead.
window.HAEUSER_DATA = {
  "meta": {
    "id": "haus-saethwyr",
    "title": "Haus Saethwyr O'Gwynthor – Aleria",
    "type": "Ritterfürstenhaus",
    "status": "Active",
    "template": "haus",
    "storage": {
      "document": "haus-saethwyr"
    }
  },
  "name": "Haus Saethwyr O'Gwynthor",
  "hierarchy": [
    {
      "type": "Sammlung",
      "name": "Familien Häuser und Clans",
      "slug": "familien-hauser-und-clans"
    },
    {
      "type": "Kontinent",
      "name": "Estryll",
      "slug": "estryll"
    },
    {
      "type": "Königreich",
      "name": "Cenyr",
      "slug": "cenyr"
    },
    {
      "type": "Grafschaft",
      "name": "Celtigerns Wacht",
      "slug": "celtigerns-wacht"
    },
    {
      "type": "Region",
      "name": "Llamreis Ankunft",
      "slug": "llamreis-ankunft"
    },
    {
      "type": "Sitz",
      "name": "Gwynthor",
      "slug": "gwynthor"
    },
    {
      "type": "Haus",
      "name": "Haus Saethwyr",
      "slug": "haus-saethwyr"
    }
  ],
  "layout": "responsive",
  "classification": {
    "category": "Familien Häuser und Clans",
    "houseType": "Ritterfürstenhaus",
    "scale": "Herrschaft",
    "parentHouseId": "haus-draig",
    "rootHouseId": "haus-draig",
    "territoryId": "herrschaft-saethwyr"
  },
  "profile": {
    "highestTitle": "Ritterfürst",
    "houseType": "Herrschaft",
    "motto": "Nicht überliefert",
    "quoteAuthor": "",
    "seat": "Gwynthor",
    "affiliation": "Grafschaft Celtigerns Wacht · Graf Galahad Draig",
    "troopStrength": "Mittelmäßig",
    "tiarna": "Überwiegend Helwyr, Cantref",
    "kerns": "Mittelmäßig, überwiegend Infanterie",
    "fleet": "Mehr Flotte als Heer",
    "founding": "Nach Kynwrigs Seesieg · Jahr unbekannt",
    "milestoneOne": "Kynwrig Draig, der Seefahrer, besiegte mit einer zahlenmäßig unterlegenen Mannschaft die Nordmänner. Dafür erhielt er den Ritterfürstentitel und das Recht auf ein eigenes Haus. Er benannte es nach seinem Schiff Saethwyr und nahm sich den Entdecker Sir Melwas zum Vorbild.",
    "milestoneTwo": "Huw Saethwyr · Seit 1720",
    "people": "Cenyri",
    "wealth": "Mittelmäßig",
    "religion": "Alerische Kirche",
    "patronDeities": "Die Dame der See, Die Seemaid",
    "origin": "Kynwrig Draig, der Seefahrer",
    "cadetBranches": "Keine benannt",
    "allies": "Haus Draig",
    "enemies": "Keine gegenwärtige Hausfehde benannt"
  },
  "profileLabels": {
    "tiarna": "Ritter",
    "kerns": "Knechte"
  },
  "showMotto": false,
  "sections": {
    "overview": "Haus Saethwyr ist ein Kadettenhaus der Draigs mit Sitz in Gwynthor. Sein Gründer Kynwrig, der Seefahrer, verband ritterlichen Mut mit einer tiefen Leidenschaft für das Meer. Dieses Erbe prägt die Ritterfürstenfamilie und ihre Aufgabe im Küstenschutz.",
    "history": "Kynwrig Draig führte ein Schiff namens Saethwyr und wollte den großen Entdeckern und Seekriegern nacheifern. Besonders Sir Melwas war sein Vorbild. Er übernahm dessen Rüstungsstil und Kampfweise und suchte selbst die Bewährung auf See.\n\nIn einer entscheidenden Schlacht gegen die Nordmänner führte Kynwrig seine deutlich unterlegenen Männer durch Geschick und List zum Sieg. Dafür erhielt er den Rang eines Ritterfürsten und die Erlaubnis zur Gründung eines eigenen Hauses. Den Namen wählte er zu Ehren seines Schiffes: Saethwyr.\n\nEin augenzwinkernder Teil der Überlieferung handelt von seinem Vorbild Melwas. Dessen Tapferkeit und Kampfstil konnte Kynwrig nachahmen; der berühmte prächtige Schnurrbart wollte ihm jedoch nicht wachsen. Der ehrgeizige Seefahrer blieb trotz aller Ähnlichkeit im Auftreten glattrasiert.",
    "traditions": "Die Angehörigen werden von klein auf mit Seefahrt und Seekampf vertraut gemacht. Ein eigenes Schiff zu führen gilt als besondere Ehre. Ausrüstung und Auftreten erinnern an Kynwrig; die Verteidigung der Küsten wird als Pflicht gegenüber dem Gründer und als Vermächtnis des Hauses verstanden.",
    "knighthood": "Das cenyrische Rittertum hat seine Wurzeln in Avallorn. Bei der Aufnahme wird der Knappe an einem See oder einem anderen Gewässer zum Ritter geschlagen und gesalbt. Er schwört auf jeden der Neun Göttlichen und dessen Tugenden; ein zehnter Eid gilt der Dame der See, der Schutzgöttin Cenyrs.\n\nGoldene und silberne Rüstungen mit Schuppenmustern und gehörnten Helmen erinnern an Kynwrigs Erscheinung. Sie sollen auf engem Deck Bewegungsfreiheit lassen und im Nahkampf schützen. Helwyr und Cantref stellen den Schwerpunkt des Ritteraufgebots. Die Knechte sind überwiegend Infanteristen; die Flotte hat für das Haus mehr Gewicht als das Landheer.",
    "cultureReligion": "Die Saethwyr gehören zu den Cenyri und zur Alerischen Kirche. Als besondere Patrone verehren sie die Dame der See und die Seemaid. Meer, Schiffe und die Erinnerung an große Seefahrer prägen ihre Familienkultur.",
    "conflictsAlliances": "Als Draig-Kadetten und Vasallen des Grafen sind die Saethwyr fest in die Grafschaft eingebunden. Der Sieg über die Nordmänner gehört zur Gründungsgeschichte; eine gegenwärtige Hausfehde ist nicht benannt. Küstenschutz und maritime Handelsbeziehungen bestimmen ihre äußeren Aufgaben.",
    "values": "Mut, Entschlossenheit und Seefahrertreue sind die Leitwerte des Hauses. Freiheit auf See steht neben Verantwortung für Küsten, Angehörige und Verbündete. Die Saethwyr verbinden Entdeckergeist mit der Pflicht, die ihnen anvertrauten Gewässer zu schützen.",
    "holdings": "Hafensiedlungen, Fischerei und Werften bilden die wirtschaftliche Grundlage. Salzfisch wird entlang der Küsten gehandelt. Die Schiffbauer fertigen schnelle, robuste Schiffe für Handel, Fischfang und Krieg. Segelmacherei und Tauwerkherstellung ergänzen das Handwerk; Handelsbeziehungen reichen über die unmittelbare Küstenregion hinaus.",
    "succession": "Die überlieferte Erbfolge nennt Marmaduke Saethwyr, Arian Saethwyr. Die Reihenfolge und bekannten Amtszeiten sind unten aufgeführt; nicht überlieferte Zeiträume bleiben offen.",
    "court": "Huw Saethwyr führt das Haus. Die Übersicht versammelt Gründer, Oberhauptfolge, Erben und Hofämter. Nicht benannte Amtsinhaber sind mit den Silhouetten der Vorlage dargestellt.",
    "familyTree": "Der Stammbaum zeigt die überlieferten Generationen und ihre Heiratsverbindungen. Die verlinkten Portraits führen zu den jeweiligen Personen; das Hauswappen im Stammbaum öffnet die kurze Hausbiografie.",
    "historicalFigures": "Diese Personen prägten den Ursprung und die überlieferte Geschichte des Hauses."
  },
  "sectionTitles": {
    "knighthood": "4. Rittertum"
  },
  "images": {
    "haus-wappen": {
      "src": "../Stammbäume/assets/images/houses/Llamreis Ankunft/haus-saethwyr.png",
      "alt": "Wappen von Haus Saethwyr O'Gwynthor",
      "format": "square"
    },
    "haus-hauptbild": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Llamreis_Ankunft/Haus_Saethwyr/assets/ritter.png",
      "alt": "Ritter von Haus Saethwyr O'Gwynthor",
      "format": "portrait",
      "maxHeight": 580
    },
    "haus-banner": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Llamreis_Ankunft/Haus_Saethwyr/assets/herrschaftsbanner.png",
      "href": "../Kontinente/Estryll/Königreich Cenyr/Grafschaft Celtigerns Wacht/Herrschaft der Saethwyr/Herrschaft der Saethwyr.html",
      "alt": "Herrschaftsbanner von Herrschaft der Saethwyr",
      "format": "square"
    },
    "hof-founder-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-gafyr/kynwrig-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=kynwrig-draig",
      "alt": "Kynwrig Draig",
      "format": "portrait"
    },
    "hof-heads-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-gafyr/kynwrig-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=kynwrig-draig",
      "alt": "Kynwrig Draig",
      "format": "portrait"
    },
    "hof-heads-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-saethwyr/odyar-saethwyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=odyar-saethwyr",
      "alt": "Odyar Saethwyr",
      "format": "portrait"
    },
    "hof-heads-3": {
      "src": "../Stammbäume/assets/images/portraits/haus-gafyr/limwris-saethwyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=limwris-saethwyr",
      "alt": "Limwris Saethwyr",
      "format": "portrait"
    },
    "hof-heads-4": {
      "src": "../Stammbäume/assets/images/portraits/haus-saethwyr/llawvrodedd-saethwyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=llawvrodedd-saethwyr",
      "alt": "Llawvrodedd Saethwyr",
      "format": "portrait"
    },
    "hof-heads-5": {
      "src": "../Stammbäume/assets/images/portraits/haus-saethwyr/drudwas-saethwyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=drudwas-saethwyr",
      "alt": "Drudwas Saethwyr",
      "format": "portrait"
    },
    "hof-heads-6": {
      "src": "../Stammbäume/assets/images/portraits/haus-saethwyr/gruffyd-saethwyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=gruffyd-saethwyr",
      "alt": "Gruffyd Saethwyr",
      "format": "portrait"
    },
    "hof-heads-7": {
      "src": "../Stammbäume/assets/images/portraits/haus-saethwyr/gallgoid-saethwyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=gallgoid-saethwyr",
      "alt": "Gallgoid Saethwyr",
      "format": "portrait"
    },
    "hof-heads-8": {
      "src": "../Stammbäume/assets/images/portraits/haus-saethwyr/huw-saethwyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=huw-saethwyr",
      "alt": "Huw Saethwyr",
      "format": "portrait"
    },
    "hof-heirs-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-wyrm/marmaduke-saethwyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=marmaduke-saethwyr",
      "alt": "Marmaduke Saethwyr",
      "format": "portrait"
    },
    "hof-heirs-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-saethwyr/arian-saethwyr.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=arian-saethwyr",
      "alt": "Arian Saethwyr",
      "format": "portrait"
    },
    "hof-offices-1": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Vogt nicht benannt",
      "format": "portrait"
    },
    "hof-offices-2": {
      "src": "../Stammbäume/assets/images/placeholders/female.png",
      "href": "",
      "alt": "Silhouette · Schatzmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-3": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Kommandant der Garde nicht benannt",
      "format": "portrait"
    },
    "hof-offices-4": {
      "src": "../Stammbäume/assets/images/placeholders/female.png",
      "href": "",
      "alt": "Silhouette · Zeremonienmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-5": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Mundschenk nicht benannt",
      "format": "portrait"
    },
    "hof-offices-6": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Waffenmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-7": {
      "src": "../Stammbäume/assets/images/placeholders/female.png",
      "href": "",
      "alt": "Silhouette · Stallmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-8": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Kerkermeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-9": {
      "src": "../Stammbäume/assets/images/placeholders/female.png",
      "href": "",
      "alt": "Silhouette · Jagdmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-10": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Hafenmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-11": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Küchenmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-12": {
      "src": "../Stammbäume/assets/images/placeholders/female.png",
      "href": "",
      "alt": "Silhouette · Brotmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-13": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Handwerksmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-14": {
      "src": "../Stammbäume/assets/images/placeholders/female.png",
      "href": "",
      "alt": "Silhouette · Gartenmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-15": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Hofkaplan nicht benannt",
      "format": "portrait"
    },
    "hof-offices-16": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Hofmeister nicht benannt",
      "format": "portrait"
    },
    "hof-offices-17": {
      "src": "../Stammbäume/assets/images/placeholders/female.png",
      "href": "",
      "alt": "Silhouette · Hofdame nicht benannt",
      "format": "portrait"
    },
    "hof-offices-18": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Archivar nicht benannt",
      "format": "portrait"
    },
    "hof-offices-19": {
      "src": "../Stammbäume/assets/images/placeholders/female.png",
      "href": "",
      "alt": "Silhouette · Hoffalkner nicht benannt",
      "format": "portrait"
    },
    "hof-offices-20": {
      "src": "../Stammbäume/assets/images/placeholders/male.png",
      "href": "",
      "alt": "Silhouette · Zwingermeister nicht benannt",
      "format": "portrait"
    },
    "haus-figur-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-gafyr/kynwrig-draig.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=kynwrig-draig",
      "alt": "Kynwrig Draig",
      "format": "portrait"
    }
  },
  "court": {
    "groups": [
      {
        "id": "founder",
        "title": "Gründer",
        "entries": [
          {
            "name": "Kynwrig Draig",
            "role": "",
            "detail": "Amtszeit unbekannt",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=kynwrig-draig",
            "imageKey": "hof-founder-1"
          }
        ]
      },
      {
        "id": "heads",
        "title": "Oberhauptfolge · Haus Saethwyr O'Gwynthor",
        "note": "Überlieferte Amtszeiten; unbekannte Zeiträume bleiben offen.",
        "entries": [
          {
            "name": "Kynwrig Draig",
            "role": "",
            "detail": "Amtszeit unbekannt",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=kynwrig-draig",
            "imageKey": "hof-heads-1"
          },
          {
            "name": "Odyar Saethwyr",
            "role": "",
            "detail": "Beginn unbekannt – 1143",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=odyar-saethwyr",
            "imageKey": "hof-heads-2"
          },
          {
            "name": "Limwris Saethwyr",
            "role": "",
            "detail": "Beginn unbekannt – 1300",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=limwris-saethwyr",
            "imageKey": "hof-heads-3"
          },
          {
            "name": "Llawvrodedd Saethwyr",
            "role": "",
            "detail": "Beginn unbekannt – 1644",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=llawvrodedd-saethwyr",
            "imageKey": "hof-heads-4"
          },
          {
            "name": "Drudwas Saethwyr",
            "role": "",
            "detail": "1644–1674",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=drudwas-saethwyr",
            "imageKey": "hof-heads-5"
          },
          {
            "name": "Gruffyd Saethwyr",
            "role": "",
            "detail": "1674–1700",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=gruffyd-saethwyr",
            "imageKey": "hof-heads-6"
          },
          {
            "name": "Gallgoid Saethwyr",
            "role": "",
            "detail": "1700–1720",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=gallgoid-saethwyr",
            "imageKey": "hof-heads-7"
          },
          {
            "name": "Huw Saethwyr",
            "role": "",
            "detail": "Seit 1720",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=huw-saethwyr",
            "imageKey": "hof-heads-8"
          }
        ]
      },
      {
        "id": "heirs",
        "title": "Erbfolge",
        "entries": [
          {
            "name": "Marmaduke Saethwyr",
            "role": "",
            "detail": "1. in der Erbfolge",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=marmaduke-saethwyr",
            "imageKey": "hof-heirs-1"
          },
          {
            "name": "Arian Saethwyr",
            "role": "",
            "detail": "2. in der Erbfolge",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view&person=arian-saethwyr",
            "imageKey": "hof-heirs-2"
          }
        ]
      },
      {
        "id": "offices",
        "title": "Hofämter",
        "entries": [
          {
            "name": "Nicht benannt",
            "role": "Vogt",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-1"
          },
          {
            "name": "Nicht benannt",
            "role": "Schatzmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-2"
          },
          {
            "name": "Nicht benannt",
            "role": "Kommandant der Garde",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-3"
          },
          {
            "name": "Nicht benannt",
            "role": "Zeremonienmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-4"
          },
          {
            "name": "Nicht benannt",
            "role": "Mundschenk",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-5"
          },
          {
            "name": "Nicht benannt",
            "role": "Waffenmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-6"
          },
          {
            "name": "Nicht benannt",
            "role": "Stallmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-7"
          },
          {
            "name": "Nicht benannt",
            "role": "Kerkermeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-8"
          },
          {
            "name": "Nicht benannt",
            "role": "Jagdmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-9"
          },
          {
            "name": "Nicht benannt",
            "role": "Hafenmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-10"
          },
          {
            "name": "Nicht benannt",
            "role": "Küchenmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-11"
          },
          {
            "name": "Nicht benannt",
            "role": "Brotmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-12"
          },
          {
            "name": "Nicht benannt",
            "role": "Handwerksmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-13"
          },
          {
            "name": "Nicht benannt",
            "role": "Gartenmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-14"
          },
          {
            "name": "Nicht benannt",
            "role": "Hofkaplan",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-15"
          },
          {
            "name": "Nicht benannt",
            "role": "Hofmeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-16"
          },
          {
            "name": "Nicht benannt",
            "role": "Hofdame",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-17"
          },
          {
            "name": "Nicht benannt",
            "role": "Archivar",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-18"
          },
          {
            "name": "Nicht benannt",
            "role": "Hoffalkner",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-19"
          },
          {
            "name": "Nicht benannt",
            "role": "Zwingermeister",
            "detail": "",
            "href": "",
            "imageKey": "hof-offices-20"
          }
        ]
      }
    ],
    "cadets": []
  },
  "figures": {
    "heading": "12. Historische Figuren",
    "tableTitle": "Ursprung und Vermächtnis des Hauses",
    "entries": [
      {
        "group": "Ursprung und Vermächtnis des Hauses",
        "role": "Der Seefahrer · Gründer",
        "name": "Kynwrig Draig",
        "description": "Ein Seesieg gegen überlegene Nordmänner brachte Kynwrig den Ritterfürstentitel ein. Er benannte Haus Saethwyr nach seinem Schiff und pflegte das Vorbild des berühmten Sir Melwas.",
        "imageKey": "haus-figur-1"
      }
    ]
  },
  "familyTreeEmbed": {
    "src": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-saethwyr&mode=view",
    "title": "Stammbaum von Haus Saethwyr O'Gwynthor"
  },
  "trivia": [
    "Saethwyr war zuerst der Name von Kynwrigs Schiff.",
    "Kynwrigs Versuch, Melwas nachzueifern, scheiterte der Überlieferung nach ausgerechnet an dessen Schnurrbart."
  ]
};
