// Generated by scripts/build-house-content.mjs. Edit haus.content.mjs instead.
window.HAEUSER_DATA = {
  "meta": {
    "id": "haus-daran",
    "title": "Haus Daran – Aleria",
    "type": "Ritterhaus",
    "status": "Active",
    "template": "kleinehaeuser",
    "storage": {
      "document": "haus-daran"
    }
  },
  "name": "Haus Daran",
  "hierarchy": [
    {
      "type": "Sammlung",
      "name": "Familien Häuser und Clans",
      "slug": "familien-hauser-und-clans"
    },
    {
      "type": "Kontinent",
      "name": "Estryll",
      "slug": "estryll"
    },
    {
      "type": "Königreich",
      "name": "Cenyr",
      "slug": "cenyr"
    },
    {
      "type": "Grafschaft",
      "name": "Celtigerns Wacht",
      "slug": "celtigerns-wacht"
    },
    {
      "type": "Region",
      "name": "Gwendolyns Ufer",
      "slug": "gwendolyns-ufer"
    },
    {
      "type": "Sitz",
      "name": "Garwfaen",
      "slug": "garwfaen"
    },
    {
      "type": "Haus",
      "name": "Haus Daran",
      "slug": "haus-daran"
    }
  ],
  "layout": "responsive",
  "classification": {
    "category": "Familien Häuser und Clans",
    "houseType": "Ritterhaus",
    "scale": "Ritterhaus",
    "parentHouseId": "",
    "rootHouseId": "haus-daran",
    "territoryId": "baronie-gwendolyns-ufer"
  },
  "profile": {
    "highestTitle": "Ritterherr",
    "rank": "Ritterherr",
    "houseType": "Ritterhaus",
    "motto": "",
    "quoteAuthor": "",
    "seat": "Garwfaen",
    "affiliation": "Haus Gwyvern",
    "liege": "Haus Gwyvern",
    "patron": "Haus Gwyvern",
    "knightingPatron": "Haus Gwyvern",
    "troopStrength": "",
    "tiarna": "",
    "kerns": "",
    "fleet": "",
    "founding": "1720",
    "milestoneOne": "",
    "milestoneTwo": "",
    "people": "Cenyri",
    "wealth": "Beschaulich",
    "religion": "Alerische Kirche",
    "patronDeities": "Knecht & Streiter",
    "origin": "Sir Maelgwyn Daran",
    "cadetBranches": "",
    "allies": "",
    "enemies": ""
  },
  "profileLabels": {
    "tiarna": "Ritter",
    "kerns": "Knechte"
  },
  "showMotto": false,
  "sections": {
    "overview": "Haus Daran ist kein altes Geschlecht mit verstaubten Ahnenreihen, sondern ein Haus, das aus Dienst geboren wurde. Sein Fundament ist nicht Blutlinie oder politisches Kalkül, sondern der unbeugsame Wille, Verantwortung zu tragen – auch dann, wenn andere längst beiseitetreten. Geformt durch Krieg, gehalten durch Disziplin und anerkannt durch tägliche Präsenz, ist Haus Daran ein fixer Bestandteil Garwfaens geworden, ohne je danach gestrebt zu haben.\n\nWas heute als ritterliches Haus gilt, ist in Wahrheit das Vermächtnis eines Mannes und derer, die seinen Maßstab übernommen haben. Ordnung wird hier nicht verwaltet, sondern gelebt. Auf den Mauern, an den Toren, in der Ausbildung der Wachen. Haus Daran existiert dort, wo Pflicht nicht delegiert wird.\n\nHaus Daran versteht sich nicht als Hofadel, sondern als Dienstadel. Seine Mitglieder bekleiden keine prunkvollen Ämter und meiden politische Bühnen, wo immer es möglich ist. Ihr Einfluss speist sich aus Verlässlichkeit und Präsenz: Wer Ordnung will, wendet sich an einen Daran. Wer Ausreden sucht, meidet sie.\n\nDas Haus ist klein, klar strukturiert und bewusst bodenständig. Besitz dient der Unabhängigkeit, nicht dem Status. Titel sind Mittel zum Zweck, kein Selbstzweck. In Garwfaen gilt: Solange ein Daran an den Toren steht, ist die Stadt nicht schutzlos.",
    "history": "Haus Daran entstand nicht aus altem Erbrecht, sondern aus dem Aufstieg eines Mannes: Sir Maelgwyn Daran. Er wurde im Jahr 1669 geboren und diente früh als Page bei Baron Seithved Gwyvern. Unter dessen Führung stieg er zum Knappen auf ( 1683 ) und wurde 1686 zum Ritter geschlagen.\n\nAls Belohnung erhielt Maelgwyn ein kleines Hofgut. Statt sich dort niederzulassen, zog er jedoch als fahrender Ritter auf Wanderschaft. Das prägt den Charakter des Hauses bis heute: Land ist Versorgung – nicht Ruhesitz.\n\nNach der Rückkehr heiratete Maelgwyn 1694 und gründete eine Familie. Sein Erstgeborener erhielt den Namen Seithved – als Ehrung seines Mentors.\n\nIm Jahr 1720 brach der große Krieg aus. Maelgwyn zog erneut unter die Banner, diesmal an der Seite von Baron Maredudd Gwyvern (Sohn seines alten Herren). Maredudd fiel, Maelgwyn überlebte. Nach der Rückkehr erhielt er Auszeichnungen: Medaille, Land, Ehre – und man bot ihm mehrfach den Posten des Lehenswarts von Garwfaen an.\n\nEr lehnte ab. Nicht einmal, sondern konsequent. Seine Begründung war praktisch: Er wollte führen, nicht verwalten. Das Amt ging schließlich an Caderyn Rhuddgar aus Abergwint.\n\nIm Jahr 1740 ist Sir Maelgwyn 71 Jahre alt und dennoch weiterhin Hauptmann der Stadtwache. Er lebt nicht auf dem Landgut, sondern in Garwfaen selbst, nahe seiner Truppe. In der Wahrnehmung der Stadt ist er nicht nur Gründer, sondern lebender Maßstab: Rekruten kennen seinen Namen, Diebe fürchten seine Stimme.",
    "traditions": "Aus dem Vorbild Sir Maelgwyns – und später auch seines Sohnes – entstand eine junge, aber feste Übung: Frisch geschlagene Ritter des Hauses Daran sollen ein bis zwei Jahre als fahrende Ritter durch Cenyr ziehen, um Land und Leute kennenzulernen, Schutz zu gewähren und Dienst zu leisten; erst nach ihrer Rückkehr binden sie sich bewusst an Garwfaen, das Land und das Haus.",
    "knighthood": "Folgt …",
    "succession": "Folgt …",
    "holdings": "Haus Daran verfügt über ein bewusst schlichtes und zweckgebundenes Besitztum. Mit der Gründung des Hauses im Jahr 1720 erhielt Sir Maelgwyn Daran ein altes Castell nördlich von Garwfaen, das ursprünglich als Wachposten diente und zu einem ritterlichen Gut umfunktioniert wurde. Dieses Anwesen gilt als formeller Sitz des Hauses, wird jedoch von wenigen Mitgliedern bewohnt, da sich die meisten anderen Mitglieder des Hauses im täglichen Dienst in Garwfaen aufhalten.\n\nDarüber hinaus besitzt Haus Daran einige wenige Landstücke im Umland, darunter einzelne Bauernhöfe, die gegen Pacht bewirtschaftet werden. Diese Einnahmen bilden die wichtigste Geldquelle des Hauses. Abgesehen davon verfügen die Darans über keinen nennenswerten Reichtum. Angebote, Garwfaen selbst als Lehen zu übernehmen und den Titel des Lehnswarts zu führen, wurden mehrfach ausgeschlagen – zugunsten von Dienst und Unabhängigkeit statt gesteigertem Wohlstand.",
    "cultureReligion": "Haus Daran ist in seinem Kern durch und durch garwfaenisch. Die Linie geht direkt auf Sir Maelgwyn Daran zurück – einen frommen, pflichtbewussten Mann von über siebzig Wintern, der nie vergessen hat, woher er stammt. Die Darans sind kein abgehobener Adel; noch vor ein oder zwei Generationen waren sie selbst bürgerlichen Standes. Diese Herkunft prägt ihre Kultur bis heute: Sie gelten als bodenständig, nahbar und frei von Standesdünkel. Man achtet sie, weil sie schützen, nicht weil sie herrschen.\n\nReligiös folgen die Darans keiner strengen Frömmigkeit, sondern einer praktischen Ehrfurcht. Verehrt werden vor allem der Knecht, Gott von Arbeit, Aufrichtigkeit, Fleiß und Handwerk, sowie der Streiter, Gott der Krieger, der Ehre und der Tapferkeit. Die Darans sind keine Kleriker und keine Eiferer, doch sie respektieren Götter und Land als tragende Ordnung der Welt. Gebet ist für sie keine Zierde, sondern Haltung – still, aufrichtig und ohne großes Aufheben.",
    "conflictsAlliances": "Allianzen und offene Gegnerschaften sind für Haus Daran ein junges Feld. Politisch steht das Haus bislang abseits größerer Verflechtungen, doch eine stabile Verbindung besteht zum Haus Rhuddgar. Diese gründet sich weniger auf Verträge als auf gegenseitigen Respekt: Caderyn Rhuddgar aus Abergwint übernahm den Posten des Lehnswarts von Garwfaen, nachdem Sir Maelgwyn Daran dieses Amt mehrfach dankend abgelehnt hatte. Aus dieser Konstellation erwuchs eine sachliche, wachsende Freundschaft – getragen von klarer Rollenverteilung und gemeinsamem Interesse an Ordnung und Stabilität.\n\nOffene Fehden mit anderen Häusern führt Haus Daran nicht und hat auch kein Interesse daran, politische Konflikte zu provozieren. Ihr Kampfplatz liegt außerhalb der höfischen Arena. Lokale Banditen, Wegelagerer und Raubritter stellen hingegen sehr wohl Gegner dar – und mit diesen legt sich Haus Daran ohne Zögern an. Wo Ordnung bedroht wird, endet Neutralität. Für die Darans sind solche Auseinandersetzungen kein politisches Mittel, sondern schlichte Pflichterfüllung.",
    "values": "Haus Daran steht für Pflicht ohne Eitelkeit. Seine Moral gründet nicht auf alten Titeln oder politischem Ehrgeiz, sondern auf der Überzeugung, dass Ordnung Arbeit ist und Schutz Verantwortung bedeutet. Ein Daran dient, wo er gebraucht wird, hält Wort statt Reden und misst Ehre nicht an Ruhm, sondern an Verlässlichkeit. Macht wird nicht gesucht, Reichtum nicht angehäuft – entscheidend ist allein, dass Garwfaen sicher bleibt und der Ritter seinem Stand durch Haltung gerecht wird, nicht durch Anspruch.",
    "court": "Überlieferte Oberhäupter, Erben und Aufgaben. Unbekannte Angaben bleiben offen.",
    "familyTree": "Die Hausbio öffnet sich über das Wappen im Stammbaum. Personen und Verbindungen sind in der Familienakte verzeichnet.",
    "historicalFigures": "Überlieferte Persönlichkeiten des Hauses."
  },
  "sectionTitles": {
    "knighthood": "4. Rittertum"
  },
  "images": {
    "haus-wappen": {
      "src": "../Stammbäume/assets/images/houses/Gwendolyns Ufer/Ritterliche/Daran.png",
      "alt": "Wappen von Haus Daran",
      "format": "square"
    },
    "haus-hauptbild": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Gwendolyns_Ufer/Haus_Daran/assets/hausmotiv.png",
      "alt": "Hausmotiv · Haus Daran",
      "format": "portrait",
      "maxHeight": 580
    },
    "haus-banner": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Gwendolyns_Ufer/Haus_Gwyvern/assets/herrschaftsbanner.png",
      "href": "../Kontinente/Estryll/Königreich Cenyr/Grafschaft Celtigerns Wacht/Baronie Gwendolyns Ufer/Baronie Gwendolyns Ufer.html",
      "alt": "Herrschaftsbanner von Baronie Gwendolyns Ufer",
      "format": "square"
    },
    "hof-founder-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-daran/maelgwyn-daran.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-daran&mode=view&person=maelgwyn-daran",
      "alt": "Maelgwyn Daran",
      "format": "portrait"
    },
    "hof-heads-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-daran/maelgwyn-daran.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-daran&mode=view&person=maelgwyn-daran",
      "alt": "Maelgwyn Daran",
      "format": "portrait"
    },
    "hof-heirs-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-daran/seithved-daran.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-daran&mode=view&person=seithved-daran",
      "alt": "Seithved Daran",
      "format": "portrait"
    },
    "hof-heirs-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-daran/lleu-daran.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-daran&mode=view&person=lleu-daran",
      "alt": "Lleu Daran",
      "format": "portrait"
    },
    "haus-figur-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-daran/maelgwyn-daran.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-daran&mode=view&person=maelgwyn-daran",
      "alt": "Maelgwyn Daran",
      "format": "portrait"
    },
    "haus-figur-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-daran/nest-daran.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-daran&mode=view&person=nest-daran",
      "alt": "Nest",
      "format": "portrait"
    },
    "haus-figur-3": {
      "src": "../Stammbäume/assets/images/portraits/haus-daran/seithved-daran.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-daran&mode=view&person=seithved-daran",
      "alt": "Seithved Daran",
      "format": "portrait"
    },
    "haus-figur-4": {
      "src": "../Stammbäume/assets/images/portraits/haus-daran/rhodri-daran.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-daran&mode=view&person=rhodri-daran",
      "alt": "Rhodri Daran",
      "format": "portrait"
    },
    "haus-figur-5": {
      "src": "../Stammbäume/assets/images/portraits/haus-daran/einion-daran.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-daran&mode=view&person=einion-daran",
      "alt": "Einion Daran",
      "format": "portrait"
    }
  },
  "court": {
    "groups": [
      {
        "id": "founder",
        "title": "Gründer",
        "entries": [
          {
            "name": "Maelgwyn Daran",
            "role": "",
            "detail": "Amtszeit: 1720–…",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-daran&mode=view&person=maelgwyn-daran",
            "imageKey": "hof-founder-1"
          }
        ]
      },
      {
        "id": "heads",
        "title": "Oberhauptfolge · Haus Daran",
        "note": "Überlieferte Oberhäupter; Lücken und nicht belegte Amtszeiten bleiben offen.",
        "entries": [
          {
            "name": "Maelgwyn Daran",
            "role": "",
            "detail": "Amtszeit: 1720–…",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-daran&mode=view&person=maelgwyn-daran",
            "imageKey": "hof-heads-1"
          }
        ]
      },
      {
        "id": "heirs",
        "title": "Erbfolge",
        "entries": [
          {
            "name": "Seithved Daran",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-daran&mode=view&person=seithved-daran",
            "imageKey": "hof-heirs-1"
          },
          {
            "name": "Lleu Daran",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-daran&mode=view&person=lleu-daran",
            "imageKey": "hof-heirs-2"
          }
        ]
      }
    ],
    "cadets": []
  },
  "figures": {
    "heading": "11. Historische Figuren",
    "tableTitle": "Persönlichkeiten des Hauses",
    "entries": [
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Ritterherr Maelgwyn Daran",
        "name": "Maelgwyn Daran",
        "description": "Sir Maelgwyn Daran ist der Gründer und moralische Maßstab seines Hauses. Geboren 1669, geprägt durch Krieg und jahrzehntelangen Dienst, verkörpert er das Selbstverständnis der Darans wie kein anderer. Er ist stoisch, pflichtbewusst und frei von jeder Neigung zu Prunk oder Bequemlichkeit. Titel bedeuten ihm wenig – Haltung alles. Ausreden duldet er nicht, Ehrlichkeit schätzt er hoch, und Respekt verdient sich bei ihm allein durch verlässliche Arbeit. Derzeit bekleidet Sir Maelgwyn den Posten des Hauptmanns der Stadtwache von Garwfaen. Trotz seines Alters von über siebzig Wintern lebt und wirkt er mitten in der Stadt, nahe seiner Männer. Er führt durch Vorbild, nicht durch Lautstärke, und gilt in Garwfaen weniger als Amtsträger denn als feste Größe – ein Mann, der bleibt, solange er noch stehen kann.",
        "imageKey": "haus-figur-1"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Herrin Nest",
        "name": "Nest",
        "description": "Herrin Nest ist die Gattin Sir Maelgwyns und eine gebürtige Garwfaenerin – bodenständig, scharfzüngig und fest im Ort verwurzelt. 1686 hielt Maelgwyn nach seinem Ritterschlag um ihre Hand an; sie willigte ein. Statt Hochzeit folgten jedoch acht Jahre Verlobung, denn Maelgwyn zog als fahrender Ritter durch Cenyr bis die beiden 1694 schließlich heirateten. In Garwfaen kursiert das Gerücht, er habe auf den Tod der Schwiegermutter in spe gewartet – meist wird das als Klatsch abgetan. Derzeit führt Herrin Nest den Haushalt des Hauses Daran und hält den Kontakt zur Bürgerschaft – leise, aber wirkungsvoll. Ihrem Gatten wirft sie bis heute gelegentlich die lange Verlobungszeit vor; sie hätte, so sagt sie, durchaus einen Gwyvern oder gar Draig an Land ziehen können. Maelgwyn reagiert darauf zuverlässig gleich: ein Seufzen – und er geht angeln.",
        "imageKey": "haus-figur-2"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Sir Seithved",
        "name": "Seithved Daran",
        "description": "Sir Seithved Daran ist der Erstgeborene Sir Maelgwyns und gilt weithin als der fähigste Ritter Garwfaens – auch wenn er selbst diesem Ruf wenig Bedeutung beimisst. Wie sein Vater ist er geradlinig, ehrlich und frei von höfischem Ehrgeiz. Intrigen liegen ihm fern, List verachtet er; Seithved kämpft offen mit Schwert und Schild und erwartet dasselbe von anderen. Er ist kein Mann großer Reden, sondern einer klarer Handlungen. Derzeit steht Sir Seithved im aktiven Wachdienst Garwfaens. Nicht selten versieht er selbst Nachtwachen an Nord- oder Südtor, vollständig gerüstet bis zum Morgengrauen. Der Baron hat bereits Interesse bekundet, ihn an den Hof zu ziehen – doch Seithved lehnt ab. Solange Bedrohungen wie der Zitteraal die Wälder unsicher machen, bleibt sein Platz bei den Menschen Garwfaens.",
        "imageKey": "haus-figur-3"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Sir Rhodri",
        "name": "Rhodri Daran",
        "description": "Sir Rhodri Daran ist der zweitälteste der Linie und das stille Gegengewicht zu den präsenten Darans Garwfaens. Er ist ruhig, ordentlich, reserviert – und bewusst unauffällig. Wo andere führen oder wachen, sorgt Rhodri dafür, dass Dinge funktionieren. Er sucht keine Aufmerksamkeit und meidet den öffentlichen Auftritt; Verlässlichkeit ist seine Sprache. Derzeit verwaltet Sir Rhodri das Anwesen des Hauses Daran in den nördlichen Hügeln und überwacht die dem Haus unterstellten Bauernhöfe. Er hält Ordnung auf dem Gut, schlichtet Streitigkeiten, organisiert Abgaben und sorgt für ruhigen Betrieb. In Garwfaen selbst lässt er sich selten blicken – nicht aus Distanz, sondern weil seine Arbeit dort liegt, wo sie gebraucht wird.",
        "imageKey": "haus-figur-4"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Sir Einion",
        "name": "Einion Daran",
        "description": "Sir Einion Daran ist der jüngste der Daran-Ritter, dreißig Jahre alt, kräftig, erfahren – und stets ein wenig im Schatten seiner Brüder. Er war mit Leib und Seele fahrender Ritter und liebte die Freiheit, durch Cenyr zu ziehen, Streit zu schlichten und dort zu helfen, wo man ihn brauchte. Diese Zeit hat ihn geprägt – und fehlt ihm bis heute. Derzeit dient Sir Einion als Ritter Garwfaens. Er hat Frau und Kind, Pflichten und festen Boden unter den Füßen. Die alten Tage vermisst er, ohne sich ihnen hinzugeben. Denn Einion ist ein Daran: Er weiß, dass Pflicht gegenüber Haus und Stadt über persönlichen Wünschen steht – auch wenn diese Erkenntnis manchmal schmerzt.",
        "imageKey": "haus-figur-5"
      }
    ]
  },
  "familyTreeEmbed": {
    "src": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-daran&mode=view",
    "title": "Stammbaum von Haus Daran"
  },
  "trivia": [
    "Folgt …"
  ]
};
