// Generated by scripts/build-house-content.mjs. Edit haus.content.mjs instead.
window.HAEUSER_DATA = {
  "meta": {
    "id": "haus-awenydd",
    "title": "Haus Awenydd – Aleria",
    "type": "Ritterhaus",
    "status": "Active",
    "template": "kleinehaeuser",
    "storage": {
      "document": "haus-awenydd"
    }
  },
  "name": "Haus Awenydd",
  "hierarchy": [
    {
      "type": "Sammlung",
      "name": "Familien Häuser und Clans",
      "slug": "familien-hauser-und-clans"
    },
    {
      "type": "Kontinent",
      "name": "Estryll",
      "slug": "estryll"
    },
    {
      "type": "Königreich",
      "name": "Cenyr",
      "slug": "cenyr"
    },
    {
      "type": "Grafschaft",
      "name": "Celtigerns Wacht",
      "slug": "celtigerns-wacht"
    },
    {
      "type": "Region",
      "name": "Llamreis Ankunft",
      "slug": "llamreis-ankunft"
    },
    {
      "type": "Sitz",
      "name": "Gwynthor",
      "slug": "gwynthor"
    },
    {
      "type": "Haus",
      "name": "Haus Awenydd",
      "slug": "haus-awenydd"
    }
  ],
  "layout": "responsive",
  "classification": {
    "category": "Familien Häuser und Clans",
    "houseType": "Ritterhaus",
    "scale": "Ritterhaus",
    "parentHouseId": "",
    "rootHouseId": "haus-awenydd",
    "territoryId": "celtigerns-wacht"
  },
  "profile": {
    "highestTitle": "Ritterherr",
    "rank": "Ritterherr",
    "houseType": "Ritterhaus",
    "motto": "",
    "quoteAuthor": "",
    "seat": "Gwynthor",
    "affiliation": "Haus Draig",
    "liege": "Haus Draig",
    "patron": "",
    "knightingPatron": "",
    "troopStrength": "",
    "tiarna": "",
    "kerns": "",
    "fleet": "",
    "founding": "",
    "milestoneOne": "",
    "milestoneTwo": "",
    "people": "Cenyri",
    "wealth": "Beschaulich",
    "religion": "Die Alerische Kirche",
    "patronDeities": "",
    "origin": "",
    "cadetBranches": "",
    "allies": "",
    "enemies": ""
  },
  "profileLabels": {
    "tiarna": "Ritter",
    "kerns": "Knechte"
  },
  "showMotto": false,
  "sections": {
    "overview": "Haus Awenydd ist ein niederes ritterliches Haus aus Gwynthor, alt an Herkunft, aber ohne Legende, bekannt nicht durch Ruhm, sondern durch stete Treue zum Haus Draig. Politisch unauffällig, wirtschaftlich solide und ohne großen Einfluss dient es seit Generationen als verlässlicher Vasall, dessen Mitglieder als Ritter, Verwalter oder Gesandte eingesetzt werden, ohne je den Anspruch zu erheben, mehr zu sein als nötig. Ihre Burg sichert eine wichtige Nordstraße, ihr Gestüt genießt Anerkennung, ihre Ehen sind pragmatisch, ihr Glaube ordentlich und ihre Moral klar auf Pflicht, Maß und Loyalität ausgerichtet. Die Awenydd streben nicht nach Größe – sie bestehen, weil man sich auf sie verlassen kann",
    "history": "Der Ursprung des Hauses Awenydd ist alt, aber unerquicklich. Keine Legende, kein göttliches Zeichen, kein blutiger Schwur am Ende einer Schlacht. Nur ein Ritter aus Gwynthor, dessen Name heute kaum mehr als eine Randnotiz ist, der dem Hause Draig die Treue schwor – nüchtern, verbindlich, endgültig.\n\nDieser Ritter erhielt Land, ein kleines Lehen, Schutz und Pflicht. Mehr nicht. Und genau daraus wuchs Awenydd. Über Generationen hinweg hielt das Haus, was es versprach: Loyalität ohne Zögern, Dienst ohne Forderung, Waffen nur dort, wo Worte endeten. Sie erhoben sich nie über ihren Stand und fielen nie darunter. Während andere Häuser aufstiegen und stürzten, blieb Awenydd – unauffällig, verlässlich, austauschbar wirkend und doch unersetzlich.\n\nIhre Nähe zum Grafenhaus Draig machte sie nie mächtig, aber immer notwendig. Awenydd wurde das Haus, das man schickt, wenn Loyalität gefragt ist. Das man einsetzt, wenn Ordnung hergestellt werden muss. Das man hört, wenn Entscheidungen ohne Schmuck, ohne Pathos und ohne falsche Versprechen gefällt werden sollen.\n\nSo ist Haus Awenydd bis heute kein Haus der Geschichten, sondern eines der Akten, Siegel und stillen Eide. Und in Gwynthor weiß man: Häuser wie dieses überleben länger als jene, über die gesungen wird.",
    "traditions": "Haus Awenydd galt lange als Quelle verlässlicher Verwalter und pflichtbewusster Kastellane. Inzwischen wurden sie in diesen Rollen jedoch von Häusern wie den Balchder deutlich überholt. Wo früher Awenydd als Vögte, Kämmerer oder Justiziare dienten, greifen die Draigs heute meist auf andere zurück. Die Awenydd verschwanden aus diesen Ämtern – still, ohne Widerstand, ohne Anspruch.\n\nGeblieben ist ihre Treue. Auch ohne Einfluss und Titel stehen sie weiterhin als ritterliche Diener des Hauses Draig bereit, ohne zu murren, ohne zu fordern.\n\nIhre Traditionen sind entsprechend unspektakulär. Die Sprösslinge werden zu Rittern erzogen, im Schwert, im Sattel, im Schreiben und in Etikette, ergänzt durch grundlegende wirtschaftliche Bildung. Kein Glanz, keine Besonderheiten – nur Zuverlässigkeit.\n\nMan erwartet von einem Awenydd keine Größe. Man weiß nur: Einen Awenydd kann man immer gebrauchen.",
    "knighthood": "Folgt …",
    "succession": "Folgt …",
    "holdings": "Haus Awenydd ist weder wohlhabend noch verarmt. Ihre Mittel reichen für Unterhalt, Waffen und Verpflichtungen, aber nicht für Prunk. Ihre Burg liegt im Umland von Gwynthor und sichert die Straße in den Norden – eine strategische Aufgabe, die mehr Pflicht als Prestige bringt.\n\nVon größerer Bedeutung ist ihr Gestüt, das seit Generationen besteht und einen guten Ruf genießt. Es wird in Kooperation mit der Rhosmeres Rösser geführt. Die Awenydd selbst sind dort jedoch nur noch indirekt eingebunden; Verwaltung und Betrieb liegen zunehmend in den Händen von Bediensteten und beauftragten Verwaltern.\n\nDarüber hinaus besitzen sie die Lehensherrschaft über einige Höfe, die ihnen Pacht entrichten. Kein umfangreicher Landbesitz, keine reichen Einkünfte – aber genug, um das Haus stabil zu halten und seine Pflichten gegenüber den Draigs zu erfüllen.",
    "cultureReligion": "Wie die meisten Cenyri sind auch die Awenydd treue Anhänger der Alerischen Kirche. Ihre Frömmigkeit ist sittsam, geordnet und frei von Ausschweifungen. Sie halten sich an die gewohnten Gepflogenheiten, besuchen die Gottesdienste, leisten ihre Abgaben und achten die kirchlichen Autoritäten – nicht aus Inbrunst, sondern aus Pflichtbewusstsein.\n\nMan sieht in ihnen jedoch weder Heilige noch besonders fromme Ritter. Sie stechen nicht hervor, sie missionieren nicht, sie tragen ihren Glauben nicht vor sich her. Die Awenydd sind gute Edelleute, die tun, was von ihnen erwartet wird – nicht mehr, nicht weniger.",
    "conflictsAlliances": "In der politischen Arena Gwynthors zählt Haus Awenydd zu den unauffälligsten Akteuren. Es richtet sich vollständig nach dem Willen des Hauses Draig und verfolgt keine eigene Agenda. Eigenständige Machtpolitik, Lagerbildung oder Intrigen sind ihnen fremd – bewusst und konsequent.\n\nEhen werden vorzugsweise mit anderen Adligen geschlossen oder mit Mitgliedern der Rhosmeres Rösser, was pragmatische Bindungen stärkt, ohne politische Spannungen zu erzeugen. Diese Verbindungen dienen Stabilität, nicht Einflussgewinn.\n\nKonflikte bestehen keine – zumindest nicht mit anderen Häusern. Awenydd ist kein Haus, das Reibung erzeugt. Es existiert, dient und bleibt aus dem Fokus. Genau das macht es für die Draigs verlässlich.",
    "values": "Die Moral des Hauses Awenydd gründet auf Pflicht, Verlässlichkeit und Zurückhaltung. Sie glauben nicht an Größe um ihrer selbst willen, sondern an Beständigkeit durch Dienst. Ehre entsteht für sie nicht aus Ruhm, sondern daraus, Erwartungen zu erfüllen und Versprechen einzuhalten.\n\nEin Awenydd sucht keinen Glanz, keinen Einfluss und kein lautes Wort. Er tut, was getan werden muss, bleibt loyal, hält sich an Ordnung und Maß – und akzeptiert seinen Platz, solange er dem Ganzen dient.",
    "court": "Überlieferte Personen und Aufgaben. Nicht belegte Angaben bleiben offen.",
    "familyTree": "Die Hausbio öffnet sich über das Wappen im Stammbaum. Personen und Verbindungen sind in der Familienakte verzeichnet.",
    "historicalFigures": "Überlieferte Persönlichkeiten und ihre Bedeutung für das Haus."
  },
  "sectionTitles": {
    "knighthood": "4. Rittertum"
  },
  "images": {
    "haus-wappen": {
      "src": "../Stammbäume/assets/images/houses/Llamreis Ankunft/haus-awenydd.png",
      "alt": "Wappen von Haus Awenydd",
      "format": "square"
    },
    "haus-hauptbild": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Llamreis_Ankunft/Haus_Awenydd/assets/hausmotiv.png",
      "alt": "Hausmotiv · Haus Awenydd",
      "format": "portrait",
      "maxHeight": 580
    },
    "haus-banner": {
      "src": "Estryll/Cenyr/Celtigerns_Wacht/Haus_Draig/assets/gwynthor.png",
      "href": "../Kontinente/Estryll/Königreich Cenyr/Grafschaft Celtigerns Wacht/Grafschaft Celtigerns Wacht.html",
      "alt": "Herrschaftsbanner von Celtigerns Wacht",
      "format": "square"
    },
    "hof-founder-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenydd/aeddan-awenydd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenydd&mode=view&person=aeddan-awenydd",
      "alt": "Aeddan Awenydd",
      "format": "portrait"
    },
    "hof-heads-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenydd/aeddan-awenydd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenydd&mode=view&person=aeddan-awenydd",
      "alt": "Aeddan Awenydd",
      "format": "portrait"
    },
    "hof-heads-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenydd/colwyn-awenydd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenydd&mode=view&person=colwyn-awenydd",
      "alt": "Colwyn Awenydd",
      "format": "portrait"
    },
    "hof-heads-3": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenydd/derfel-awenydd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenydd&mode=view&person=derfel-awenydd",
      "alt": "Derfel Awenydd",
      "format": "portrait"
    },
    "hof-heirs-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenydd/gildas-awenydd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenydd&mode=view&person=gildas-awenydd",
      "alt": "Gildas Awenydd",
      "format": "portrait"
    },
    "haus-figur-1": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenydd/hafgan-awenydd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenydd&mode=view&person=hafgan-awenydd",
      "alt": "Hafgan Awenydd",
      "format": "portrait"
    },
    "haus-figur-2": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenydd/brychan-awenydd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenydd&mode=view&person=brychan-awenydd",
      "alt": "Brychan Awenydd",
      "format": "portrait"
    },
    "haus-figur-3": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenydd/idnerth-awenydd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenydd&mode=view&person=idnerth-awenydd",
      "alt": "Idnerth Awenydd",
      "format": "portrait"
    },
    "haus-figur-4": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenydd/amren-awenydd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenydd&mode=view&person=amren-awenydd",
      "alt": "Amren Awenydd",
      "format": "portrait"
    },
    "haus-figur-5": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenydd/gwern-awenydd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenydd&mode=view&person=gwern-awenydd",
      "alt": "Gwern Awenydd",
      "format": "portrait"
    },
    "haus-figur-6": {
      "src": "../Stammbäume/assets/images/portraits/haus-awenydd/arthen-awenydd.jpg",
      "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenydd&mode=view&person=arthen-awenydd",
      "alt": "Arthen Awenydd",
      "format": "portrait"
    }
  },
  "court": {
    "groups": [
      {
        "id": "founder",
        "title": "Gründer",
        "entries": [
          {
            "name": "Aeddan Awenydd",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenydd&mode=view&person=aeddan-awenydd",
            "imageKey": "hof-founder-1"
          }
        ]
      },
      {
        "id": "heads",
        "title": "Oberhauptfolge · Haus Awenydd",
        "note": "Überlieferte Oberhäupter. Zeitangaben werden nur übernommen, soweit sie belegt sind.",
        "entries": [
          {
            "name": "Aeddan Awenydd",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenydd&mode=view&person=aeddan-awenydd",
            "imageKey": "hof-heads-1"
          },
          {
            "name": "Colwyn Awenydd",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenydd&mode=view&person=colwyn-awenydd",
            "imageKey": "hof-heads-2"
          },
          {
            "name": "Derfel Awenydd",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenydd&mode=view&person=derfel-awenydd",
            "imageKey": "hof-heads-3"
          }
        ]
      },
      {
        "id": "heirs",
        "title": "Erbfolge",
        "entries": [
          {
            "name": "Gildas Awenydd",
            "role": "",
            "detail": "",
            "href": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenydd&mode=view&person=gildas-awenydd",
            "imageKey": "hof-heirs-1"
          }
        ]
      }
    ],
    "cadets": []
  },
  "figures": {
    "heading": "11. Historische Figuren",
    "tableTitle": "Persönlichkeiten des Hauses",
    "entries": [
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Persönlichkeit des Hauses",
        "name": "Hafgan Awenydd",
        "description": "Hafgan war vor seinem Sohn Brychan der persönliche Waldläufer des Ratsmagiers Myrddin. Er diente gewissenhaft, erfahren und mit einer Art stiller Heldentat, die nie nach Ruhm verlangte. Hafgan führte gefährliche Wege, barg Relikte und erzog Brychan bewusst als Nachfolger, nicht mit Worten, sondern mit Pflicht und Beispiel. Sein Ende gilt als ungeklärt. Bei der Bergung eines Artefakts im Gebirge von Aldrimar, nahe den Ruinen von Ard Eabhraig, kam es zu einem Einsturz. Hafgan wurde seitdem nicht mehr gesehen. Ob er gefallen ist oder nur verschollen, weiß niemand sicher – doch für Haus Awenydd gilt er als verloren im Dienst.",
        "imageKey": "haus-figur-1"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Persönlichkeit des Hauses",
        "name": "Brychan Awenydd",
        "description": "Brychan ist der persönliche Botengänger und Beschaffer des Ratsmagiers des Grafen, Myrddin. Er ist kein Botenjunge, sondern ein Waldläufer, der gefährliche Wege, verlassene Ruinen und heikle Aufträge übernimmt, wenn Diskretion und Zuverlässigkeit gefragt sind. Er birgt Artefakte, beschafft seltene Güter und trägt Botschaften, die niemand sonst tragen soll. Er arbeitet gemeinsam mit seinen Söhnen, die er bewusst als Nachfolger ausbildet – so, wie sein Vater es einst mit ihm tat. Kein Pathos, keine Romantik: Auftrag, Weitergabe, Pflicht.",
        "imageKey": "haus-figur-2"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Persönlichkeit des Hauses",
        "name": "Idnerth Awenydd",
        "description": "Idnerth gehört zum engeren Gefolge des Erzritters Sir Owain Draig, des Herolds des Königs, und dient diesem als Vertragsmeister. Seine Aufgabe ist nicht ritterlich im klassischen Sinn, sondern juristisch, verbindlich und von großem politischem Gewicht: Er verhandelt, prüft und besiegelt Abkommen im Namen seines Herren. Aufgrund dieser Tätigkeit ist Idnerth oft monatelang unterwegs und nur selten beim Hause Awenydd anzutreffen. Den Großteil seiner Zeit verbringt er in der Hauptstadt Cenyrs, nahe dem Hof und der Kanzlei seines Herren. Seine Familie lebt ohne ihn auf dem Lehen und besucht ihn nur gelegentlich – eine Trennung, die Idnerth pflichtbewusst hinnimmt. Dienst geht vor Nähe, wie es seiner Herkunft entspricht.",
        "imageKey": "haus-figur-3"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Persönlichkeit des Hauses",
        "name": "Amren Awenydd",
        "description": "Amren diente einst als Knappe unter Sir Owain Draig und steht ihm nun als Ritter im Gefolge zur Seite. Er begleitet seinen Herrn auf Reisen und übernimmt jene Aufgaben, für die dem Erzritter oft die Zeit fehlt – vor allem die Aufsicht, Ausbildung und Disziplin der Pagen und Knappen. Sein Verbleib im Gefolge ist nicht dauerhaft: Eines Tages wird er aus dem Dienst entlassen und zu Haus Awenydd zurückkehren. Bis dahin bleibt er, wo er gebraucht wird – an der Seite des Erzritters.",
        "imageKey": "haus-figur-4"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Persönlichkeit des Hauses",
        "name": "Gwern Awenydd",
        "description": "Gwern ist ein gebildeter Kämmerer mit scharfem Verstand und klaren Ambitionen. Einst strebte er das Amt des Vogtes bei den Draigs an, doch der Weg nahm eine andere Wendung. Er teilt mit seinem Gönner Sir Owain Draig eine ausgeprägte Liebe zu Pferden – eine Gemeinsamkeit, die sein Schicksal bestimmte. Heute verwaltet Gwern das persönliche Gestüt des Erzritters, gelegen im Umland von Gwynthor. Der Umstand ist beinahe ironisch: Das Gestüt liegt nahe der Burg und dem eigenen Gestüt seines Hauses Awenydd. Gwern versieht diesen Dienst sorgfältig, kompetent und ohne Bedauern – weniger Macht, dafür Verantwortung, die zu ihm passt.",
        "imageKey": "haus-figur-5"
      },
      {
        "group": "Persönlichkeiten des Hauses",
        "role": "Persönlichkeit des Hauses",
        "name": "Arthen Awenydd",
        "description": "Arthen, der 14-jährige Sohn Idnerths, dient als Knappe im Gefolge von Sir Owain Draig. Er findet seine Rolle aufregend und lehrreich, doch die Realität ist ernüchternd: Er teilt seinen Knappenstatus mit mehreren anderen, und Owain selbst ist fast ständig überlastet. Für Arthen ist das frustrierend. Er idealisiert den Erzritter und bekommt ihn doch nur selten zu sehen. Bewunderung aus der Ferne, Ausbildung im Schatten – eine frühe Lektion darin, wie wenig Zeit große Männer haben.",
        "imageKey": "haus-figur-6"
      }
    ]
  },
  "familyTreeEmbed": {
    "src": "../Stammb%C3%A4ume/Stammbaum.html?family=haus-awenydd&mode=view",
    "title": "Stammbaum von Haus Awenydd"
  },
  "trivia": [
    "Folgt …"
  ]
};
